### ISSUE TITLE
Addresses are not being removed correctly on backend

### ISSUE THREAD

**Issue by deividfdez** [DiscipleTools/disciple-tools-mobile-app#10]
This is the JSON that is being sent: “contact_address”: Array [ Object { “delete”: true, “key”: “contact_address_c8d”, },]

**Comment by cairocoder01** [comment]
This is related to https://github.com/DiscipleTools/disciple-tools-theme/pull/735

**Comment by corsacca** [comment]
@deividfdez this should be fixed now. Can you confirm?
