### ISSUE TITLE
Add UI feedback when comment is saved

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#113]
When adding a comment to a contact, the message does not instantly disappear when clicking the send button. There is no indication that the message is being sent, so it would be common for a user to click the send button again (causing the comment to be saved twice).

Instead, a user clicks the send button, the text field should be disabled until it is sent. There is already a loading indicator, but it was not clear the first time I tried this.

## Requirements ##
When clicking the send button for contact/group comments:
* [ ] Disable text field until comment is saved
* [x] Disable send button until comment is saved
* [x] Re-enable text field after comment is saved
* [x] Re-enable send button after comment is saved.

Related to #35

**Comment by zdmc23** [comment]
Disabled text fields are typically “grayed out”. Please indicate this with gray text field color. If you want color specifics, check some of the answers here: https://stackoverflow.com/questions/16176346/what-color-do-disabled-text-boxes-in-html-uses
