### ISSUE TITLE
v1.1.0 `release` branch issue placeholder

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#116]
NOTE: All of the issues in the comments that follow below were observed using iOS 13.1.3 (iPhone XR) and D.T v1.1.0 (Expo `release` channel: https://expo.io/@discipletools/discipletoolsapp?release-channel=release), and this 1st comment issue was also observed with D.T v1.2.0 on both iOS and Android

**Comment by zdmc23** [comment]
Crash 2 - Steps to reproduce:

TBD

![F9ED7881-ECCC-4F2A-B440-5F59C4831616](https://user-images.githubusercontent.com/191707/69480739-28fd3000-0dd8-11ea-8c41-684bd780e048.png)

**Comment by zdmc23** [comment]
![5028B8F1-BE35-4998-AEF5-24AC1794D797](https://user-images.githubusercontent.com/191707/69480740-28fd3000-0dd8-11ea-89e7-cd4a2de30309.png)

**Comment by zdmc23** [comment]
Unable to save `Coaching` value - Steps to reproduce

1. Select `GH Issue 51` Contact
1. Swipe to `Connections`
1. Click `Edit`
1. Add `zdmc23` to Coached field
1. Click `Save`

![BAAC9267-E9DB-4BE7-A807-5657398EF8E6](https://user-images.githubusercontent.com/191707/69480741-28fd3000-0dd8-11ea-8573-5bccc4e58a1b.png)

**Comment by zdmc23** [comment]
Unable to save `Sub-assigned to` value - Steps to reproduce

1. Select `GH Issue 51` Contact
1. Click `Edit`
1. Add `GH Issue 51` to `Sub-assigned to` field
1. Click `Save`

NOTE: It probably is *should* not be valid to Sub-assign a Contact to its own self, but I think that this error is not indicating this logic, but rather a similar error to that of the Coaching error in the comment above.

![417E1266-AF3A-475D-A822-A86DDEB13EB3](https://user-images.githubusercontent.com/191707/69480742-28fd3000-0dd8-11ea-887d-5d0d957d8217.png)

**Comment by zdmc23** [comment]
Email field displays with multiple commas for empty strings - Steps to reproduce:

(From D.T *WEBSITE*)

1. Select `GH Issue 51` Contact
1. Add empty `Email` value
1. Click `Save`

(Mobile App)

1. Select `GH Issue 51` Contact

![3E7EA038-DC0A-4190-8075-6ED6688EC19D](https://user-images.githubusercontent.com/191707/69480744-2995c680-0dd8-11ea-9c94-88134feab33a.jpeg)

**Comment by zdmc23** [comment]
Age and Gender Input fields *appear* to be missing in Edit mode - Steps to reproduce:

1. Select `GH Issue 51` Contact
1. Click `Edit`

![6B1CC419-317D-40E2-A64E-42B1C9D53CF5](https://user-images.githubusercontent.com/191707/69480745-2995c680-0dd8-11ea-9372-535399e3cfe7.png)

**Comment by zdmc23** [comment]
Age display reflects different value than Age input/entry - Steps to reproduce:

1. Select `GH Issue 51` Contact
1. Click `Edit`
1. Click `Age` input, and select `26-40 years old`
1. Click `Save`
1. Observe that `Age` is displayed as `<41` (which is technically accurate, but confusing as to why the value would change for display)

![AF08D781-0014-4363-9762-ACF66FB4743B](https://user-images.githubusercontent.com/191707/69480746-2995c680-0dd8-11ea-9fca-4ed8f02367bf.png)

**Comment by zdmc23** [comment]
Group Status color change isn't reflected in Edit mode - Steps to reproduce:

1. Click `Groups` Tab icon
1. Select `Yet Another Group`
1. Click `Edit`
1. Toggle the `Group Status`

The color change is only reflected after Save, but it should be reflected as soon as the User makes the selection.  If the User clicks `Cancel`, then trigger an Auto-Refresh so the proper color will be reflected.

![589988CD-114E-4867-B1C8-B8C7FA195BDE](https://user-images.githubusercontent.com/191707/69480747-2995c680-0dd8-11ea-81b0-ae8ed74c287b.png)

**Comment by zdmc23** [comment]
Virtual Keyboard is covering the Comment Text Input field - Steps to reproduce:

1. Click `Groups` Tab button
1. Select `Yet Another Group`
1. Swipe to `Comments and Activities`
1. Click in Comment Text Input field

![F9ACBD20-1898-4F40-8F59-99791D8EAFD9](https://user-images.githubusercontent.com/191707/69480748-2995c680-0dd8-11ea-8aa1-f065193d2858.png)

**Comment by zdmc23** [comment]
![FD6F5F70-64EA-4DFE-BA9F-241965E4A2EB](https://user-images.githubusercontent.com/191707/69480749-2995c680-0dd8-11ea-9f22-b59d456dddfa.png)

**Comment by zdmc23** [comment]
![488DC1D0-745C-426F-B1BC-9C658608593C](https://user-images.githubusercontent.com/191707/69480750-2995c680-0dd8-11ea-99b1-0bb37fc450c6.png)

**Comment by zdmc23** [comment]
![899C454E-6152-431A-B39C-614C6DBE0F69](https://user-images.githubusercontent.com/191707/69480751-2995c680-0dd8-11ea-8fb7-d223bf5a4f6c.png)

**Comment by zdmc23** [comment]
![B94E3FCA-3183-463A-A56F-8EDD56BA0289](https://user-images.githubusercontent.com/191707/69480752-2a2e5d00-0dd8-11ea-9756-30e6b5b5264d.png)

**Comment by mikeallbutt** [comment]
Hi - using version 1.2.0 in offline/aeroplane mode, I got these crash logs:

![Screenshot_20191123-052831](https://user-images.githubusercontent.com/43966676/69481980-92327280-0ddb-11ea-847d-e5187e277b35.png)
![Screenshot_20191123-053115](https://user-images.githubusercontent.com/43966676/69481981-92327280-0ddb-11ea-9a5e-7c149c55144f.png)

**Comment by zdmc23** [comment]
> Hi - using version 1.2.0 in offline/aeroplane mode, I got these crash logs:
> ...

Hi @mikeallbutt , I reopened Issue #62 , would you please also add your screenshots there. Thx!

**Comment by mikeallbutt** [comment]
I got this bug on Android 9 on a moto g(6):
Sign in for the first time, and the Contacts view has no contacts, until you pull down to refresh the view. 
I did a test by signing out then back in and also used 2 different sign ins with different users, and this issue persited.

**Comment by mikeallbutt** [comment]
@zdmc23 I am pretty sure this is no longer and issue.
