### ISSUE TITLE
X doesn’t delete

### ISSUE THREAD

**Issue by johnj246810** [DiscipleTools/disciple-tools-mobile-app#128]
**Describe the bug**

When you click on the “X” in the search bar it doesn’t immediately do anything. It does not delete the contents of the box. (It takes 2 clicks on the "X" bc the first click only closes the virtual keyboard)

 **Steps to reproduce**
1. Go to search bar
2. Click on X
3. Nothing happens

 **Expected behavior**

Deletes contents 

 **Smartphone specs**
 - Device: iPhone 6S and Android
 - OS: Latest
 - App Version: 1.2.0 (Expo)

**Comment by zdmc23** [comment]
@johnj246810 Try clicking twice.  It looks like the first click will close the virtual keyboard, and the second will actually clear the Search field

**Comment by mikeallbutt** [comment]
> @johnj246810 Try clicking twice. It looks like the first click will close the virtual keyboard, and the second will actually clear the Search field

Yes @johnj246810 clicking twice does work, but that is not what a user should have to do.

**Comment by mikeallbutt** [comment]
Another thing related to this is that search field keeps text but does not use it after returning from a contact. 
Steps to reproduce:
Type in the search field
View a record
Return to the list view
The text is still in the search box but not using it to refine the list.

The image below is what the screen looked like after returning to the list after viewing a contact that had the word 'test' in the name. So you can see that the list no longer just showing rows with the word 'test' in them.

![Screenshot_20191205-011555](https://user-images.githubusercontent.com/43966676/70256583-52aa4580-174e-11ea-8b68-14feec318632.png)

**Comment by jl0325** [comment]
We updated search Bar in sprint 11 and now don't have that issue: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/71950968-3fecbb80-31a7-11ea-92c0-908f3ab0c42d.gif)

**Comment by zdmc23** [comment]
Hi @jl0325 , yes, ‘X’ click works now, but please see @mikeallbutt ‘s comment as that issue remains:

Steps to reproduce:

1. Type in the search field
1. Select a Contact or Group
1. Click Back button from Contact or Group Details Screen

The text remains in the search box but not using it to refine the list. Please ensure that the field is cleared

**Comment by jl0325** [comment]
We carry out flow tests on different IOS and Android devices, and when you do a search in this case "hans" the filter and when the item is selected, it redirects to the detail and when returning, keeps the filter and the text applied in the SearchBar component

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10079527/72809472-ad79fc80-3c29-11ea-821d-02a3f9fa9dbc.gif)
