### ISSUE TITLE
Endpoints not responding

### ISSUE THREAD

**Issue by deividfdez** [DiscipleTools/disciple-tools-mobile-app#13]
Several endpoints are not responding while loading contact or group views. Error 400, Type Error: Already read

**Comment by cairocoder01** [comment]
@deividfdez Can you provide the full details of how to reproduce this? Which endpoints? What data are you sending? Any specific contacts or groups that this happens on?

**Comment by deividfdez** [comment]
contact_address, contact_email, contact_phone, contact_facebook, contact_instagram, contact_other, contact_skype, contact_twitter 

https://dtappdemo.wpengine.com/contacts/42/
https://dtappdemo.wpengine.com/contacts/43/

**Comment by cairocoder01** [comment]
@deividfdez I am able to make a request to get contact details from the API (see screenshot below), so could you please provide more details about how to reproduce this issue? Is the original endpoint error 400 something that happens every time you try to request it, or is it an intermittent issue? I don't understand how that list of contact fields relates to the endpoint error, so please clarify the issue and how to reproduce it.

![image](https://user-images.githubusercontent.com/44169599/61203114-c4272000-a6e9-11e9-8bde-842f363370c5.png)

**Comment by deividfdez** [comment]
Error 400 was because of the way the mobile request was processed, issue solved
