### ISSUE TITLE
Crashes when Required Field is left empty

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#133]
The app crashes when on the Add New Contact (or Add New Group) page, when nothing has been entered in the required fields of Full name (or Group Name) and the save button is pressed.

**Comment by zdmc23** [comment]
@mikeallbutt Can you re-test this one with the latest changes?  It's not crashing for me with latest changes.  That said, we should have a discussion as to whether a user should be able to save a Contact/Group without entering a Name

**Comment by mikeallbutt** [comment]
> @mikeallbutt Can you re-test this one with the latest changes? It's not crashing for me with latest changes. That said, we should have a discussion as to whether a user should be able to save a Contact/Group without entering a Name

@zdmc23 you are correct. It doesn't crash. But one the very next screen after pressing save, there is no 'edit' button so you can't make any changes.

Yes there should be a message that informs users that they must write a name of the contact or group. It is a required field.
