### ISSUE TITLE
Group: missing church start date field

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#134]
The Group screen is missing church start date field. It is also not on the groups edit screen.

**Comment by mikeallbutt** [comment]
This is a very important field and issue that needs to be implemented asap.

**Comment by zdmc23** [comment]
> This is a very important field and issue that needs to be implemented asap. @zdmc23 this needs to be in the next milestone.

Done. Added to Sprint 12

**Comment by jl0325** [comment]
![Screenshot_2020-01-12-13-28-20-844_host exp exponent](https://user-images.githubusercontent.com/10079527/72223688-bb4fc380-353f-11ea-91f2-80dbd2b3d921.jpg)
![Screenshot_2020-01-12-13-28-40-980_host exp exponent](https://user-images.githubusercontent.com/10079527/72223690-bb4fc380-353f-11ea-8db2-a8c761356c19.jpg)
![Screenshot_2020-01-12-13-28-38-539_host exp exponent](https://user-images.githubusercontent.com/10079527/72223689-bb4fc380-353f-11ea-87bf-72c3f40f791f.jpg)

**Comment by zdmc23** [comment]
Verified on iOS
