### ISSUE TITLE
Edit group: locations field box has 'Select geonames' and not 'Select locations'

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#135]
On a group details screen that has no location set in the Locations field has 'Select geonames' and not 'Select locations'.

People Groups field is correct.

**Comment by mikeallbutt** [comment]
This same issue happens for Group Coach too.

**Comment by mikeallbutt** [comment]
@zdmc23 another easy fix I would think.

**Comment by zdmc23** [comment]
Fields continue to show “Select coaches” and “Select geonames”. It should be “Select Group Coach” and “Select Locations” respectively

![37D5BB26-6BF1-4AF7-8918-21D051A3F596](https://user-images.githubusercontent.com/191707/72682821-4f211280-3a9f-11ea-94e6-afce4a14cbdb.png)
