### ISSUE TITLE
App crash on opening contact

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#14]
When opening contact Zeyn Ibn Mohammed (https://dtappdemo.wpengine.com/contacts/42/), the app gives a number of error messages and fails to be able to refresh again.

OS: Android 9
Device: Google Pixel 3

![image](https://user-images.githubusercontent.com/44169599/60957261-a120f880-a304-11e9-856a-12608eee2cb7.png)

**Comment by deividfdez** [comment]
This was solved with the implementation of tab loading on demand, and temporary fix to remove the repeated values
