### ISSUE TITLE
Remove translation strings for fields already translated.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#157]
For example: contactOverallStatus is available from the settings array.

**Comment by zdmc23** [comment]
@corsacca I wonder whether it's better to have the deployment differ, but merge the projects in POEditor.  I'll need to investigate POEditor a bit further, but this `languages/xy.json` seems to work well for us, so if we were simply using the same translation for that field in POEditor, then we'd be accomplishing the consistency that you want but not needing to rely on API for some fields but not others.

**Comment by corsacca** [comment]
The app uses .json whereas the website uses .po files. I'm not sure we can merge them on poeditor.

I think it might depend if the app is trying to mimic the website as much as possible or trying to offer a different experience. 

Right now i think we are mimicking the UI so we'd expect the options and labels on the app to match the website.  All the fields at this point should be able to get their values from the API. 
Navigation strings tho belong specifically to the app.

**Comment by corsacca** [comment]
@zdmc23 there are still fields that get their values from the theme like
```
"contactOverallStatus": {
      "new": "New Contact",
      "unassignable": "Not Ready",
      "unassigned": "Dispatch Needed",
      "assigned": "Waiting to be accepted",
      "active": "Active",
      "paused": "Paused",
      "closed": "Closed"
    },
    "seekerPath": {
      "none": "Contact Attempt Needed",
      "attempted": "Contact Attempted",
      "established": "Contact Established",
      "scheduled": "First Meeting Scheduled",
      "met": "First Meeting Complete",
      "ongoing": "Ongoing Meetings",
      "coaching": "Being Coached"
    },
    "groupStatus": {
      "active": "Active",
      "inactive": "Inactive"
    },
```

**Comment by zdmc23** [comment]
@corsacca Thanks for reviewing!  We'll reopen and alert the Team that this was not fully completed

**Comment by corsacca** [comment]
Awesome
