### ISSUE TITLE
New drop-down list widget doesn't pre-populate with available values

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#16]
The new drop-down list widget doesn't pre-populate with all available values, and because of this the "Assigned To" value is not displayed in Mobile app (even though it's present on the D.T Website), or available via Filter auto-complete.  It *DOES* work *IF* the D.T Website value happens to be one of the available drop-down options.

**Comment by zdmc23** [comment]
D.T Website behavior:

![Screenshot from 2019-07-13 16-19-10](https://user-images.githubusercontent.com/191707/61176181-40a2ed00-a58a-11e9-8cd4-755477e3da6e.png)

Mobile app behavior:

**Comment by zdmc23** [comment]
Linked to: https://trello.com/c/VtuSdyxL

**Comment by deividfdez** [comment]
@zdmc23 Solved, the necessary lists are obtained when the mobile app login, please review

**Comment by zdmc23** [comment]
![0A7FBBC1-14A2-4E5C-8F0A-7B51F39D7B39](https://user-images.githubusercontent.com/191707/67160423-80623900-f31e-11e9-913b-5cbdf4a69e89.png)

List shows; closing this issue
