### ISSUE TITLE
Add New Contact: reorder items

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#166]
The order of the fields on the New Contact screen be rearranged, to help the user complete the most details in the fast time so that they can get the most relevant info about the user to facilitate followup.

1. Name 
2. Phone
3. Email
4. Social Media 
5. Gender 
6. Initial Comment (this field would look better if it was 2 lines high to begin with)
MORE FIELDS (reduce the amount of white space after the text)
8. Age
9. Address (new field needed!)
10. Locations
11. People Groups
12. Sources

**Comment by mikeallbutt** [comment]
The save button is not visible when the keyboard is activated. It needs to be moved to the top right of the header bar. A “X Cancel” button should be in the header on the top left to replace the arrow pointing left.

![Screenshot_20191213-141513](https://user-images.githubusercontent.com/43966676/70834992-5cbceb80-1dc1-11ea-8bd8-759bc580b427.png)

**Comment by ahillbilly** [comment]
@mikeallbutt the comment is a separate issue (bug) from the original issue.  Let's create a new issue.
