### ISSUE TITLE
Instructions to enable mobile app plugin

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#169]
The app can be used with any D.T instance, but the mobile app plugin needs to be installed and activated.
Users will receive this message when they try to log in
```
Code: rest_no_route
Message: No route was found matching the URL and request method
```

The error message needs be changed to a more useful message like:
"The Mobile App Plugin is required and does not seem to be activated on your Disciple.Tools. Click **here** for more information"

I'll work on getting that help page up.

Related to https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/89

**Comment by mikeallbutt** [comment]
The help documentation page is [here](https://disciple-tools.readthedocs.io/en/latest/app/index.html). Is it ok or does it need more info?

**Comment by corsacca** [comment]
Thanks Mike. Looks good for now, we'll add more as we go.

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/90031012-a6ddd000-dcb4-11ea-9c3f-78bdbf35f45a.png)

**Comment by corsacca** [comment]
Me can point to this page: https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/169

**Comment by raschdiaz** [comment]
Hi @corsacca there is a way to replicate this flow? Which DT instance we can use?

**Comment by raschdiaz** [comment]
Upon investigation, we discovered that the current toast library does not support an option to perform the 'tap' action.

To support the link behavior, we will have to use a different toast library. But this could break the visual flow of the user, since the 'toast' element would have a different design.

We found this library: [https://github.com/ywein/react-native-another-toast](https://github.com/ywein/react-native-another-toast).

**Comment by corsacca** [comment]
@raschdiaz try to use app with any D.T instance that does not have the mobile plugin activated.

I'd suggest we don't try to put everything in the toast.

The toast could say: Configuration needed on [the url they entered].

And we put this message on the login screen instead:
"The Mobile App Plugin is required and does not seem to be activated on your Disciple.Tools. Click **here** for more information"

**Comment by raschdiaz** [comment]
Hi @corsacca @mikeallbutt @zdmc23 @ericchen59  see the following video showing the implementation:

[https://drive.google.com/file/d/1jWRYDcMjePlGBNR--2u9fDA3tLdZ7Jjs/view?usp=sharing](https://drive.google.com/file/d/1jWRYDcMjePlGBNR--2u9fDA3tLdZ7Jjs/view?usp=sharing)

We test this flow using a local D.T. instance, disabling the 'Disciple Tools - Mobile App Extension' plugin in the D.T instance.
