### ISSUE TITLE
Error on end-point authentication for version 2

### ISSUE THREAD

**Issue by deividfdez** [DiscipleTools/disciple-tools-mobile-app#18]
The end-point  authentication: https://dtappdemo.wpengine.com/wp-json/jwt-auth/v2/token

When we try to connect, end-point send this error message:

{
   “code”: “rest_cannot_access”,
   “message”: “Only authenticated users can access the REST API.“,
   “data”: {
       “status”: 401
   }
}

**Comment by corsacca** [comment]
@deividfdez there is no v2 for this endpoint.
