### ISSUE TITLE
Cannot find  some end-points v2

### ISSUE THREAD

**Issue by deividfdez** [DiscipleTools/disciple-tools-mobile-app#19]
https://${domain}/wp-json/dt/v1/users/get_users?s=
https://example.com/wp-json/dt/v1/mapping_module/search_geonames_by_name
https://${domain}/wp-json/dt/v1/people-groups/compact

We need to know which are the end-points V2 for these ones

**Comment by corsacca** [comment]
Only contacts and groups right now have the v2 endpoints.
The rest can stay in v1.
