### ISSUE TITLE
Groups > Members: list of members missing

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#190]
This screen should have the number of members in the group listed.

When there are members but they aren’t listed, we need a way to request them to be loaded.

When there are no members in a group (ie Child Church), the members screen only has the heading “Members”. It should have a message saying ”No members. Click edit to add some members to this group”.

**Comment by zdmc23** [comment]
![C892D722-B2CB-44F2-BEE5-91573FC0FE0F](https://user-images.githubusercontent.com/191707/75634637-7d852800-5bdd-11ea-89ac-9174b4ff172e.png)
![E631A90C-E4D2-4173-BF8D-5C250943963B](https://user-images.githubusercontent.com/191707/75634640-7e1dbe80-5bdd-11ea-8c73-206243e01286.png)

**Comment by zdmc23** [comment]
Verified on iOS w/ Expo
