### ISSUE TITLE
Enable Linking for Phone and Email

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#193]
Per @ChrisChasm 

Our DMM team is using the mobile app, but a simple user experience issue I keep hitting is that I can’t tap the email or phone number and copy or jump to using that data. It seems small but a big UI win to allow email to jump out to my email client and phone to jump to a call or message.

I have iOS / iPhone 11. (But we want this to work with Android also)

Acceptance Critera:
- Enable proper link scheme for phone (`tel:1-408-555-5555`) and email (`mailto:frank@wwdcdemo.example.com`) using the RN `Linking` component (like we're already doing on the Login Screen)

https://docs.expo.io/versions/latest/workflow/linking/
https://facebook.github.io/react-native/docs/linking.html

**Comment by ChrisChasm** [comment]
Thanks for this. I'm trying to use the app on a daily basis and the behavior I find blocked is that as I pull out the app and begin working contacts, I want to first tap their phone number and either copy (which isn't working on iPhone 11) and paste into a new message conversation or tap it and make a phone call; if that was not available then I would want to tap their email and start a new email conversation. 

This small upgrade is a big block for my daily usage of the app.

**Comment by jl0325** [comment]
Latest PR have this function! 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/74089599-dba46c80-4a70-11ea-8166-f51eb7a763e4.gif)
