### ISSUE TITLE
Login often gets stuck in loading state

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#196]
iPhone via Expo

Steps to reproduce:

1. Enter URL and Credentials, and click `Log In` button

![1A83201C-D888-44F4-9412-B33598879256](https://user-images.githubusercontent.com/191707/73809796-571cca00-47a2-11ea-9028-c45f34107279.jpeg)

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ahillbilly , after some testing and fix, the app will quit their 'loading' state if any of the login end-point return error (of any reason), show again the 'login' button so the user can try again the 'login' process.

The following error will show if the app get timeout error (or any similar error):
[https://drive.google.com/file/d/1S9EEWsexH7Xc_-gU6hcMi1PU7ageTDuc/view?usp=sharing](url)

Now, when we test the login process when the app lose internet connection, this error its appearing in the app (related to the push notification):
[https://drive.google.com/file/d/1FwhMX7Sf40A0t1nM8hEmX0_DsVy7qruT/view?usp=sharing](url)

**Comment by zdmc23** [comment]
![31E44A3D-9E90-42D3-B0DD-8BE7E2F2E74B](https://user-images.githubusercontent.com/191707/75634562-0fd8fc00-5bdd-11ea-9418-ed7759139fc5.jpeg)

**Comment by zdmc23** [comment]
![D546DBB2-AD26-4E03-8544-5B86C870ECEF](https://user-images.githubusercontent.com/191707/75634583-21ba9f00-5bdd-11ea-820b-173ff9d60c04.png)
![A12C5529-E3EE-4D6C-BC48-DC87FB860094](https://user-images.githubusercontent.com/191707/75634585-22533580-5bdd-11ea-915a-cf08f6af10c5.png)

**Comment by zdmc23** [comment]
![36ED57B0-ED38-4532-9B87-807DA285EE71](https://user-images.githubusercontent.com/191707/75634609-4b73c600-5bdd-11ea-9181-ba2405e808ac.png)

**Comment by zdmc23** [comment]
@raschdiaz I am re-opening this Issue bc the following sequence does not work using iOS w/ Expo:

1. Login
1. Click `Settings` Tab
1. Disable `Keep logged in`
1. Swipe close Expo app
1. Relaunch Expo app
1. Get prompted for Login (as expected per #60)
1. Login
1. Click `Settings` Tab
1. Enable `Keep logged in`
1. Swipe close Expo app
1. Relaunch Expo app
1. App *should* log-in and auto-navigate to Contact List, but I am prompted by Login Screen again.

**Comment by zdmc23** [comment]
Mobile App is receiving a 504 from the D.T API:

```
<!DOCTYPE html>
<html>
<head>
    <title>Error Loading Site | 504 Gateway Timeout</title>
</head>
<body>
    <style>
@import url(//fonts.googleapis.com/css?family=Open+Sans:300);
    body {
    color: #343434;
    font-family: 'Open Sans Regular', Helvetica, Arial, sans-serif;
    font-size: 16px;
    font-weight: 300;
    line-height: 1.2;
    margin: 50px 25px;
    }
    h1,h2,h3,h4,h5,h6 {
    font-weight:300;
    margin:5px 0 25px;
    padding:0;
    }
    h1 {
    font-size: 100px;
    margin:5px -5px 10px 0;
    }
    hr {
    background:#DFDFDF;
    height: 1px;
    border:0;
    margin: 40px 0 30px;
    }
    </style>
    <h1>504</h1>
    <h2>The page request was canceled because it took too long to complete</h2>
    <hr>
    <p><strong>What can I do?</strong></p>
    <p></p>
    <p><strong>Site visitors:</strong> There was an issue serving your request,
    please try again in a few minutes.</p>
    <p><strong>Site Owners:</strong> There was a gateway timeout. You should
    visit your error log for more information.</p>
</body>
</html>
```
