### ISSUE TITLE
Save of Contact/Group info often results in API error

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#197]
iPhone via Expo

Steps to reproduce:

1. `Edit` Group Progress
1. Click `Save`
1. Observe error message 
1. Click `Save`
1. Observe success message

![56B69E56-ED11-4EFB-9B95-3FE6BC08E588](https://user-images.githubusercontent.com/191707/73809952-d1e5e500-47a2-11ea-8277-0ab425028511.png)

**Comment by deividfdez** [comment]
@zdmc23 this issue needs to be solved by @corsacca . Can you please check on that?

**Comment by corsacca** [comment]
I'm pretty sure this was due to a bug in the notifications section of the plugin. I've fixed it now and push the update.
