### ISSUE TITLE
Keyboard on login screen

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#2]
When the keyboard is open, the user can't see the password input. 
The page content should be pushed up
![Screenshot_20190605-152042_Expo](https://user-images.githubusercontent.com/24901539/58966879-ff5d3780-87aa-11e9-93a3-a2cea29a92db.jpg)

**Comment by yorkaspacher** [comment]
Group details info feels a little small, too close together, not spaced comfortably - what are they using for benchmark / standard? @cairocoder01 - I thought I remembered you having some standards / guidelines on this subject, as far as the size of a hotspot onscreen to accommodate the human fingertip...? :-)

**Comment by yorkaspacher** [comment]
Groups - Details: Address 1 & 2 fields have pre-populated "1" & "2" in them, and they stay when you tap to enter your data, you have to manually delete them before you enter text

**Comment by yorkaspacher** [comment]
What about date format - should it default based on your language? Location? (22/5/2019 vs 5/22/2019)

**Comment by deividfdez** [comment]
Got it, and doing the update!
