### ISSUE TITLE
Add New Contact Workflow: Save not visible/accessible when keyboard is displayed.

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#200]
The save button is not visible when the keyboard is activated. It needs to be moved to the top right of the header bar. A “X Cancel” button should be in the header on the top left to replace the arrow pointing left.

![Screenshot_20191213-141513](https://user-images.githubusercontent.com/43966676/70834992-5cbceb80-1dc1-11ea-8bd8-759bc580b427.png)

**Comment by zdmc23** [comment]
@ahillbilly If we go this direction (and I believe that we should for consistency sake), then we will break from mimicking the D.T Mobile Website.  That's fine too, but I just want to clarify that the Team understands that in general we are mimicking the D.T Mobile Website, but that there are specific places where the App differs

**Comment by ahillbilly** [comment]
@zdmc23 , correct and agreed.  We need to choose wisely when and where to deviate, but this one seems to warrant the deviation both for consistency across screens and and for improved usability overall.

**Comment by jl0325** [comment]
> The save button is not visible when the keyboard is activated. It needs to be moved to the top right of the header bar. A “X Cancel” button should be in the header on the top left to replace the arrow pointing left.

About the change of icon and replace with an 'x' I would like to point out that it would not be convenient as it is a navigation button to the previous window.
