### ISSUE TITLE
Add New Contact Workflow: Field areas border line not visible for selection of dropdown fields

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#201]
Text fields and multi-select fields have a grey box around the data field so you know where to press to edit.  The single select dropdown fields have no border making it hard to find the dropdown field to open the list.

iPhone 10 used for test.

**Comment by ahillbilly** [comment]
This is true also for date fields and is not limited to the adding a new contact workflow, but is an always present issue for contact records.

**Comment by raschdiaz** [comment]
![Screenshot_2020-02-07-16-41-18-986_host](https://user-images.githubusercontent.com/16809967/74068288-3d110080-49c9-11ea-897d-18c7d393e3ac.jpg)
![Screenshot_2020-02-07-16-41-25-354_host](https://user-images.githubusercontent.com/16809967/74068293-3edac400-49c9-11ea-906c-06598d93a924.jpg)
![Screenshot_2020-02-07-16-41-36-065_host](https://user-images.githubusercontent.com/16809967/74068295-400bf100-49c9-11ea-8600-3ad82ea85f8b.jpg)
![Screenshot_2020-02-07-16-41-49-857_host](https://user-images.githubusercontent.com/16809967/74068300-413d1e00-49c9-11ea-8445-79509b23cd7a.jpg)
