### ISSUE TITLE
Add New Contact Workflow: Email duplicated and saved as both email and social media data

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#202]
When adding a contact, I input an email address in the email field and saved the contact.  When I opened the new contact the email address was duplicated.  It was saved both as an email and as a social media data point.  

This should be saved only as an email address.

Tested on iPhone 10

**Comment by raschdiaz** [comment]
![Screenshot_2020-02-06-16-46-17-842_host](https://user-images.githubusercontent.com/16809967/73982038-84cc5500-4901-11ea-8564-77770800a784.jpg)
![Screenshot_2020-02-06-16-46-37-128_host](https://user-images.githubusercontent.com/16809967/73982043-87c74580-4901-11ea-99aa-14a3fca85193.jpg)
![Screenshot_2020-02-06-16-47-52-960_host](https://user-images.githubusercontent.com/16809967/73982048-8a299f80-4901-11ea-8194-25b58f39e373.jpg)
