### ISSUE TITLE
Change in "Assigned to:" field - should change status to "Waiting to be Accepted"

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#205]
I assigned a contact to another user.

The contact status should change to "Waiting to be Accepted"... it does this on the web version.

I clicked save on the assignment change and the record status is still "Active".

**Comment by raschdiaz** [comment]
@corsacca , can you check this please?

**Comment by corsacca** [comment]
This is currently the same behavior on the website. The contact status is changed to "Waiting to be Accepted" only if assigned by a dispatcher.
I've tested the app ui and it works as expected as a dispatcher.
@ahillbilly let's have a look on website and come back to the app if we need to.
