### ISSUE TITLE
Edit Contact Record (Progress tab): Baptism Date field takes to a blank white screen

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#206]
I went to add a baptism date.  

I clicked edit and the baptism date field shows "Select Date".  I press "Select Date" and am taken to a completely white screen.  no header, no anything, just bright white.  (I can tap the white screen and it takes me back to the edit Progress screen).

I cannot set the baptism date.

**Comment by zdmc23** [comment]
@ahillbilly is your iPhone in Dark Mode? If so, that’s unfortunately a known issue with React Native. Try switching to Light Mode and check again. Thx!

**Comment by ahillbilly** [comment]
haha, new phone.  Yes, in dark mode.

**Comment by ahillbilly** [comment]
Do "wontfix" issues ever get closed or do they stay open to show ongoing awareness?

**Comment by zdmc23** [comment]
@ahillbilly If/when we get our Issue count down, then I'd be tempted to close them out.  Until then, I think it's good to leave them open bc the default Issue search is `open` items, and if someone performs a default search and doesn't find their search terms then they are more likely to enter a duplicate issue (that we `wontfix`) than to re-search while including the `closed` items
