### ISSUE TITLE
Notifications: link to referenced record missing

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#208]
See web version.  Notifications reference a record and should link to that record from the notification.

**Comment by raschdiaz** [comment]
Hi @ahillbilly , when the user go to detail view through the notification link, and later tap the 'return' button, where the app have to go?, to the 'notificationList ' view or Contact/Group List view respectively?

**Comment by ahillbilly** [comment]
Going back to the notifications list would be preferable.
