### ISSUE TITLE
PIN code login while offline and/or unauthenticated

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#224]
PIN code login support is implemented per #146 in coordination with #60, but there is a more complex scenario to support which we initially punted on and that is to enable PIN code login when there is no existing and/or valid JWT Token.  This scenario also applies to the previously discussed case of enabling the app in "Offline Mode" to folks who download it and want to experience it without having a valid D.T Instance account to authenticate with.

The complexity is in the authentication flow when the app *does* come `online` and/or when the user is ready to authenticate with a D.T Instance.  There will need to be some changes around what API calls occur at login, because we will want to first submit all of our queued `offline` work, and there also needs to be a UI change to enable navigation to the Login Screen (which is currently only on app load)

**Comment by ericchen59** [comment]
[DTMA-13]

**Comment by zdmc23** [comment]
Exists as of v1.11
