### ISSUE TITLE
Duplicate default list filters from the website.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#226]
The filters help navigate contacts and focus on the ones to take the next steps with.

![image](https://user-images.githubusercontent.com/24901539/74418699-129bc900-4e49-11ea-84e4-aff9bc5d7a01.png)

**Comment by raschdiaz** [comment]
Hi @corsacca this filters are dynamic? There are some end-point to get them?

**Comment by corsacca** [comment]
`/wp-json/dt/v1/users/get_filters?post_type=contacts&force_refresh=1`
You can see that the theme load the cached version and then replaces it with the new version with the `force_refresh`

**Comment by raschdiaz** [comment]
Hi @corsacca , We implemented this feature , see the following video: 

[https://drive.google.com/file/d/1O9FqxdJ1X2J5WOvFVc-U00HitEe0wt2n/view?usp=sharing](https://drive.google.com/file/d/1O9FqxdJ1X2J5WOvFVc-U00HitEe0wt2n/view?usp=sharing)


Additionally, We found several contacts with incorrect JSON structure like this:

![Captura6](https://user-images.githubusercontent.com/16809967/87360026-c3101500-c52e-11ea-9c83-5eadb72d8d1e.PNG)

This can break the mobile app when trying to see their 'Detail info'.

**Comment by mikeallbutt** [comment]
@zdmc23 and @raschdiaz The filter list for contacts is great. Now we need it for the groups. :)
