### ISSUE TITLE
Jittery comment input

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#233]
See
https://drive.google.com/file/d/15bQo7mkQxTL0JrPkBxT0-Fj-bXKy-8GM/view?usp=sharing
Jump between these two:
![signal-attachment-2020-02-26-153005_001](https://user-images.githubusercontent.com/24901539/75354366-26194c00-58ad-11ea-82d1-b14e2633cb94.jpeg)
![signal-attachment-2020-02-26-153005_002](https://user-images.githubusercontent.com/24901539/75354372-27e30f80-58ad-11ea-9ee8-4ffe4a3891d1.jpeg)

**Comment by zdmc23** [comment]
Verified on iOS w/ Expo
