### ISSUE TITLE
Adding Contact/Member to a Group is not reflected in Connections

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#235]
Steps to reproduce:

1. Add a Contact/Member to a Group
1. Click on Contact/Member link
1. Navigate to `Connections` Tab
1. Confirm that this new connection is not reflected in the `Group` field

![54A363C4-E2F0-4D86-B5AB-15688A954232](https://user-images.githubusercontent.com/191707/75634870-6e9f7500-5bdf-11ea-9c45-ead1bdc83759.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 what contact and group you used in this flow?

**Comment by zdmc23** [comment]
Hi @raschdiaz , please see `Atlat` Group and `Zac Contact`

![F0D97237-4C31-4F05-959A-F0877026FF2B](https://user-images.githubusercontent.com/191707/76374928-ee81b980-631a-11ea-8d03-bf8698341f59.png)
![A2F7A9E8-5517-4DB1-8A2F-FFB72A77BAD0](https://user-images.githubusercontent.com/191707/76374940-f4779a80-631a-11ea-95a2-5b6bd03309ac.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , I'm going to review this.

**Comment by raschdiaz** [comment]
Hi @zdmc23 , I have created a new PR (https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/285), when I test this with this changes, the flow works as spected, can you try another test please?.

**Comment by zdmc23** [comment]
Confirmed on iOS
