### ISSUE TITLE
App crashes when selecting Contact Status

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#239]
Observed on Android

Steps to reproduce:
1. Select Group
1. Navigate to Members Tab
1. Select Member to Navigate to Contact
1. Click `Edit` button
1. Select `Contact Status` dropdown
1. Select `Paused`
1. Click `Save` button

Please see video:
- https://youtu.be/jKr8vv1b2dM?t=1107

**Comment by deividfdez** [comment]
@zdmc23 please check, this issue solved with PR 246 where issue #238 was fixed also.

**Comment by zdmc23** [comment]
Confirmed on iOS. Thx @deividfdez 

![53D22B96-7A70-4BDF-98A6-C3A08A9F7C44](https://user-images.githubusercontent.com/191707/76373126-ebd09580-6315-11ea-9b43-fb01033f00a6.png)
