### ISSUE TITLE
Log in button displays, disappears, re-displays a second time

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#242]
Observed on Android

Steps to reproduce:
1. Login (with a slower Internet connection?)

Please see video:
- https://youtu.be/jKr8vv1b2dM?t=642

**Comment by deividfdez** [comment]
@zdmc23 this issue was solved on https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/246 but @raschdiaz forgot to add it into comment. Can you please check and validate?

**Comment by zdmc23** [comment]
Hi @deividfdez and @raschdiaz , I am not sure how it is possible that this Login issue was resolved in #246 when the only changes in that PR were related Contact/Group Details Screens:

https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/246/files

**Comment by deividfdez** [comment]
Hi @zdmc23 we will check again and let you know which PR solved this issue. I will let you know ASAP. @raschdiaz can you please verify this information so Zach can review and validate? Thnks

**Comment by deividfdez** [comment]
Hi @zdmc23 here is the reference where it was fixed: https://github.com/jl0325/disciple-tools-mobile-app/commit/24bfdc074bdd12f371c17a53511954c8b56b3c18#diff-ed10ab7af356cf0709fe8dd227e65e54
Please let me know if it is ok

**Comment by zdmc23** [comment]
Thanks @deividfdez ! I'll close this Issue
