### ISSUE TITLE
Group names missing from Groups List

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#244]
Observed on iOS w/ Expo

Steps to reproduce:
1. Click `Groups` Tab button

Also, clicking on one of Nameless entries causes App to crash and display white screen 

![67660369-4C97-466B-B3F2-5D19A68BC54F](https://user-images.githubusercontent.com/191707/75946750-f9949f80-5e6b-11ea-94fd-33c25ca772ac.png)
![889B9501-8E02-4ED2-8145-8AB951B76DD5](https://user-images.githubusercontent.com/191707/75946751-fa2d3600-5e6b-11ea-8b48-3924d5029101.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , we added a toast message when the user try to create a contact/group without name:

![Screenshot_2020-03-09-15-26-12-974_host exp exponent](https://user-images.githubusercontent.com/16809967/76254423-6ddb9400-621a-11ea-9598-56fff3a452f3.jpg)

**Comment by zdmc23** [comment]
![D991328F-A6EA-4ADF-8E79-7683B8188899](https://user-images.githubusercontent.com/191707/76333096-85248b00-62c7-11ea-97a8-25caf14220b4.png)
