### ISSUE TITLE
Transition from Contact Details to Lists slow

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#245]
Transitioning from the details screen to the lists page lags a bit with the comment input open. 

See https://drive.google.com/file/d/1P-eHWG_xaqViahsAckCxyg_qaajjM2FE/view?usp=sharing

![image](https://user-images.githubusercontent.com/24901539/75989232-2e980500-5ef3-11ea-986c-e991317a8e4d.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , we add a fix to this 'visual lag':

[https://drive.google.com/file/d/1J1oTsVWKhu3HV6gJtPkts5vejUuxjbWW/view?usp=sharing](https://drive.google.com/file/d/1J1oTsVWKhu3HV6gJtPkts5vejUuxjbWW/view?usp=sharing)
