### ISSUE TITLE
Wrong Contact loads on Edit button click

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#250]
I attempt to Edit a Contact (`Zac Contact`), but the details for another Contact (`Jessica Blue`) are loaded instead.

Observed on iOS

Steps to reproduce:
1. Click on `Groups` Tab
1. Select `ZZTestZZ Church`
1. Navigate to `Members` Tab
1. Click on `Jessica Blue` Contact
1. Repeat Steps 1-4
1. Click on `Zac Contact` Contact
1. Click `Edit` button

Please see video:
https://youtu.be/mVJDlw2hCw8

**Comment by raschdiaz** [comment]
Hi @zdmc23 , I'm going to review this.
