### ISSUE TITLE
Receiving an error upon successful login

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#251]
Upon re-opening the Expo App, I receive an initial Error Toast with missing Code and Description, then a successful login occurs, but I receive an Error Toast over the Contact List.

It's likely that 1 of the many D.T API requests failed, but displaying that error to the user does nothing but cause confusion.  If that error prevents usage of the app, then do not log in the user. Otherwise, simply retry the request in the background and do not display the error.

Observed on iOS

Steps to reproduce:
1. Login
1. Swipe Close Expo App
1. Open Expo App and Launch D.T

![A9DE0BA7-2590-4718-ABEB-3F7F5C0236A1](https://user-images.githubusercontent.com/191707/76424650-e8bdbf80-637e-11ea-906a-fd988a8df28a.png)

**Comment by raschdiaz** [comment]
Ok @zdmc23 , if I understand, you are talking about to keep in mind apply another flow in that case right?

**Comment by zdmc23** [comment]
Hi @raschdiaz , Yes, we should have a way to enable background requests and/or retry when one of the requests fails, or we need to prevent the login altogether.  Showing the user an error is unhelpful bc it's confusing. 

Do we understand *why* the requests are failing so frequently?

**Comment by zdmc23** [comment]
Superseded by #292
