### ISSUE TITLE
Request full list of groups or contacts in edit mode

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#253]
I don't get all the list of my contacts when I want to connect someone to someone else or assign them as the person who baptised them.
There is now way to request the full list of names be downloaded.

Contact > Edit > Connections > Relation: Type in a name but if that person I want to assign is not in the first 50 (or how ever many have been downloaded), there is no way to assign the person because their name is not loaded.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt, to achieve this, we can perform a similar flow used in the location fields: When a text is written and the mobile is ONLINE, the application queries and obtains the new locations, displays it in the interface and persists it for later use in OFFLINE mode.

**Comment by zdmc23** [comment]
Hi @raschdiaz , Yes, let's use a similar flow that is already in place for the Location fields.

**Comment by zdmc23** [comment]
This should be auto-resolved by #290

**Comment by zdmc23** [comment]
Resolved by https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/c0b19d50efd6a94571e4c7706616f28358c8e378
