### ISSUE TITLE
Have search list field always available

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#257]
On the Contacts list screen, the search field should be "stuck" to the top. After scrolling to the bottom of the 100 record list and still the person I am looking for is not listed, I currently have to scroll all the way to the top to access the search box again so that I can use search to refine the list.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt see this example flow: [https://drive.google.com/file/d/1PM15FOI8r8rhLUMe8A-hmbT2nc5FqUbQ/view?usp=sharing](https://drive.google.com/file/d/1PM15FOI8r8rhLUMe8A-hmbT2nc5FqUbQ/view?usp=sharing)

As you can see, This change affects the "default filters" component. So we had to stylize it.

**Comment by zdmc23** [comment]
> Hi @mikeallbutt see this example flow: https://drive.google.com/file/d/1PM15FOI8r8rhLUMe8A-hmbT2nc5FqUbQ/view?usp=sharing
> 
> As you can see, This change affects the "default filters" component. So we had to stylize it.

Hi @raschdiaz , why was the extra space (based on Window Height) required? I made a commit to remove that (https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/e4fc5cd737dac4d9a7c72131b2195edb5bafbaad) and it seems to be working fine. Thx!

![D8CBAB39-0561-4346-A373-60B7CCEF175E](https://user-images.githubusercontent.com/191707/88132125-b5046900-cbac-11ea-9804-058b1c042366.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , I set a height based on phone window because when the filter section its open, the user can't scroll down to see the rows.

**Comment by zdmc23** [comment]
Hi @raschdiaz , I think that it's fine to force the user to make a selection one they toggle the filter menu.  If we want to enable an alternative to exit the menu, then perhaps when they click the Contacts Tab, that should close the menu.  Then the user has 3 options to exit the menu:
1. Make a Selection
1. Click the Filter Menu icon
1. Click Contacts Tab icon

**Comment by zdmc23** [comment]
Actually, they would have 4 options to exit: the 4th being to collapse the Accordion component (click `-` sign).  I understand what you were doing, and I appreciate the thought to implement that, but the screen "real estate" is too valuable to leave the blank space.  We still give the user 3 options to exit, and could offer a 4th if we close the Filter Menu when Contacts Tab icon (on Main Tab Bar) is clicked

**Comment by raschdiaz** [comment]
Ok @zdmc23 , thanks for the feedback!

**Comment by mikeallbutt** [comment]
On the Groups list screen, the search field should be "stuck" to the top.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , let’s add a separate issue for reimplementing this for Groups. We want to get everyone on board with look and feel for how it works with Contacts first, and then we’ll reuse code for Groups (rather than implementing both places and then making changes in 2 places)
