### ISSUE TITLE
Align + and - icons in edit details screens

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#259]
On the details edit screen (for both a contact and a group) the fields that use plus and minus icons, have the minus icon left aligned, causing it to not site cleanly under the plus icon.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , I think that we want to rather take Thij's suggestion of reusing the Members interface rather than the (+/-) icons.  That way we have 1 consistent interface for that type of entry
