### ISSUE TITLE
Removed/changed connections that had not been changed

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#262]
This is a big bug.
I was reviewing then went into edit a contact that had many connections to groups and baptising and coaching. Most but not all the connections where removed when I clicked save (after simply modifying the contact name). It would seem that the ones that were not removed, were in the first 100 contacts or groups that had been recently updated.
I now have to go and re-add all the connections - which I will do via the website.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , can you give any example to test this in the mobile app?

**Comment by zdmc23** [comment]
See also #256

**Comment by zdmc23** [comment]
Hi @mikeallbutt , I think that you have a video capture of this issue, correct?  If so, would you kindly paste a link to view here so that @raschdiaz can view it.  Thx!

**Comment by zdmc23** [comment]
@raschdiaz , please see the related examples from #256

**Comment by mikeallbutt** [comment]
I don't have a video, but it can easily be tested simply by editing a contact which has connections, and seeing from the comment activity after saving, that the connections were removed.

**Comment by zdmc23** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/9d65b12b75191b1e92dba97d95584827499ce285
