### ISSUE TITLE
Group members list empty when offline

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#265]
When in offline mode, the members list in the members screen for any group does not display the names of the members. It does correctly display the count and has each row, but the rows do not have the names of the members.

**Comment by raschdiaz** [comment]
Hi, i am working on it.

**Comment by mikeallbutt** [comment]
Maybe I am using the wrong app, but this issue doesn't seem to be resolved. I tested it with the current development version using expo on my android phone. 
I signed into the app, went into offline mode, viewed a group then the members tab -  and the rows are all listed but no contact names next to each footprint.
