### ISSUE TITLE
Group tree inaccurately displaying church commitment 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#274]
In the groups tab of a group, there are groups that should be displaying the unbroken line to represent a group and not a church, while others show they are church when they are only a group. 

![Screenshot_20200316-184749](https://user-images.githubusercontent.com/43966676/76811537-82d69b00-67b7-11ea-9677-9ba9339574ef.png)

**Comment by raschdiaz** [comment]
Hi @corsacca, which property in the response of the '/wp-json/dt-posts/v2/groups/{id}' end-point We can use to know this? (props parent_groups, peer_groups . etc).

**Comment by corsacca** [comment]
@raschdiaz if possible here is what i suggest.
The circle should be solid one of these 2 is true:
- the `group_type` is `church`
- or if the `health_metrics` has `church_commitment` as one of the options.

other wise the circle can be a dotted line

**Comment by raschdiaz** [comment]
Hi @corsacca, when the mobile get the response of the '/wp-json/dt-posts/v2/groups/{id}' end-point, we get the groups data like this:

![Captura3](https://user-images.githubusercontent.com/16809967/81447486-52b9d180-9142-11ea-8fd8-790fd0fdfbfb.PNG)

This data its used to show the Group Tree, which property of this object the mobile has to use to show the plain/dotted circles?

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/81565702-b423af80-9391-11ea-9ce4-f99bd71e608f.png)
@raschdiaz thanks for clarifying. I've added a "is_church" field to each connected group.
If the field is `true` then display the solid circle.
If `false` or if the "is_church" field isn't present then display the doted line.

**Comment by mikeallbutt** [comment]
When using the https://dtdemo.disciple.tools/groups/ data, it is possible to see that somethings still arent correct.

**Comment by zdmc23** [comment]
Per @mikeallbutt 

> the group tree is still an issue. View the “Local Christian Committed Church” and the Groups tab. The parent should not be a full circle.

> https://dtdemo.disciple.tools/groups/ viewing that page then seeing what the app shows is the best way to access the groups to see if the group tree is accurate or not.

**Comment by corsacca** [comment]
https://dtdemo.disciple.tools/groups/ does not have the latest version of the plugin. So the is_church data will not be there yet.
