### ISSUE TITLE
Contact & Group: Tabs not being translated

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#276]
When using DT in Spanish, the tabs are not being translated. They stay in English and are not Spanish. The rest is the app interface is correct, except all the tab words: (Details, Progress, Comments etc.)

![Screenshot_20200318-101642](https://user-images.githubusercontent.com/43966676/76983053-64c98180-6902-11ea-9431-b842cde44721.png)

**Comment by mikeallbutt** [comment]
Until this is fixed, the screenshots for the upcoming release can not be done.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , some of the translation comes from the D.T Website, while other is hardcoded in the Mobile App Release.  In this case, is the D.T Instance that you're logging into configured to display in English?

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt , some of the translation comes from the D.T Website, while other is hardcoded in the Mobile App Release. In this case, is the D.T Instance that you're logging into configured to display in English?

@zdmc23 I tested this with issue with various logins on different instances, and the tabs never displayed in Spanish, even if the DT user was set to use spanish.

**Comment by zdmc23** [comment]
@mikeallbutt Thx!  I've added it to the next Sprint to be fixed
