### ISSUE TITLE
Status icons missing

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#281]
The Contact Status and Group Status icons are not present.

They need to be added on the details and edit screens of both a contact and group.

The following image can be used and has been uploaded to the assets/icons folder.

![status](https://user-images.githubusercontent.com/43966676/77091769-9871dd80-69ce-11ea-9727-099fcc3e4293.png)

**Comment by mikeallbutt** [comment]
Related to this is that the status field doesn't display any information nor the colours when in offline mode.

**Comment by zdmc23** [comment]
Resolved by #438
