### ISSUE TITLE
Title changes from list to record view

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#282]
As can be seen in the following video, the title of the group changes from what is listed on the group list screen to what is used in the group record page.

https://www.youtube.com/embed/Odks2GVI7vc

It seems that it is getting this information from 2 different fields.

**Comment by corsacca** [comment]
This is not an app issue. It is old data returned from the API and is now fixed.

**Comment by mikeallbutt** [comment]
Thanks @corsacca for helping discover what was causing this. It seems that the meta_value was being used from wp_postmeta when the meta_key was set to title. This data is obsolete but the app was using it.
