### ISSUE TITLE
Contact status changes automatically

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#283]
This video shows what is happening with the contact status.

https://www.youtube.com/watch?v=kYymbv2t00A

**Comment by mikeallbutt** [comment]
This issue seems to be resolved.

**Comment by mikeallbutt** [comment]
I have found this is still happening at times (but not always) on different instances.

**Comment by mikeallbutt** [comment]
Yes in version 1.3.0 this still happens. Login to the dtdemo.disciple.tools and view Anna Torres and Brian White.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 We are trying to replicate the error without success. We have tried the examples you provided. We believe that removing an initial variable declaration can solve the problem. But with the devices we have we don't see the change (maybe because the rendering is fast). We are going to make this change, and make a new P.R. for you to test on your device to see if this fixes the behavior.

**Comment by zdmc23** [comment]
@mikeallbutt Would you please provide the details that you described about the contact status switching from new to something else and back again.  Also if you have steps and contacts to reproduce with. Thx!

**Comment by raschdiaz** [comment]
Hi @mikeallbutt like @zdmc23 said, can you provide us some example flow?

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt like @zdmc23 said, can you provide us some example flow?

Something has changed becuse this seems to be fixed in version 1.5.0

**Comment by zdmc23** [comment]
Unable to reproduce in v1.5

**Comment by mikeallbutt** [comment]
@zdmc23 & @raschdiaz  All contacts the are not "New contact" first load saying new contact then switch over to something else like "Active". Why? 
The same happens with a group status. An active group will first load as inactive and then just as the details screen finally renders, it corrects the status to be Active.

**Comment by zdmc23** [comment]
New Contact is likely the default option and is the initial render, and then the delay on the data update and re-render makes the switch visible to the human eye.  I'll open up a new issue for this.  Thx

**Comment by mikeallbutt** [comment]
@zdmc23  & @raschdiaz I am still getting strange status info in 1.5 using expo with dtdemo and on my other real instance.

Steps to reproduce:
from contact list view, click a contact that is does not have the status set to new contact ie. Hans Test
when the contact loads it will either show the correct status or switch to use "new contact".
click the back arrow to return to the contact list view.
Click to view the same contact of "Hans Test" and the status will be different to last time.
Repeat the steps and the status will interchange from using the status of new contact to whatever it should be.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt can you give me some info to replicate the error and the device where this happens?

- D.T. instance, username, password

- Phone brand, model, android version.

**Comment by zdmc23** [comment]
Unable to reproduce on either iPhone xR or my old Android 7.1 (which runs slow and usually encounters any lag-related issues)

**Comment by mikeallbutt** [comment]
This issue has not been seen for a while now so I think the issue can be closed. (and reopened if needed in the future).
