### ISSUE TITLE
Save and Cancel buttons remain after clicking Save

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#287]
Observed on iOS

Steps to reproduce:
1. Click `Groups` Tab
1. Select `Atlat` Group
1. Navigate to `Members` Tab
1. Add a Member
1. Click `Save`

`Cancel` and `Save` buttons remain.  It's not only the `Members` Screen, it applies to other Screens as well.

![DD6CE414-44BD-45AB-B437-28C8084CD745](https://user-images.githubusercontent.com/191707/77719084-c9e43d80-6fba-11ea-9b6f-65da418d55b0.png)

**Comment by zdmc23** [comment]
![E20C7488-83C0-4A01-B3D1-17A9FA354A39](https://user-images.githubusercontent.com/191707/77719002-a1f4da00-6fba-11ea-9df0-9882ea135aac.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , currently the group its saved automatically when the user selects or remove a member (mentioned in the requirements: https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/57#issuecomment-545963400). We suggest to remove this auto save and only save the data when the user tap the 'Save' button.

**Comment by zdmc23** [comment]
Hi @raschdiaz , Yes, I agree with you.  It's better to have consistency
