### ISSUE TITLE
Apple App Store requirement changes - June 30, 2020

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#289]
- Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen.
- iPhone apps must support all iPhone screens and all iPad apps must support all iPad screens.
- Apps that authenticate or set up user accounts must support Sign in with Apple if required by guideline 4.8 of the App Store Review Guidelines.
Apps in the Kids category must be in full compliance with guideline 1.3 and guideline 5.1.4. of the App Store Review Guidelines.
Apps using HTML 5 must be in full compliance with guideline 4.7 sections 4, 5, and 6 of the App Store Review Guidelines.

Read the App Store Review Guidelines
https://developer.apple.com/app-store/review/guidelines/

**Comment by ahillbilly** [comment]
From developer: 
The only significant change for Disciple.Tools is the requirement to build using XCode (vs Expo Cloud builds that we use now), but we also have a Mac and so we should be fine there.

**Comment by zdmc23** [comment]
Per this Expo documentation: https://docs.expo.io/versions/v37.0.0/guides/splash-screens/

it seems to be saying that we could use XCode to create a Storyboard for our Splash image one-time, then reference it for each build, and so we could conitnue with Expo cloud builds as is.

Eventually, it'd be good to wean the App from Expo dependence and have a Native/RN Hybrid, where we'd make use of some of the Native components (e.g., Native PIN code interface, Face detection, ...)
