### ISSUE TITLE
Spacing - Following visual look of mockup

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-mobile-app#3]
Group details info feels a little small, too close together, not spaced comfortably - what are they using for benchmark / standard? @cairocoder01 - I thought I remembered you having some standards / guidelines on this subject, as far as the size of a hotspot onscreen to accommodate the human fingertip...? :-)

**Comment by yorkaspacher** [comment]
![Screenshot_20190605-112537_Expo](https://user-images.githubusercontent.com/47872338/58969358-931c0d00-8785-11e9-9962-edd8e4f3a143.jpg)

**Comment by cairocoder01** [comment]
Agreed. Tappable elements should be at least 44px, but I prefer 50 or 60.
There should be more between elements as well to prevent mis-taps. You have
to consider that people's fingers are not as accurate or small as a cursor.

**Comment by deividfdez** [comment]
The views are being repaired and updated

**Comment by deividfdez** [comment]
We need a solution on the icon library selections. Please let us know your decision.

**Comment by deividfdez** [comment]
@yorkaspacher  this issue has been solved. Please review

**Comment by zdmc23** [comment]
@yorkaspacher please review when you have the chance, and Close if satisfied. Thx!
