### ISSUE TITLE
Remove bottom tab nav from detail screens

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#30]
MexSurfer:
> Free up the space at the bottom by moving the 3 big icons from the bottom and have them in a slide out menu on the left (like most apps do). These icons won’t get used often enough to warrant such valuable screen real estate. When I am typing, my keyboard also covers these icons and the current Cancel and Save buttons.

The bottom tab nav is only necessary on the root level screens (contact list, group list, settings). It could be removed from detail screens in favor of the back button in the header to go back and simplify navigation. Although slide-out/drawer menus may be common, they are not recommended by most UI/UX people. We will also have a conflict with other contextual actions in our header.

An enhanced bottom nav bar on the list screens could also include an add button for adding either a new contact or group quickly (See [Micro-interactions section](https://medium.com/akveo-engineering/2019-ui-ux-design-trends-you-should-know-268b6bdbc0e3#928d))

**Comment by corsacca** [comment]
@zdmc23 i vote we reopen this issue. At least for discussion.

**Comment by mikeallbutt** [comment]
After using the app, I now use the bottom nav icons all the time - and need them there on all non-editing screens.

**Comment by zdmc23** [comment]
The referenced article (https://medium.com/akveo-engineering/2019-ui-ux-design-trends-you-should-know-268b6bdbc0e3#928d) advances the case for having the Bottom Tab Nav available _more_ often

> Thumb-friendly experience
Last years the smartphones that were released by top mobile companies get large enough screens (5'7-’6'2). This thing makes our fingers and hands practice at stretching. Thumb-oriented design transports all important and frequently used controls to the bottom of the screen. You can reach fundamental parts of your app using only your thumb, without the help of your other hand. But frankly speaking, the moving of this trend started a long time ago with the emergence of bottom navigation menus.

**Comment by mikeallbutt** [comment]
@zdmc23 I think we can close this.
