### ISSUE TITLE
Ability to edit and delete a comment

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#304]
When a comment for a contact or group is added, there is no way to adjust it.

- [ ] edit a contact comment
- [ ] edit a group comment
- [ ] delete a contact comment
- [ ] delete a group comment

**Comment by zdmc23** [comment]
The Website does not permit me to do this, so we may need to discuss this further with D.T Team

**Comment by mikeallbutt** [comment]
> The Website does not permit me to do this, so we may need to discuss this further with D.T Team

@zdmc23 On the website, you can only edit or delete your own comments. If they are yours, you will see and edit or delete link.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 Do you have any suggestion about this feature?

We consider to add the new options (edit, delete) below the comment. When the user tap one of this options. a new dialog appear to edit or delete the comment.

**Comment by ahillbilly** [comment]
@raschdiaz Yes. Mimic the web version, please. 

Edit and Delete links under comment - Clicking one pulls up a modal with: 
1. the old comment in editable form and the option to change and save... or 
2. a confirmation of deletion depending on the link clicked.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ahillbilly , We implemented this feature that enables the user to do the following flows:

- Edit comment (ONLINE / OFFLINE)
- Delete comment (ONLINE / OFFLINE)
- Create, edit and delete comment (ONLINE / OFFLINE)
- Create and delete comment (ONLINE / OFFLINE)
- RTL
- I18N

All this were tested in iOS (11.0.3) and Android (5.1, 8.1.0 and 10).

See the following test flow video: [https://drive.google.com/file/d/1cEnbAS_2HvB08dqCUisgdYo6urzf5pae/view?usp=sharing](https://drive.google.com/file/d/1cEnbAS_2HvB08dqCUisgdYo6urzf5pae/view?usp=sharing)

Additionally, some observations We see in the development:

- When the Web App version UPDATE a comment, the API response its the same (regardless of the updated comment):

![image](https://user-images.githubusercontent.com/16809967/91672328-89519880-eaf3-11ea-9f91-518b999be38f.png)

![image](https://user-images.githubusercontent.com/16809967/91672351-a4240d00-eaf3-11ea-8b5b-8b82f6d20344.png)

As you can see, the API response comments its not the updated comment.

- When a user edit a comment in the Web App setting the comment to a empty string, the interface hide this comment, but the comment it does exist:

![image](https://user-images.githubusercontent.com/16809967/91672421-1b59a100-eaf4-11ea-9501-cd545e08ff99.png)

![image](https://user-images.githubusercontent.com/16809967/91672428-23194580-eaf4-11ea-9cc9-a110842b3111.png)

![image](https://user-images.githubusercontent.com/16809967/91672438-37f5d900-eaf4-11ea-9b65-d17ba6045f95.png)

![image](https://user-images.githubusercontent.com/16809967/91672445-4643f500-eaf4-11ea-96f9-c3b8fc040c3d.png)

But in the mobile app, the comment its visible:

![2020_08_30_07_11_07](https://user-images.githubusercontent.com/16809967/91672507-b94d6b80-eaf4-11ea-87fb-da1e7c3f12ae.jpg)

The Mobile app had to mimic this behavior?

- We add some translations to the Mobile App (english and spanish) and the keys to the others languages, Please add the missing values.

**Comment by corsacca** [comment]
@raschdiaz Thanks for pointing out that the endpoint for updating a comment didn't return the expected result. That is now fixed with: https://github.com/DiscipleTools/disciple-tools-theme/commit/18103e4cfae6dab0fdce8e3234621f08ad65e25b

I don't think it is an issue for the mobile app to still display the empty comment if a user deletes the value.

**Comment by zdmc23** [comment]
Nice work on this @raschdiaz !

**Comment by mikeallbutt** [comment]
@zdmc23 

> Nice work on this @raschdiaz !

Yes I agree! I like too that you can't easily delete a comment - you need to confirm it.

My suggestions are"

- [ ] use the word `Delete` and not `Remove` - to keep consistency across the DT web and app.
- [ ] make the icons smaller (30% less) so they are more the same size as the text (but ensure you can still distinguish what they are).
- [ ] Swap the buttons over - put `Edit` where `Remove` is and `Remove` where `Edit`. Reasoning: scrolling gets done with the touching more on the right side so it will be less chance to accidentally delete a comment.
- [ ] Align the buttons to left side

Edit comment screen:

- [ ] Put the comment to be edited inside a text box field (like what is used for the `initial comment` field when adding a new contact) and remove the separation line at the bottom before the buttons.
- [ ] Align the text to the top of the field (like it is on the delete comment screen).
- [ ] reduce the size of the modal window so that it doesn't get hidden when the keyboard is activated. (On my screen the words/title `Edit Comment are not visible when the keyboard is active)`
- The website uses the word `Update` and not `Save`. I think both are good.

The function to delete a message is needed but will be used very rarely. 90% of the time the user will want to edit and not delete completely a comment. So maybe we should just have the `Edit` button (or even change the `Edit` button to be `Modify`), remove the `Delete` button and then on the Edit screen/modal, add the `Delete` button -so there would be 3 - `Close`, `Delete` and `Save` (or `Update` like the website has).

**Comment by mikeallbutt** [comment]
Not all of the comment is visible when the comment is long. The last part of the comment is shown and not the first part. There should be a scroll bars to indicate not all the comment is visible. 

![edit-long.png](https://user-images.githubusercontent.com/43966676/91792029-30106480-ebda-11ea-9399-27be045f1b14.png)
