### ISSUE TITLE
App crashes in when view some groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#305]
When viewing some groups, the app will stop and leave the app user with a blank white screen. This happens when a the group details tab loads for a group. You see much of the details but then just before the underline of the first tab is assigned, the app screen goes complete white.

**Comment by zdmc23** [comment]
Mike to provide more details

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , can you provide us an example?.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt this error its caused in the method "formatTimestampToDate()" on the GroupDetailView (https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/70a802716cc217d79b88096b8be4f76bd56b6bfc) specifically in this line: `let formattedDate = new Intl.DateTimeFormat(langcode, options).format(timestamp * 1000);`. That seems the class "Intl" does not exist in Android but iOS does. I will investigate how to solve this.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt this error its caused in the method "formatTimestampToDate()" on the GroupDetailView (https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/70a802716cc217d79b88096b8be4f76bd56b6bfc) specifically in this line: `let formattedDate = new Intl.DateTimeFormat(langcode, options).format(timestamp * 1000);`. The "Intl" class is undefined in Android. I will investigate to solve this.
