### ISSUE TITLE
New Contact screen does not include all fields

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#31]
MexSurfer:
> It would be useful to have the option to fill in more/all fields when creating a new user or group, so that the multiplier doesn’t have to create, then go and edit something as simple as the gender, or age of the person. Most of the time, this app will be being used by people doing face to face interaction, so they should be able to fill in this type of information the first time (if they so desire). This might be achieved with a simple “more fields” link at the bottom of the existing form that opens to show more / all of the details fields.

We should allow the entry of all fields that are relevant for a new contact. We can decide on which are the most important ones and keep them visible from the start. Others can be hidden behind a link for "More Fields" or "Advanced", like the Android Contacts app.

![image](https://user-images.githubusercontent.com/44169599/64117923-b3646380-cd96-11e9-958a-b20c0d72aa02.png)

**Comment by mikeallbutt** [comment]
The fields that I would like have offered when creating the contact (that I have to go and edit immediately after creating a contact) are:
gender, age, people groups.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @cairocoder01 . We have the following question: What fields will be available in the "More fields" section?.

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt @cairocoder01 . We have the following question: What fields will be available in the "More fields" section?.

I would like all the editable fields.

- [ ] Gender
- [ ] People group
- [ ] Age
- [ ] Social media

**Comment by cairocoder01** [comment]
I'd also like to see:
* [ ] Contact Status
* [ ] Assigned To
* [ ] Groups

**Comment by jl0325** [comment]
![WhatsApp Image 2019-11-27 at 9 45 13 PM (1)](https://user-images.githubusercontent.com/10079527/69772911-4d059c00-115f-11ea-9e62-62cbe795819e.jpeg)
![WhatsApp Image 2019-11-27 at 9 45 13 PM](https://user-images.githubusercontent.com/10079527/69772912-4d059c00-115f-11ea-8d4d-3902111b025c.jpeg)

**Comment by zdmc23** [comment]
Verified. The scroll bar is showing in the middle of the screen, but I will open a separate issue for that. 

![D8902820-7FC3-436B-BEAE-D2E15491B2C1](https://user-images.githubusercontent.com/191707/69888156-6a9a4900-12b8-11ea-9535-d2c8d97640a5.png)
![280A0340-EC22-4E5E-946F-CC2F92C7181C](https://user-images.githubusercontent.com/191707/69888157-6a9a4900-12b8-11ea-964d-1730f8a24b77.png)

**Comment by mikeallbutt** [comment]
This feature of offering more fields when adding a new record would be useful for groups also.
