### ISSUE TITLE
Locations list missing locations

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#313]
In my installation there is a complete list of locations /wp-admin/admin.php?page=dt_mapping_module&tab=names but not all of them are suggested/showing when I try to assign them.

In this example, Mexico is missing (but it and all the states of Mexico are definitely in the mapping data.)

![Screenshot_20200503-065335](https://user-images.githubusercontent.com/43966676/80913693-28b07b80-8d0c-11ea-948c-5b82e6a0b9d8.png)
![Screenshot_20200503-065940](https://user-images.githubusercontent.com/43966676/80913695-2f3ef300-8d0c-11ea-850c-ef090976383b.png)

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , that seems its a problem with the mobile when it gets the locations list. After add a fix, this is how the flow works:

https://drive.google.com/file/d/1GOI36oX1MduC0zTfs1BuVv7iSESBHzbO/view?usp=sharing

**Comment by zdmc23** [comment]
Hi @raschdiaz , is this reading from local state (after the initial Locations list API call), or is it searching with API endpoint prefix param?  Is it requiring 3 characters before auto-complete?

**Comment by raschdiaz** [comment]
Hi @zdmc23 , when mobile its in ONLINE mode, the mobile search in API to get locations, according to the text entered by the user (At least 1 character). After get this data, the mobile save only non persisted locations, and show results to the user.
