### ISSUE TITLE
Requires update (contact and group)

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#314]
Have the ability to see which contact and group needs an update.

**Comment by corsacca** [comment]
I'm assuming this request is for the list view.
Each row should show a symbol to show if the record is "Update Needed"

**Comment by zdmc23** [comment]
Let's use Icon: "FontAwesome" - "warning" with a red tint color

![warning](https://user-images.githubusercontent.com/191707/89051279-01c11000-d322-11ea-867d-a743b09a1213.png)

**Comment by mikeallbutt** [comment]
> I'm assuming this request is for the list view.
> Each row should show a symbol to show if the record is "Update Needed"

It would be good to have an indication on the record itself too that the record needs to be updated (like what is used in the the theme).

**Comment by mikeallbutt** [comment]
Implemented with #616
