### ISSUE TITLE
Social media links should open the associated app or website

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#320]
Some contacts will have information about who they are on the various social media platforms. If they have recorded on their details screen their Facebook URL, then clicking on that should take the DT app user to the contacts Facebook account/profile page. This should also happen fo the other social media profiles (twitter, instagram, skype).

**Comment by zdmc23** [comment]
We may want to collect a list of social media apps that we want to support.  WhatsApp, Telegram, Signal, Discord, Slack?, Zoom, etc... each will have a unique DeepLink protocol that we will need to map to

**Comment by zdmc23** [comment]
I received a request for "IMO" (https://www.imo.im/) and "KaoKaoTalk" (https://www.kakaocorp.com/service/KakaoTalk?lang=en)

**Comment by zdmc23** [comment]
Kakao and Line for Taiwan

**Comment by ericchen59** [comment]
@corsacca and @ahillbilly - are custom Social media links already built into the DT Theme?

My sense is that deep links provide great value to the multiplier using DT mobile app. What I'm interested to know is if there's already a way DT theme is trying to this as well?

**Comment by ahillbilly** [comment]
@ericchen59, the theme allows saving custom social media links within contact details.  My limited understanding of deep links is that it attempts to open services' mobile apps rather than opening the links within a browser.  I don't know whether this is as great a value on the web app as it will be on mobile, but am open to the conversation.

**Comment by zdmc23** [comment]
@ericchen59 @ahillbilly Deep Links work on the Mobile Website also bc it's more about "handling" them on a mobile device than which client they are clicked from.  A mobile app can specify that it will handle the following type of link: "dt://mylink", and then whether that is a link clicked on from a mobile website or a mobile app, it will prompt the opening of the app that has registered that protocol.  Often times you will have sites that redirect normal links to the mobile specific format to launch an app - for example you could have "https://disciple.tools/mobile" redirect to "dt://login" and that would prompt the D.T app to open if we were handling that link. 

Where a potential change may come in to play is that we may want to detect someone entering a Facebook profile (https://www.facebook.com/zuck) and auto-convert it to be the FB Deep Link format (fb://profile/zuck)

**Comment by ericchen59** [comment]
[dtma-21]

**Comment by zdmc23** [comment]
Anything entered into `Other Social Links` will now be auto-linked and will assume that you're entering the proper deep link formats.  We will work to reference the proper formats in Help Docs, and possibly on edit screen in the app (eventually)

#### WhatsApp
- https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app/?lang=en
- https://wa.me/15551234567  (digits only, not: +1 (555) 123-4567)

#### Messenger
- https://developers.facebook.com/docs/messenger-platform/discovery/m-me-links/
- https://m.me/[username]
