### ISSUE TITLE
Fields hidden on login screen

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#325]
App Version: 1.3

With the keyboard open the fields are hidden by a grey space:
![signal-attachment-2020-05-13-152618](https://user-images.githubusercontent.com/24901539/81826182-69d83500-952f-11ea-8b22-d3073f717644.jpeg)

**Comment by corsacca** [comment]
@zdmc23 this ones gets in the way, but there might be too much in this sprint.

**Comment by zdmc23** [comment]
I think that this is worth fixing since it would possibly confuse and prevent folks from attempting to login. I'll add it. Thx!

**Comment by raschdiaz** [comment]
Hi @zdmc23 the fix was implemented, see this flow example:

https://drive.google.com/file/d/1GQvPNDHYhgnygbxIToLA_GrIXZ_x7rSC/view?usp=sharing

https://drive.google.com/file/d/1GQDy633fuemIisQTX5yfElmjofPmfawn/view?usp=sharing

**Comment by zdmc23** [comment]
Thx @raschdiaz !
