### ISSUE TITLE
Re-enable Language to be set from Settings Screen

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#327]
We previously allowed the Language to be set via the Settings Screen, but then removed it because at that time we were not keeping in-sync with the Website.  Now that we're implementing #326 we can re-enable this.

![language-settings](https://user-images.githubusercontent.com/191707/81840140-8ddb4c80-9516-11ea-8aa5-cec2ab440426.png)

**Comment by raschdiaz** [comment]
Hi @corsacca , which end-point have to use the mobile to update this profile data?.

**Comment by corsacca** [comment]
@raschdiaz i'll get you an endpoint as soon as i can

**Comment by corsacca** [comment]
POST `https://${domain}/wp-json/dt/v1/user/update`
```
{
    'locale': 'fr_FR'
}
```
@raschdiaz here you go

**Comment by raschdiaz** [comment]
Hi @zdmc23 we already apply this modification (see the following example video what show this example flow: Change to Spanish language and after change to Arabic).

[https://drive.google.com/file/d/1IYM0PAHqzh0aBeTH0u49_gDpkDCjZrpL/view?usp=sharing](https://drive.google.com/file/d/1IYM0PAHqzh0aBeTH0u49_gDpkDCjZrpL/view?usp=sharing)

This change involved some changes in the way the language set currently in the app. Some changes were added related to this:

- When the app opens by first time, the app take the current language of device and set it (if the language its not supported, the mobile show English translations).

- In the login, when the change the 'Picker' option, the app change the language according to it (the app will restart if there are any change about RTL/LTR direction, showing a dialog reporting this).

- When the user login in the app, get the current Language profile config (from web) and set it in the app.

- After user log in, go to Settings screen and select a new Language, the app will act as similar way in the login: The mobile update the profile data (end-point) and the app will restart if there are any change about RTL/LTR direction, showing a dialog reporting this. The app always restart in this flow (to avoid some visual errors like texts not translated).

- Offline mode work similar way: The user selects a new Language, the app store the request (and acts like request was succesfully), the app show the dialog and restart. When the user go to ONLINE mode, the app send the stored request and update the website config.

Additional to this, several translation were added/changed.
