### ISSUE TITLE
Warn user about App reboot when switching between LTR/RTL languages

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#328]
Currently, the App reboots when toggling between LTR/RTL (and vice versa) languages.  Rather than simply reload the App (seems kind of like a crash), we want to have an "OK" dialog box to warn the user that the reload is about to occur and "why" (because we're switching from LTR->RTL or RTL->LTR and we need to reload the components)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , We implemented this feature, see the test flow in the following video:

https://drive.google.com/file/d/1Gzw5dvEAfaWxCP0pIvswRx2F_H-Dc4aA/view?usp=sharing

Additionally translations were added.

**Comment by zdmc23** [comment]
Hi @raschdiaz , please darken the text color and rename button to be "ok" (in English).  Otherwise, it looks good!  Thx

**Comment by raschdiaz** [comment]
Hi @zdmc23 , We added the change:

https://drive.google.com/file/d/1I9nOyoforEh6C9gFrYg11zUNY3TEslKk/view?usp=sharing

**Comment by mikeallbutt** [comment]
@zdmc23 what happens if someone doesn't want to accept the change. There is no cancel or reject change option. I tied to a few things, but all I could do is accept of force close the app. I think it needs an option to reject and not just accept - or a way that gives the app user a way to decline the change.

**Comment by zdmc23** [comment]
@mikeallbutt go ahead an open a new issue to include a `Cancel` button.  I don't think that it's terribly urgent as it doesn't "cost" that much to switch back if a mistake is made, but we can eventually include it
