### ISSUE TITLE
Comments and Activities not being displayed in forced offline mode

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#329]
Observed on Android and iOS

Steps to reproduce:
1. Select a Contact
1. Tab to `Comments and Activities`
1. Observe available data
1. Go OFFLINE (either via Airplane Mode without WiFi or via `Settings` Tab)
1. Refresh the `Comments and Activities`
1. Observe Placeholder about being offline

We should display the Comments and Activities data if we have it cached locally

![9870B843-FAA5-4EB7-958A-2697E3D047D5](https://user-images.githubusercontent.com/191707/81886883-d53ff800-956b-11ea-86c7-d038674ca828.png)

**Comment by zdmc23** [comment]
This continues to be an issue. Same steps to reproduce as above

![D164ECB0-F924-4636-967B-14008B22B9BE](https://user-images.githubusercontent.com/191707/84456689-99618680-ac2e-11ea-98c3-ee1a2b9416b0.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 We can use some property in the Redux Store to persist this collection BUT will only save the last comments / activities loaded. What do yo think about this?.

**Comment by zdmc23** [comment]
Hi @raschdiaz , I don't understand why there is an issue.  If we're online at some point, and we load the data to the local device (and persist it via AsyncStorage), then it should remain available when we go offline.  Why can we only have the "last" comments / activities?  What happens to the previously available data?

**Comment by raschdiaz** [comment]
Hi @zdmc23 , to achieve that, we have to do some validations (in the reducers), and some Redux Store data restructure to detect persisted data and show it to the user (like detail view/ view lists), not only persist it in the Redux.

Currently, the device get the comments/activities of a specific contact/group ONLY when the user go to their DetailView. This info will be saved in one specific property in the store/reducer:

![image](https://user-images.githubusercontent.com/16809967/90300080-7b96e480-de5e-11ea-8f62-7eaa8d422dfd.png)

When the user go to another contact detail, this data its replaced with their comments/activities.

When I talk about "last comments/activities" , there are the latest comments obtained from the contact (or group).

**Comment by raschdiaz** [comment]
Hi @zdmc23 , We can implement this improvement, and do some test flows like:

- Get comments/activities data
- Add comments
- Do pagination

See this test flow: [https://drive.google.com/file/d/1bkOSzDhkAVvJTfzB0JnV9e0EAmCCPwVo/view?usp=sharing](https://drive.google.com/file/d/1bkOSzDhkAVvJTfzB0JnV9e0EAmCCPwVo/view?usp=sharing)

Additionaly, We fix some error related to the 'assigned_to' field when user enter to DetailView.

**Comment by zdmc23** [comment]
> Hi @zdmc23 , We can implement this improvement, and do some test flows like:
> 
>     * Get comments/activities data
> 
>     * Add comments
> 
>     * Do pagination
> 
> 
> See this test flow: https://drive.google.com/file/d/1bkOSzDhkAVvJTfzB0JnV9e0EAmCCPwVo/view?usp=sharing
> 
> Additionaly, We fix some error related to the 'assigned_to' field when user enter to DetailView.

@raschdiaz , nice job!  That flow looks like what we want.  I'll test more tomorrow, but it looks good per the video.  Thx!!
