### ISSUE TITLE
Add @mention functionality for collaboration

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#332]
Mimic web app functionality of @mentioning within comments to trigger notification to other users.

**Comment by ahillbilly** [comment]
MVP of this feature could be simpler than full implementation with a button to pick from a list and attach afterward.
![atmention](https://user-images.githubusercontent.com/25323324/83036506-96fa0c80-a032-11ea-9194-3ad15f5f176a.jpg)

**Comment by raschdiaz** [comment]
Hi @ahillbilly @zdmc23 , We implement this feature like web behavior, see the following video: [https://drive.google.com/file/d/1LLiJJJVyBFJ_WENSP5u1Cnb6ev_hFVdJ/view?usp=drivesdk](https://drive.google.com/file/d/1LLiJJJVyBFJ_WENSP5u1Cnb6ev_hFVdJ/view?usp=drivesdk)
