### ISSUE TITLE
Switching between instances causes data problems

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#333]
Per @mikeallbutt 

> There is definitely issues when signing in to a different instance. I get all the old/previous instance data - even are pulling down to refresh, it all stays there. I also couldn’t pull down to refresh the contact list screen.

>https://drive.google.com/open?id=1ZyyVsr8zXFCQqxcgOZxMcaXEVYJ7A3oX that folder has 2 videos that show the issues with the strange status for contacts and groups.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt I have added the following modification to resolve this:

- When the user logout, the app will delete all instance related data (like contacts, groups .etc).

See the following video: [https://drive.google.com/file/d/1Ig6f3iR8ez3KpR_OR_CEGfkkKsAILOOy/view?usp=sharing](https://drive.google.com/file/d/1Ig6f3iR8ez3KpR_OR_CEGfkkKsAILOOy/view?usp=sharing)
