### ISSUE TITLE
App crashes when marking meeting attendance using FAB

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#334]
Observed on Android 

Steps to reproduce per @mikeallbutt 

1. View Contact "Karla Cruz"
1. Click FAB button and mark meeting attendance

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , which Android version you see this crash?. I have tested this in Android 8.1 and 9 and works fine. Can you provide us some test video flow?.

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt , which Android version you see this crash?. I have tested this in Android 8.1 and 9 and works fine. Can you provide us some test video flow?.

Yes it didn't crash now. So not sure what has changed, but happy that this bug is not showing for now.

**Comment by zdmc23** [comment]
Unable to reproduce
