### ISSUE TITLE
User not showing in Sub-Assign List

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#338]
Per Field Partner:

> I was trying to sub-assign contact [Jane Doe] to user [Timmy D. Testerton] ([Jane Doe] was already sub-assigned to user [Sally Sue] but I wanted to add [Timmy D. Testerton]), but when I looked at sub-assign, for one it didn't show his sub-assignment to user [Sally Sue], and for two when I tried to search for [Timmy D. Testerton], it only showed me contacts (whose ID numbers begin with "D"). I couldn't find any users.

**Comment by raschdiaz** [comment]
Hi @zdmc23 can you give me more info about this flow?

- Which W.P. instance are using? Can you give me credentials?
- This flow was made in ONLINE or OFFLINE mode?

**Comment by zdmc23** [comment]
Hi @raschdiaz , I'll try to reproduce it in one of our demo environments.  Unfortunately, I can't share these particular credentials. Thx

**Comment by corsacca** [comment]
Is this the same on the desktop version?

**Comment by mikeallbutt** [comment]
I suspect this might be connected to the issue #359

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt , the Sub-assign field use the list retrieved for this end-point 'wp-json/dt-posts/v2/contacts?offset=${offset}&limit=${limit}&sort=${sort}' (list used for the contactsView).

We tried to replicate the problem again without success.

It seems weird this happen, because the mobile app get all the contacts of the D.T instance.

Its possible that the user record the screen of their cell phone to show how the issue happen?

**Comment by zdmc23** [comment]
@mikeallbutt have you been able to retrieve the expected Contacts via the Website?  Per @corsacca 's comment above, I suspect that it may be a situation where some of the Contacts may not be visible to your User?

cc: @raschdiaz

**Comment by zdmc23** [comment]
I will mark this as `unable to reproduce` bc I seem to have all of the Users/Contacts that I have "interacted with" available to me on the mobile app.  I'll bring this up for discussion on the 7/29 call.

**Comment by mikeallbutt** [comment]
As can be seen here, there should be 3 sub-assigned contacts listed in the app.

![Screenshot 2020-08-03 22 32 25](https://user-images.githubusercontent.com/43966676/89250092-93a67280-d5d9-11ea-8754-799cb6627ec1.png)

![Screenshot_20200803-223227](https://user-images.githubusercontent.com/43966676/89250072-82f5fc80-d5d9-11ea-80ec-94d49225d82b.png)

**Comment by zdmc23** [comment]
Hi @mikeallbutt , it seems that it's only certain accounts that aren't showing, and I think that may have something to do with how D.T handles Sub-Assign and its concept of "interacted with".  Some Contacts can be added via the Website and then show properly in the App (eg, "Hans C. Test" and "Mike Albutt"), but others cannot.

cc: @ahillbilly @corsacca Would either of you be able to further explain the concept of "interacted with" as it relates to Sub-Assign? (I've also observed this strange occurrence where most auto-complete fields will display 30 results if more than 30+ exist, but Sub-Assign only shows specifically *27* for some reason).  I'm not sure that I fully understand the logic around Sub-Assignment, and there isn't much written about it in the docs: 
- https://disciple-tools.readthedocs.io/en/latest/Disciple_Tools_Theme/getting_started/contacts.html#status-and-assignment-tile
- https://disciple-tools.readthedocs.io/en/latest/Disciple_Tools_Theme/archive/user_about.html?highlight=sub-assign#assigning-sub-assigning-following-and-sharing

**Comment by corsacca** [comment]
The API request for the contact returns something like
```
{
  ...
  "subassigned" : [
    {
      "post_title": "Bob"
      "ID": 300
    },
    {
      "post_title": "Zoro"
      "ID": 301
    },
    {
      "post_title": "Random Contact"
      "ID": 302
    },
   ...
  ]
}
```

The signed in user has permission to subassign the "Bob" user, but not the "Zoro" user.
The signed in user may or may not have access to "Random Contact"
"Bob" and "Zoro" and "Random Contact" should still be listed in the typeahead.

When using the typeahead search it will only list out the users and contacts the user has access to.
A user has interacted with another user if they are both "shared" on a contact. Sharing happens automatically you you are assigned, subassigned or @mentioned on a contact.

**Comment by zdmc23** [comment]
Thx @corsacca !

Hi @raschdiaz , I have found a new example in "dtappdemo" instance for Contact (https://dtappdemo.wpengine.com/contacts/1863/):

```
...
    "subassigned": [
        {
            "ID": 63,
            "post_type": "contacts",
            "post_date_gmt": "2018-05-29 14:34:10",
            "post_date": "2018-05-29 14:34:10",
            "post_title": "Christopher Berganza (multiplier)",
            "permalink": "https://dtappdemo.wpengine.com/contacts/63/"
        },
        {
            "ID": 13,
            "post_type": "contacts",
            "post_date_gmt": "2018-05-29 12:30:34",
            "post_date": "2018-05-29 12:30:34",
            "post_title": "Damián Abellán (Dispatcher)",
            "permalink": "https://dtappdemo.wpengine.com/contacts/13/"
        },
        {
            "ID": 1774,
            "post_type": "contacts",
            "post_date_gmt": "2020-03-09 19:44:47",
            "post_date": "2020-03-09 19:44:47",
            "post_title": "Hans 1446",
            "permalink": "https://dtappdemo.wpengine.com/contacts/1774/"
        }
    ],
...
```

The 2 Users which are not showing ARE present in the response from: `/dt/v1/users/get_users?get_all=1`

![subassign](https://user-images.githubusercontent.com/191707/89294297-51a71c00-d62d-11ea-9585-01d47f6059dc.png)

**Comment by zdmc23** [comment]
Added `SHOWSTOPPER` label bc this issue is causing `Sub-Assign` and `Connection/Relation` data to be lost upon `Edit/Save`

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt @corsacca We think this can be solved implementing a behavior like 'sources' fields: When a contact has a 'source' that not exist in the current 'sources' list, the mobile app add this non existing 'sources' to the list to can be shown in the detail / edit mode. But, when the user remove this value, it will be remove it from the 'sources' list.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt @corsacca We implemented the behavior similar to 'sources' field:

[https://drive.google.com/file/d/1U4-nigK3dlGSr8CiGPUPSyT9LeilOdTz/view?usp=sharing](https://drive.google.com/file/d/1U4-nigK3dlGSr8CiGPUPSyT9LeilOdTz/view?usp=sharing)
