### ISSUE TITLE
Crash with demo contact 155

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#339]
I get crashes for https://dtdemo.disciple.tools/contacts/155/ which is Rashid Contact449 when I try to see the contact details screen.

**Comment by ahillbilly** [comment]
I get this as well on the same contact, but opened other contacts without issue.  The screen just goes white and hangs with no ability to close out the app or go back.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ahillbilly , The 'Rashid Contact449' has asigned a source called 'partner', which does not exist in the 'wp-json/dt-posts/v2/contacts/settings' end-point. 

![Captura4](https://user-images.githubusercontent.com/16809967/84517510-0871c600-ac95-11ea-8c49-0616be113e04.PNG)

The current source's values supported are: personal, web, phone, facebook, twitter, linkedin, referral, advertisement and transfer.

**Comment by corsacca** [comment]
@raschdiaz if the value is not found for a field then the UI should show the key instead.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ahillbilly @corsacca , we implemented a workaround (as suggested by @corsacca ) , adding the non existing source to the option list:

[https://drive.google.com/file/d/1MGBNG8MGwBPnMjRyhub44qfsOtCAL9ut/view?usp=sharing](https://drive.google.com/file/d/1MGBNG8MGwBPnMjRyhub44qfsOtCAL9ut/view?usp=sharing)

**Comment by corsacca** [comment]
@raschdiaz Undefined fields/options do not need to be selectable. Since it is not a defined option we don't want more contacts getting that option.
The details section should display the key as a fallback if the the option or option label is not defined.

**Comment by raschdiaz** [comment]
Hi @corsacca , ok. Then, this options only appear in the 'Detail' mode, not 'Edit' mode.

**Comment by corsacca** [comment]
@raschdiaz It should mimic the website.

**Comment by corsacca** [comment]
It should show up in Detail mode and in the input box in edit mode, but not in the edit mode dropdown options.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ahillbilly @corsacca We add the indicated changes, see this video: [https://drive.google.com/file/d/1NHt4BuJ1Yekf2FtS0fS490TyJZ1qEZ8r/view?usp=sharing](https://drive.google.com/file/d/1NHt4BuJ1Yekf2FtS0fS490TyJZ1qEZ8r/view?usp=sharing)

**Comment by corsacca** [comment]
Awesome!

**Comment by mikeallbutt** [comment]
I have confirmed that this issue is fixed.
