### ISSUE TITLE
Removing last item of a multiple entry text field (like phone, email, etc) displays "undefined" on detail screen

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#34]
![image](https://user-images.githubusercontent.com/44169599/64118046-12c27380-cd97-11e9-8243-251b81be2020.png)

**Comment by mikeallbutt** [comment]
I think this issues has been fixed.

**Comment by cairocoder01** [comment]
Confirmed fixed
