### ISSUE TITLE
Missing translation should default to English

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#342]
![translation](https://user-images.githubusercontent.com/24901539/84269783-9b89ef00-ab21-11ea-97db-75545c8861c6.jpeg)

**Comment by raschdiaz** [comment]
Hi @corsacca , now, the app will set English as default language:

[https://drive.google.com/file/d/1Jp6QisVbKna6Lg7xkONQYPZcx6-8T2NL/view?usp=sharing](https://drive.google.com/file/d/1Jp6QisVbKna6Lg7xkONQYPZcx6-8T2NL/view?usp=sharing)

In the video, the mobile Language is set to Deutch, after open app. The app set English language as default.
