### ISSUE TITLE
Pin workflow. Ability to log in with password and reset pin

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#343]
I set a pin and chose the remember my password setting. I closed the app. 
I then promptly forgot my pin.
When i open the app i am asked for the pin. I can't close the dialog box to enter my password instead.

---
Let the user close the "Enter PIN" dialog box so then can log in with a password.
![reset_pin](https://user-images.githubusercontent.com/24901539/84271076-87df8800-ab23-11ea-94cb-551d82af789a.jpeg)

**Comment by raschdiaz** [comment]
Hi @corsacca , We add a fix when the user close the PIN dialog and log in the app 'manually':

[https://drive.google.com/file/d/1K0Ds2Gn5B_PBJlajWY9F8bTCIyV6P4wR/view?usp=sharing](https://drive.google.com/file/d/1K0Ds2Gn5B_PBJlajWY9F8bTCIyV6P4wR/view?usp=sharing)

**Comment by zdmc23** [comment]
Confirmed

https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/344/commits/b6726d3624f327f87bf7be7d2b027853ddae5581

**Comment by corsacca** [comment]
You guys rook! :)
