### ISSUE TITLE
Comment time stamp not using instance timezone

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#347]
When the timezone of the DT instance is set to UTC+0 then a new comment for a contact or group are correctly logged at the right time. But if the WP timezone is set to something else other than UTC+0 then they are assigned as being logged at an incorrect time.

**Comment by mikeallbutt** [comment]
To facilitate the testing of this, I have adjusted the WP general timezone for the instance https://dtdemo.disciple.tools/ to be Tokyo time.

**Comment by raschdiaz** [comment]
Hi @corsacca, the 'wp-json/dt-posts/v2/**{contacts/groups}**/**{id}**/comments' and 'wp-json/dt-posts/v2/**{contacts/groups}**/**{id}**/activity' end-points return dates accordly D.T. instance timezone?

To OFFLINE MODE we need to know the instance timezone to show the dates accordly. Can you add this in the 'wp-json/jwt-auth/v1/token' end-point?

**Comment by corsacca** [comment]
@raschdiaz 
The activity `hist_time` and the comment `comment_date_gmt` are both always gmt(+0)

**Comment by raschdiaz** [comment]
Hi  @mikeallbutt @corsacca . As you mentioned, We apply this modification to see the correct dates:

![image](https://user-images.githubusercontent.com/16809967/88597001-ead1a380-d02b-11ea-8a67-614532494881.png)

![image](https://user-images.githubusercontent.com/16809967/88597084-15236100-d02c-11ea-95e0-f4b5ccf1e4e5.png)

**Comment by mikeallbutt** [comment]
Still not quite right. I logged a comment in 'dtdemo' for Jessica Blue. The app says it was logged at 7:52pm and not 10:52am, while it is correctly time stamped on the website.

**Comment by zdmc23** [comment]
@mikeallbutt would you please try with the mobile website also. It’s possible that it’s related to a time setting on your phone vs your desktop

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 I do a quick test to verify the @mikeallbutt report in Slack. I do the test using the test using the following settings:

- WP Instance: dtdemo.disciple.tools
- Username: someone

I logged and added a new comment to the contact 'Mike Allbutt' (in the comment is write the exact time):
![2020_07_29_02_13_30](https://user-images.githubusercontent.com/16809967/88843560-f4334b00-d1a6-11ea-96ba-7521f5ea6de6.jpg)

As you can see, the comment timestamp seems correct. And the website:
![image](https://user-images.githubusercontent.com/16809967/88843673-217ff900-d1a7-11ea-8337-fc4e6ac31d8a.png)

Show the same time.

When the mobile app get the comments data, the JSON looks like this:
![JSON](https://user-images.githubusercontent.com/16809967/88843758-407e8b00-d1a7-11ea-92c5-2746b95b4e6e.PNG)

The date show in GMT +00:00 (like @corsacca mentioned).

**Comment by zdmc23** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/5f75f6dfadcd7f0680894efa6196ea9ee18f0ada
