### ISSUE TITLE
Login button needs pressing twice

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#350]
When I go to sign in, I enter the URL in the first field, then move to the username field, enter my username, then move to the password field, enter the password (normally by pasting it after it had been copied to the phones memory from a password program), then press "Log In". The digital keyboard is open so when I press the "Log In" button, it only closes the keyboard, forcing me to press the button again. Pressing the login button should activate the login sequence.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 see the following video showing the implementation: [https://drive.google.com/file/d/1hmWUlbootrUK3Bm-jbe0lDSPxfeJPnHs/view?usp=sharing](https://drive.google.com/file/d/1hmWUlbootrUK3Bm-jbe0lDSPxfeJPnHs/view?usp=sharing)
