### ISSUE TITLE
Set PIN code confirmation

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#357]
Require that the app user needs to type in the PIN code twice when setting their pin code, to avoid them accidentally setting something they didn't mean to set.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 see the following video showing the implementation:

[https://drive.google.com/file/d/1jdzDlhfB319j4gbYtPv_EOe2Fb9hf6cl/view?usp=sharing](https://drive.google.com/file/d/1jdzDlhfB319j4gbYtPv_EOe2Fb9hf6cl/view?usp=sharing)
