### ISSUE TITLE
Missing contacts in list view when using the search field

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#359]
After working in the app and making some edits etc, when I return to the contacts list view and use the search box to refine the list again for a new contact, not all the contacts that should be shown are offered in the list.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , this is happening with the new contact filter implemented? [https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/378](https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/378)

Can you show me what D.T. instance are you using?. 

Can you add some screenshots?

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt , this is happening with the new contact filter implemented? #378

It was happening before and after the new filter was done.

> 
> Can you show me what D.T. instance are you using?

My Oikos and the dtdemo instances.

> 
> Can you add some screenshots?

Yes. The first set shows there should be 3 but only 2 show. The next set for pause shows none when there should be 1.

![Screenshot_20200714-200610](https://user-images.githubusercontent.com/43966676/87812055-3cf11880-c825-11ea-90b3-cfbb03182d8c.png)
![Screenshot_20200714-200646](https://user-images.githubusercontent.com/43966676/87812062-3f537280-c825-11ea-896b-a81f5da9555a.png)
![Screenshot_20200714-200709](https://user-images.githubusercontent.com/43966676/87812063-3fec0900-c825-11ea-80ea-f060ad3781be.png)
![Screenshot_20200714-200930](https://user-images.githubusercontent.com/43966676/87812066-40849f80-c825-11ea-809d-79fba9cb8f3a.png)

**Comment by raschdiaz** [comment]
Hi @corsacca , I have a doubt about how filters work in the web app. When I do the following filter in the dtappdemo.wpengine.com instance, look like this:

![image](https://user-images.githubusercontent.com/16809967/88411018-d9269c80-cd9c-11ea-8447-31b4ee4701b0.png)

But in the mobile app looks like this:

![Screenshot_2020-07-24-11-01-04-358_host exp exponent](https://user-images.githubusercontent.com/16809967/88411162-0ffcb280-cd9d-11ea-9ab3-263e84a355b5.jpg)

Following the query that the mobile app use:

![image](https://user-images.githubusercontent.com/16809967/88411258-3fabba80-cd9d-11ea-96c7-495027de89ef.png)

The mobile app result seems correct. Now, when i search the contact does not appear (Ahmed Salem) in the web app, It shows me the following:

![image](https://user-images.githubusercontent.com/16809967/88411447-90231800-cd9d-11ea-9056-c8350621e085.png)

But in the contact JSON structure We don't see any reference to 'Closed Contact':

> {
            "ID": "53",
            "post_title": "Ahmed Salem",
            "post_type": "contacts",
            "post_date": "2018-05-29 14:03:24",
            "relation": [
                {
                    "ID": 118,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-02-26 18:43:32",
                    "post_date": "2019-02-26 18:43:32",
                    "post_title": "joswin",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/118/"
                },
                {
                    "ID": 117,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-31 10:28:20",
                    "post_date": "2019-01-31 10:28:20",
                    "post_title": "Jon W",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/117/"
                }
            ],
            "coached_by": [],
            "coaching": [],
            "baptized_by": [
                {
                    "ID": 117,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-31 10:28:20",
                    "post_date": "2019-01-31 10:28:20",
                    "post_title": "Jon W",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/117/"
                },
                {
                    "ID": 116,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-30 21:43:40",
                    "post_date": "2019-01-30 21:43:40",
                    "post_title": "zdmc23",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/116/"
                },
                {
                    "ID": 8,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-30 15:50:57",
                    "post_date": "2019-01-30 15:50:57",
                    "post_title": "york",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/8/"
                }
            ],
            "baptized": [
                {
                    "ID": 117,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-31 10:28:20",
                    "post_date": "2019-01-31 10:28:20",
                    "post_title": "Jon W",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/117/"
                },
                {
                    "ID": 8,
                    "post_type": "contacts",
                    "post_date_gmt": "2019-01-30 15:50:57",
                    "post_date": "2019-01-30 15:50:57",
                    "post_title": "york",
                    "permalink": "https://dtappdemo.wpengine.com/contacts/8/"
                }
            ],
            "people_groups": [
                {
                    "ID": 33,
                    "post_type": "peoplegroups",
                    "post_date_gmt": "2018-05-29 13:13:49",
                    "post_date": "2018-05-29 13:13:49",
                    "post_title": "Arab, Tunisian",
                    "permalink": "https://dtappdemo.wpengine.com/peoplegroups/arab-tunisian/",
                    "label": "Arab, Tunisian"
                }
            ],
            "groups": [],
            "subassigned": [],
            "seeker_path": {
                "key": "met",
                "label": "First Meeting Complete"
            },
            "last_modified": "1569358078",
            "type": {
                "key": "media",
                "label": "Media"
            },
            "overall_status": {
                "key": "active",
                "label": "Active"
            },
            "sources": [
                "facebook"
            ],
            "age": {
                "key": "<26",
                "label": "18-25 years old"
            },
            "gender": {
                "key": "male",
                "label": "Male"
            },
            "accepted": true,
            "quick_button_no_answer": "1",
            "quick_button_contact_established": "1",
            "quick_button_meeting_scheduled": "1",
            "quick_button_meeting_complete": "1",
            "requires_update": true,
            "baptism_date": {
                "timestamp": false,
                "formatted": false
            },
            "duplicate_data": {
                "contact_phone": [
                    41,
                    51,
                    55,
                    57,
                    58,
                    59,
                    60,
                    61,
                    66,
                    67,
                    68,
                    69,
                    71,
                    72,
                    73,
                    77,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    108,
                    110
                ]
            },
            "milestones": [
                "milestone_baptized",
                "milestone_baptizing"
            ],
            "baptism_generation": "47",
            "contact_phone": [
                {
                    "verified": false,
                    "value": "555-5555",
                    "key": "contact_phone_320"
                }
            ],
            "contact_email": [
                {
                    "verified": false,
                    "value": "",
                    "key": "contact_email_22b"
                }
            ],
            "permalink": "https://dtappdemo.wpengine.com/contacts/53"
        },

How the web app detect this?

**Comment by zdmc23** [comment]
Thank you for this thorough investigation @raschdiaz !  It would seem that #338 may be experiencing a similar issue

**Comment by zdmc23** [comment]
Hi @corsacca and @ahillbilly , should we open a new issue in the Theme repo to get the `Closed Contact` property included in the API response?

**Comment by corsacca** [comment]
@raschdiaz On the web, the "My contacts" tab only returns the contacts that are assigned or sub-assigned to you.
Ahmed is not assigned to you (somehow not assigned to anyone) so he will not show up from the "my contacts" tab.

The "Closed Contacts" toggle when off just adds a `{ overall_status: [ '-closed'] }` to the query which filters out closed contacts.

**Comment by corsacca** [comment]
@raschdiaz can you copy here the exact query you are using that also includes the "Ahmed" result?

**Comment by raschdiaz** [comment]
Hi @corsacca to clarify, the mobile app filters the list locally (to works in ONLINE/OFFLINE) mode. We try to replicate the same behavior like web app. We have a function to filter the contact list according to the filters.

**Comment by corsacca** [comment]
@raschdiaz  If you log in a as a multiplier the 'All Contacts" tab is not displayed.
All contacts > All would just show all the contacts you have access to (or have stored locally) minus the closed ones.
My Contacts > All looks more like you JSON. Contacts i am assigned to or ubassigned, but **not** closed contacts.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @corsacca @zdmc23 We add some improvements to the filter behavior. Now the filter will show the same results as web app.

![1-web](https://user-images.githubusercontent.com/16809967/89342075-e0d12580-d667-11ea-8b9c-f0fae785fbb8.PNG)

![1-mobile](https://user-images.githubusercontent.com/16809967/89342082-e29ae900-d667-11ea-9573-b3f7b97c7c03.png)

We notice some filters like this:

{
            "ID": "my_all",
            "tab": "assigned_to_me",
            "name": "All",
            "query": {
                "assigned_to": [
                    "me"
                ],
                **"subassigned": [
                    "me"
                ],**
                "combine": [
                    "subassigned"
                ],
                "overall_status": [
                    "-closed"
                ],
                "sort": "overall_status"
            },
            "count": 16
        },

Use the 'subassigned' with value '{$userId}', but in the contacts list, this value does nos appear (We remove the other properties for this example):

{
            "ID": "1681",
            "post_title": "Zac &amp; Jerry հễŀլⱺ ẘǒ𝘳ιᏧ",
            "subassigned": []
}

As you can see , the $userId does not appear in the 'subassigned' collection. Then, We remove this value from the filters like this:

// Remove subassigned query because contacts does not have this value
if(Object.prototype.hasOwnProperty.call(queryFilterTwo, "subassigned")) {
    delete queryFilterTwo.subassigned;
}

With this modification, the user can see their filtered related contacts like website:

![2-web](https://user-images.githubusercontent.com/16809967/89342663-b9c72380-d668-11ea-8f99-4574cfd05c3f.PNG)

![2-mobile](https://user-images.githubusercontent.com/16809967/89342649-b6339c80-d668-11ea-8c06-bf6e117bd767.png)
