### ISSUE TITLE
Tapping Cancel in edit mode still updates contact info

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#36]
MexSurfer:
> I clicked save when editing and stayed on the same screen. So I then clicked cancel and that returned me to the details screen, only to see  that the edits had actually been saved.

It might be that the changes are not saved via the API, but the local state has been updated accidentally and gives the impression that the change was saved. Either way, "Cancel" should cancel the changes from being applied.

**Comment by deividfdez** [comment]
@cairocoder01 this issue has been solved, can you please check?

**Comment by cairocoder01** [comment]
Works as expected. Thanks @deividfdez
