### ISSUE TITLE
View tags and Filter by tags for [contact, group] records

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#360]
DT has a tagging feature. A contact can be tagged and those tags used to filter a list. Things that would be good to be able to do are:

- [ ] Create a tag 
- [ ]  apply a tag to a contact
- [ ]  remove a tag to a contact
- [ ]  tap on a tag to filter the contact list

**Comment by corsacca** [comment]
GET /wp-json/dt-posts/v2/{post-type}/multi-select-values
get the possible options for adding a tag to the record

**Comment by mikeallbutt** [comment]
The tagging field should be added after the sources field on the details screen of a contact and group.

It should look and function like the connections field for a contact in edit mode (with the light grey background) .

**Comment by ahillbilly** [comment]
This actually might fit inline with issue #353 where additional and custom tiles are shown as additional tabs and fields on those tiles appear within the tab.  The "Tags" field is on the "Other" Tile, which was not added initially.  

As I perceive it...  Creating a new tag and Filtering by a tag will be separate issues from applying and displaying the tags that already exist server side.

**Comment by mikeallbutt** [comment]
@ahillbilly yes the tags are in the other tile in DT but it would be better to have the tags just be at the bottom of the details screen.
It would be good if was possible to move fields into whatever tile the admin for the instance prefers.

**Comment by ahillbilly** [comment]
I understand the desire for the tags to be in a different tile... that’s a theme issue and I think is being worked on... but as far as the mobile is concerned, it should mimic in a consistently modular way what is going on within the theme... so for now it would see from the theme the other tile and the tags within it.

**Comment by ericchen59** [comment]
User Story: As a DT mobile app user, I want to view tags and filter by tags for [contact, group] records, so that see the tags that any [contact, group] and enter a filter view from that tag.

Acceptance Criteria:
- [ ] when a user goes to the "Other" page for a [contact, group], they can see the same tags as seen on the DT website for that given [contact, group]
- [ ] when a user taps on a tag, the view will change to a filtered search of all contacts with the same tag that was tapped

**Comment by raschdiaz** [comment]
Hi @corsacca can you confirm us the prop 'tag' its retrieved on the contacts **(https://${domain}/wp-json/dt-posts/v2/contacts?offset=${offset}&limit=${limit}&sort=${sort})** and groups **(https://${domain}/wp-json/dt-posts/v2/groups?offset=${offset}&limit=${limit}&sort=${sort})** end-points?

**Comment by corsacca** [comment]
@raschdiaz In the `tags` field.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @corsacca @ahillbilly @ericchen59 see the following video with the implementation:

[https://drive.google.com/file/d/1mhKtZ6E-JTRil1JUvlxlrKdS4R6uwxfk/view?usp=sharing](https://drive.google.com/file/d/1mhKtZ6E-JTRil1JUvlxlrKdS4R6uwxfk/view?usp=sharing)

Additionally, we found and resolve several bugs in the app.

**Comment by mikeallbutt** [comment]
@raschdiaz i have been trying for hours to watch the video but it doesn't load. Anyone else getting this issue?
@zdmc23

**Comment by ericchen59** [comment]
![image](https://user-images.githubusercontent.com/26180602/101233283-b038e100-3685-11eb-8f0b-44d60b999e2c.png)

Also didn't load for me. Try to reload the video @raschdiaz ?

**Comment by raschdiaz** [comment]
I dont know what is happening with google drive... Can you try dowloading the video?.
