### ISSUE TITLE
Remove extra spacing in list views

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#361]
There is currently lots of extra spacing when in list view for contacts and groups, and that prevents the viewing of more items in the list, and forces the app user to scroll a lot. 
On a standard phone, less than 5 items are shown. 
The extra white space should be removed to show 10 items.

**Comment by zdmc23** [comment]
Taking this up per @mikeallbutt ‘s request
