### ISSUE TITLE
Show bottom navigation icons in comments and activity screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#362]
When in viewing mode, display the bottom 4 icons (Contacts, Groups, Notifications, Settings) when in "comments and activity" screen for contacts and groups.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 We add this modification: 

[https://drive.google.com/file/d/1UrijvlfTn8hH-8Au--bpo3mQFJgsAfyQ/view?usp=sharing](https://drive.google.com/file/d/1UrijvlfTn8hH-8Au--bpo3mQFJgsAfyQ/view?usp=sharing)

**Comment by mikeallbutt** [comment]
Thanks for resolving this issue. Should we have the FAB available on the comments and activity screens also?
