### ISSUE TITLE
Access to locations other than the focused locations

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#365]
When a DT instance has a location focus set to something other than world, then it is not possible to assign a location to a contact or group outside the set area of focus. There needs to be a way like the website has that allows the app user to request a location that is not in the set area of focus.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , We add a new P.R. [https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/383](https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/383) with a end-point URI modfication, to get all locations when the user type in the 'Locations' field. Can you confirm this solves the problem?.

**Comment by zdmc23** [comment]
Hi @raschdiaz , before I merge this PR, I'd like get input from @corsacca and @ahillbilly .  "Focus" Locations may not be enough for some users like @mikeallbutt , but I am not sure that returning all is necessarily the answer either.  Focus exists for a reason, and may be useful to other users.

I wonder whether a possible workflow would be:
1. Get "Focus" Locations
1. Include a link at the bottom of the list to return "All" Locations, so if the user is typing and what she/he needs is found in "Focus", then they select it and are fine, however, if they type and auto-complete is returning only a few (or none) results, then they see the link and click it and the entire list is returned.

That feels a little unorthodox to me, so I welcome other suggestions, but I don't think that the solution is to simply return "All" immediately.  Thx!

**Comment by zdmc23** [comment]
Per @ahillbilly the proper solution is to expand the Locations in your area of Focus 

CC @mikeallbutt

**Comment by mikeallbutt** [comment]
This "solution" is not a solution that works. If I increase my focus, it shows goes up one level (from a country level) it to show all (the whole world).
As I later explained to @ahillbilly another option is to request used locations, so that if a location about the focus has been used, then that will be offered.

**Comment by ahillbilly** [comment]
@zdmc23 I'm late to this party, but would agree with @mikeallbutt that there is still an issue here (maybe a new one also).  The focus region is important, and the solution isn't to always return all locations as you commented.  I can't find my notes to you, they were probably in Slack... but I think they covered the reality that the region of focus can be expanded with pretty granular controls.  I think that could address the bulk of an issue.
 
This issue, however addresses a momentary need to select a location that for some reason falls outside of your focus region. 
 The web app has a selector to temporarily switch from region of focus to all locations on the location editing field and type-ahead.  I think a similar solution would address this issue for the mobile app.

A separate issue is probably the type-ahead logic to first display commonly used locations (as well as used locations outside of the region of focus).  In many areas around the world locations have common beginnings and it is difficult to find "Santa Maria" from the list of 100 Santa _somethings_, especially when Santa Maria is the location of a large percentage of your contacts and regularly used...

@zdmc23 Curious if this should be re-opened and also @mikeallbutt if you want to articulate the issue on the type-ahead logic for providing options for selection.
