### ISSUE TITLE
Delete a date

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#366]
There are times when a date needs to be deleted. 
eg. A group that was inactive but has become active will still have the End Date set.
or a baptism date was accidently set.

**Comment by ericchen59** [comment]
**Mockup**

Example from Microsoft Planner iOS app
![IMG_A59A48FF7A52-1](https://user-images.githubusercontent.com/26180602/93658386-2889f180-fa09-11ea-990a-bbfba2c840e9.jpeg)

Mockup using DT iOS ap
![IMG_C301AEAD8EE9-1](https://user-images.githubusercontent.com/26180602/93658393-2f186900-fa09-11ea-906a-aa3d2c5990d2.jpeg)

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ericchen59 See the following video with the implementation: [https://drive.google.com/file/d/1dhjEXCRXjRG_DX3tm_pqt4Teuh3njdw9/view?usp=sharing](https://drive.google.com/file/d/1dhjEXCRXjRG_DX3tm_pqt4Teuh3njdw9/view?usp=sharing)

**Comment by zdmc23** [comment]
Looks good, thx!
