### ISSUE TITLE
Group: Display record/ID number for fields in edit mode

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#368]
Group: Contact ID numbers need to be added to the end of each list item for the fields:

- [ ] assigned, 
- [ ] group coach, 
- [ ] members: add member, 
- [ ] groups: parent, 
- [ ] groups: peer, 
- [ ] groups: child.

**Comment by zdmc23** [comment]
Relates to #370
