### ISSUE TITLE
Edit to contact information is not reflected on contact list screen

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#37]
MexSurfer:
> I adjusted the contact “Mohammed Moghadam” name but it was not reflected until the details tab loaded. I suspect this is related to how the page loads.

If I edit name or seeker path (two things shown on contact list), the data is updated in the contact detail screen, but when I go back to the contact list, the updated information is not reflected there.

**Comment by deividfdez** [comment]
@cairocoder01 issue solved

**Comment by cairocoder01** [comment]
@deividfdez I just tried testing this and it still doesn't update the contact in the list screen. I did a refresh of the Expo app a couple times to try to make sure it was using the most recent version of the app.

I went into `JW Test` contact and changed the name to `JW Tester` and clicked save. I then tap the back arrow to go back to the contact list, but it is still listed as `JW Test` on that screen.

**Comment by raschdiaz** [comment]
Hi JW, can you provide us a step-by-step process to reproduce it?. Are you in 'ONLINE' or 'OFFLINE' mode?.

**Comment by cairocoder01** [comment]
In Online mode:

1. Scroll to "JW Tester" in contact list. Tap to view details screen.
2. Tap "Edit" link in top right
3. Change name to "JW Test". Tap Save button
4. Confirm name is changed correctly in top nav bar to "JW Test" (this works as expected)
5. Tap back arrow in nav bar to go back to contact list screen.
6. Instead of seeing the new name of "JW Test", the contact name is still listed as "JW Tester"

**Comment by cairocoder01** [comment]
Since this problem seems to have to do with `FlatList` not doing a deep comparison of the props to determine if it needs to re-render.

It seems there is another prop called `extraData` that could possibly be used to detect changes to the contacts array. Maybe we put a stringified version of the array in that prop or just set it to a date/time of the last contact update date/time.

https://stackoverflow.com/questions/44278526/react-native-flatlist-not-rerendering-row-when-props-change

**Comment by zdmc23** [comment]
@cairocoder01 You labelled this as MVP, should we take this up in the current Sprint, or should we release with this as a known issue since it may not be a trivial fix?

**Comment by cairocoder01** [comment]
This seems to be working as expected now. Closing.
