### ISSUE TITLE
Item ID # in fields/dropdown lists

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#370]
On the website, the item ID number is listed after all list items. This is helpful and should be displayed on all fields/dropdowns in edit mode.
People groups and locations are currently missing this information.

**Comment by zdmc23** [comment]
I've also recv'd requests for this to distinguish contacts

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 see the following video with the changes: [https://drive.google.com/file/d/1Q26KgfJ8kMkkHU7VtBSS5exLYu18C15o/view?usp=sharing](https://drive.google.com/file/d/1Q26KgfJ8kMkkHU7VtBSS5exLYu18C15o/view?usp=sharing)

**Comment by zdmc23** [comment]
Hi @raschdiaz , I think that this looks great for the Contacts and the Groups, but some of the fields are redundant and probably unnecessary (i.e., Status, Source, Age, etc...)

@mikeallbutt what are the minimum number of fields that require this ID, I thought that it was only Contacts and Groups, but it seems like you want more.  Thx!

**Comment by zdmc23** [comment]
Update from Slack channel discussion: 

Let’s show IDs only for Contacts & Groups, wherever they are found (ie, Lists, Connections, Assigned, etc...)
