### ISSUE TITLE
Login screen spacing for small screens

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#372]
On Android 9 and a smaller phone, the language selection space at the bottom gets truncated. By adjusting some spacing elsewhere, this area will be full visible.

![Screenshot_20200711-163911](https://user-images.githubusercontent.com/43966676/87234588-19971b00-c398-11ea-9d54-f20ad630967e.png)

**Comment by zdmc23** [comment]
I tried modifying `paddingTop` in the header style, but that wasn't enough to enable display on my Moto G4 with Android 7.1.  We'll need something more sophisticated that checks the screen size and scales accordingly

**Comment by zdmc23** [comment]
https://medium.com/@shanerudolfworktive/7-tips-to-develop-react-native-uis-for-all-screen-sizes-7ec5271be25c

**Comment by zdmc23** [comment]
v1.10 now has scroll capes
