### ISSUE TITLE
Manual edit of member count 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#375]
On the members screen of a group the member count is displayed and needs to be manually editable in edit mode. 

_Originally posted by @zdmc23 in https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/198#issuecomment-597728658_

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt , see the following video: [https://drive.google.com/file/d/1dWE0GjvQgbA5P2Lv3oDcm8cdXWSmag_k/view?usp=sharing](https://drive.google.com/file/d/1dWE0GjvQgbA5P2Lv3oDcm8cdXWSmag_k/view?usp=sharing)

**Comment by mikeallbutt** [comment]
Nice. 
I would like to suggest that the editing field moves up to be located next to the text "Member Count:"

Also, on the non edit screen the text "Members:" should actually say "Member Count:"

**Comment by raschdiaz** [comment]
Hi @mikeallbutt we do the label change to "Member Count" on 'only view' mode.

About the field, we prefer to keep the field this way, because its similar to others fields like 'name', 'address' (except for the icon).

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt we do the label change to "Member Count" on 'only view' mode.
> 
> About the field, we prefer to keep the field this way, because its similar to others fields like 'name', 'address' (except for the icon).

Ok. I did think if that about the field being the same as "name" and "address" but the difference being that those need lots of space, but member count needs maybe 2 or 3 characters. It will look much better to be moved up (and I think it isn't too difficult to code it either.)

**Comment by ericchen59** [comment]
@zdmc23 - I'm didn't hear that the offline implementation was completed yet by @raschdiaz. Is it complete?

Just wanted to make sure we didn't miss that

**Comment by zdmc23** [comment]
@ericchen59 Good point!  The merge auto-closed the issue, but let's re-open until offline implementation is complete

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt @ericchen59 We implemented this feature in OFFLINE mode, see the following test flow: [https://drive.google.com/file/d/1dkWJEY_RCsuAPdQexpd4yYH-MCIMR0MT/view?usp=sharing](https://drive.google.com/file/d/1dkWJEY_RCsuAPdQexpd4yYH-MCIMR0MT/view?usp=sharing)

We implemented the flow according to what was discussed in Slack:

- If the 'list of members' its higher that current 'member count', update the 'member count' with the current 'list of members' length.
- If the 'list of members' its less that current 'member count', update the 'member count' decreasing the value according to the quantity of removed members.
