### ISSUE TITLE
Introduce Error Tracking (e.g., Sentry)

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#380]
Introduce Error Tracking during this development and testing phase of the project in order to more rapidly identify and diagnose issues related to crashes.

Per Carlos,

> We could use a cloud service by Rollbar, Sentry or Bugsnag, in my experience are the top in the market and all of them have a free plan to start, then it’s need to pay. In the case for mobile app we could use a Firebase Crashlytics this is a 100% free forever service. Or if you want an isolated and private tool, Sentry is open source and it’s possible to install in DT servers... Sentry and Bugsnag have a special plan for open source projects and DT meets this requirement

https://sentry.io

**Comment by raschdiaz** [comment]
Hi @zdmc23 We implemented Sentry in the mobile app, to detect possible errors in the HTTP requests. also detect possible error in the render of the Detail views (Contact/Group):

![Captura7](https://user-images.githubusercontent.com/16809967/88399017-d96a6c00-cd8b-11ea-98b5-18ab8bd2ea74.PNG)
