### ISSUE TITLE
Apply same Filter and Search Bar changes to Groups

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#384]
With #226 and #257 , we introduced changes to Filter Contacts and keep the Search Bar in a fixed location during scroll.  We want to implement the same functionality for `Groups`

**_This implementation should not be a duplication of code in Groups list screen, but rather a shared component leveraged by both Contacts List and Groups List_**

Depends on #385

**Comment by raschdiaz** [comment]
Hi @corsacca which end-point will return the groups filters, it like this? `/wp-json/dt/v1/users/get_filters?post_type=groups&force_refresh=1`

**Comment by corsacca** [comment]
@raschdiaz 
Good question. I've now created a documentation page to refer to: https://disciple.tools/dev-docs/rest-api/posts-contacts-groups-etc/list-filters/
Please consider the "query" field on each filter. It is the parameters needed to get the list of contacts or groups for the filter.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @mikeallbutt @corsacca We implemented the component in the Groups view, se the following video: [https://drive.google.com/file/d/1eD8FXp7S9D_aQegnwJ7Cf59LsVqmsuBC/view?usp=sharing](https://drive.google.com/file/d/1eD8FXp7S9D_aQegnwJ7Cf59LsVqmsuBC/view?usp=sharing)

**Comment by zdmc23** [comment]
Great!  Thx @raschdiaz
