### ISSUE TITLE
Visual indicator of Filter selection

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#385]
When the user filters their contacts, they select an option (e.g., `Waiting to be accepted`) and the Accordion component closes, and the `Contacts` filter correctly, but there is currently no visual indicator to remind the user which filter that they have chosen.

I am not certain about a preferred way to display at the moment, but we should discuss on the next group conference call

**Comment by raschdiaz** [comment]
Hi team, can you provide us some mock up about this flow?.

We think the app can change the filter icon color (to theme primary color), when a filter its active.

**Comment by zdmc23** [comment]
Hi @raschdiaz The D.T mobile website uses `chips` to display the active filters. You could highlight list (All Contacts vs My Contacts) using primary color (like is done when actively selected), and have the `chips` or non-clickable/disabled `buttons` to display the filter from that list (ie, "Yay! New Contact") and the fixed sort order that we use (as a reminder): "Sorting by: Date Modified - most recent" (or something with fewer characters)

![7EEA4EB1-A100-45B0-9A24-34C671B40688](https://user-images.githubusercontent.com/191707/93403401-6ba36380-f855-11ea-91e4-6cd3ee3e900a.jpeg)

**Comment by zdmc23** [comment]
By the way, I *do* realize that the filter `chip` is redundant since we already have the text in the Contact List item component (eg, "Yay! New Contact"), but having the `chip` would enable the filters to be multi-select vs. radio button / mutually exclusive, bc then you could have:

All Contacts
My Contacts (blue/primary color - active)
_____________
[Yay! New Contact] [Requires Update] [Sorted by: Date Modified - most recent]

_____________
Jane Doe
[Yay! New Contact]
_____________
Juan Gabriel
[Requires Update]
_____________

**Comment by raschdiaz** [comment]
Hi @zdmc23 , We think don't understand the requirement. We have to implement the 'chips' visual elements in the mobile? Or implement some alternative?

**Comment by ericchen59** [comment]
@raschdiaz I'm going to assume we want to implement 'chips' as the visual way to show filters. My preference is that we stick closely to what the DT website looks like

**Comment by zdmc23** [comment]
@raschdiaz Yes, please implement the `chips` visual elements as a visual indicator of filter selection.  In the future, we may also leverage the `chips` to enable multiple filters rather than a mutually exclusive radio button format

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 We implemented the chips like web, see the following video:

[https://drive.google.com/file/d/1eT9WOPDI1SjfRGoG-fASwkPXFGmlNUQE/view?usp=sharing](https://drive.google.com/file/d/1eT9WOPDI1SjfRGoG-fASwkPXFGmlNUQE/view?usp=sharing)

As you can see, the 'Sorting By Date' chip its showed only when some filter (text, radio option) are active. This to avoid the 'searchBar' component use more height all the time.

**Comment by zdmc23** [comment]
Thx @raschdiaz !
