### ISSUE TITLE
Crashes when adding connections or members

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#386]
In my instance, I am getting lots of crashes when adding connections or members to groups.

**Comment by zdmc23** [comment]
Hi @mikeallbutt , please try deleting Expo App data/cache on Android, or re-installing Expo on iOS.  These new crashes may be a result of data being stored on your device which do not match what is being returned in the API.  Refreshing should correct the issue, as I'm unable to reproduce these (I am able to both successfully add connections to a Contact and members to a Group)

**Comment by mikeallbutt** [comment]
This issue seems to be resolved.
