### ISSUE TITLE
Crashes using FAB to assign Meeting Complete

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#387]
View a contact record, press FAB, touch 'meeting complete', app crashes.
(This happened many times using my oikos instance.)

**Comment by zdmc23** [comment]
I am unable to reproduce using "dtappdemo" and "Hillbilly's brother" Contact

**Comment by mikeallbutt** [comment]
This issue seems to be resolved.
