### ISSUE TITLE
Unrequested data change: removed group from a parent/peer/child group field

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#388]
When there are 2 or more groups listed in a parent/peer/child group field, the first group stays but the others are removed when group details are changed (setting the church start date).

The same type if issue happens for a contact.

**Comment by zdmc23** [comment]
Confirmed on iOS 13.5.1

![03FF898E-B9CA-40BB-924A-FFD848C0E7C0](https://user-images.githubusercontent.com/191707/88624875-c0a4d380-d075-11ea-9e77-49822b0a5b3d.png)
![1CAB7981-1935-4D90-AF30-93DCC7A993E8](https://user-images.githubusercontent.com/191707/88624879-c13d6a00-d075-11ea-9798-83b26bb5143a.png)
![F3C9C935-F7B7-45A1-A0F5-B99A212B975A](https://user-images.githubusercontent.com/191707/88624881-c13d6a00-d075-11ea-8c48-1b464c29c848.png)

**Comment by zdmc23** [comment]
Hi @raschdiaz , we need to prioritize this issue for Sprint 24 in order to perform a release this weekend.  Thx!

**Comment by ahillbilly** [comment]
This is applicable for all the "Connections" type fields.

**Comment by zdmc23** [comment]
Note: **_Step # 4_** of the `Steps to reproduce` is the **_key_**.  You must Add a Group to `Parent`, `Peer`, or `Child` Groups, and then click to navigate to `Group Details`, and `Edit`, and `Save`.

**Comment by mikeallbutt** [comment]
@zdmc23 @raschdiaz this issue happened again in the current 1.7 version of the app when I was updating a record on my instance. I will send you the details privately.
