### ISSUE TITLE
Add labels to quick action buttons

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#39]
MexSurfer:
> The quick action buttons need better explaining, like having the word next to the icon saying what it does. (see the Evernote app example of how they do it) At present the icons are to ambiguous.

Suggest adding labels along side each quick action to explain them - in the same way Evernote and other apps do so.

![image](https://user-images.githubusercontent.com/44169599/64118385-da6f6500-cd97-11e9-8e3e-948a360b6f37.png)

**Comment by mikeallbutt** [comment]
These icons need explaining.

![image](https://user-images.githubusercontent.com/43966676/65357158-d925a100-dbbb-11e9-8621-a6b1e2540916.png)

**Comment by mikeallbutt** [comment]
This are the icons that need to be described.

<img width="184" alt="Screenshot 2019-10-14 12 33 47" src="https://user-images.githubusercontent.com/43966676/66771102-f7ab4f00-ee7e-11e9-863c-6251aaee9420.png">

**Comment by mikeallbutt** [comment]
The quick actions button could look like this.

<img width="257" alt="Screenshot 2019-10-20 00 13 31" src="https://user-images.githubusercontent.com/43966676/67421500-3a170f00-f596-11e9-8384-1e050bbb25e8.png">

**Comment by cairocoder01** [comment]
@mikeallbutt Correct, that last screenshot is exactly what we want (as detailed in the prototype: https://xd.adobe.com/view/7080ce9f-27ae-4018-449e-33b6bcc61293-06b1/screen/3cf7701e-dec1-46b4-9753-43c5533516e1/Contact-Details-quick-actions)

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt i have implemented a new component to solve this. I have pusblished a new version in Expo, check it please.

**Comment by mikeallbutt** [comment]
I have been trying to see the changes in expo but can't. Do I need to do more than delete the cache every time there is an update to expo?

**Comment by cairocoder01** [comment]
I'm also unable to see the changes in Expo. I've already cleared the storage and reinstalled the app again.

**Comment by cairocoder01** [comment]
@raschdiaz I can see the labels in Expo. However, it is missing the darkened background like the mockup that is shown above. Also, the text is a little small. Can you please match the style to that mockup?

* [ ] Add semi-transparent background when FAB is open
* [ ] Increase label font size and update color to match mockup

**Comment by raschdiaz** [comment]
Hi @cairocoder01 i have implemented this updates. The tag name of this issue is: 'sprint-9-issue-39'.

**Comment by zdmc23** [comment]
Verified

![A6A62D94-5F14-4F1B-9983-B35EDBE3DFD4](https://user-images.githubusercontent.com/191707/68531492-a60cad80-02e0-11ea-927c-ceb8227306e7.png)
