### ISSUE TITLE
Reset or enforce Filter upon clicking back button

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#390]
Currently, when I filter `Contacts` and then click a `Contact` and then click `<-` back arrow, the `Contacts` are no longer filtered, but the `Filter` component continues to be displayed and the `Filter` criteria continues to be enabled.

We should either enforce the `Filter` criteria and only show the "Waiting to be accepted" `Contacts`, or reset the `Filter` and hide the Accordion component

Steps to reproduce:
1. Select a `Filter` criteria (e.g., "Waiting to be accepted")
1. Select any of the `Contacts`
1. Click `<-` back arrow
1. Observe that All Contacts are being displayed, but `Filter` According remains showing and same `option` ("Waiting to be accepted") remains selected

**Comment by raschdiaz** [comment]
Hi @zdmc23 We implemented your second suggestion: On the back button click, the view will reset the **Filter** and hide the **Accordion** component.

[https://drive.google.com/file/d/1UYu7GcXF70DCNotQZvE2873avRDPXj4z/view?usp=sharing](https://drive.google.com/file/d/1UYu7GcXF70DCNotQZvE2873avRDPXj4z/view?usp=sharing)
