### ISSUE TITLE
Encoding mismatch between D.T instance and app causing Name/Title change activity

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#395]
Because of an encoding mismatch between D.T Instance and the Mobile App, a Name/Title change activity occurs with each and every Edit/Save of a Contact/Group having the char encoding fix per #345 

Steps to reproduce:
1. Select a `Contact` or `Group` with an "&amp;" on the D.T Website and an ampersand ('&') on the Mobile App (e.g., "Everyones & church")
1. Click `Edit`
1. Edit ANY field
1. Click `Save`
1. Click `Comments & Activities` and observe that a Name/Title change activity is logged

![BE487CB4-5198-4052-9DDA-391284CC7C9D](https://user-images.githubusercontent.com/191707/89248067-c1d98180-d5dc-11ea-9fb2-7721864fcd77.jpeg)

**Comment by ericchen59** [comment]
@raschdiaz Just FYI, I was able to reproduce this through Expo.

iPhone 6s, iOS 14.0.1

Reproduction Flow
https://drive.google.com/file/d/1Q3Umi7EOV1VHK4OVEuxWwGcl5KvVDxZe/view?usp=sharing

Final Result - Mobile view
![IMG_2982](https://user-images.githubusercontent.com/26180602/95413971-c3843600-08fa-11eb-9afc-da4e79ca976b.jpg)

Final Result - Web view
<img width="1187" alt="Screen Shot 2020-10-08 at 12 13 41 AM" src="https://user-images.githubusercontent.com/26180602/95414376-bb78c600-08fb-11eb-8fee-3d89d65da1d0.png">

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 see the following video with the fix: [https://drive.google.com/file/d/1gAPPFubDamYrptKMxyN5WVMhgN0ma9st/view?usp=sharing](https://drive.google.com/file/d/1gAPPFubDamYrptKMxyN5WVMhgN0ma9st/view?usp=sharing)
