### ISSUE TITLE
Unrequested update to Status, Age and Gender

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#397]
I made a change to a contact by assigning who this contact was coaching, BUT other fields were updated/ recorded data changes in the activity log, even though I didn’t touch those fields.:
Status, Age and Gender.

**Comment by zdmc23** [comment]
@mikeallbutt , I cannot reproduce with these steps alone.  I edited "Mazifa" `Contact` and specified "Hans C. Test" in `Coached` field, but the `Status`, `Age` and `Gender` did not show up in `Comments & Activities`

**Comment by mikeallbutt** [comment]
Steps to reproduce:
create a new contact - just fill in the name.
got into edit mode for the newly created contact
add some connections - I added 2 contacts for the "coached by" when the field was previously empty
press save
review the activity - and you will see that Age was updated.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 , We can't reproduce this error, Wed do the test in two D.T. instances but it works as expected.

**Comment by mikeallbutt** [comment]
> Hi @mikeallbutt @zdmc23 , We can't reproduce this error, We do the test in two D.T. instances but it works as expected.

Ok Thanks @raschdiaz - I did another test with dtappdemo and I can still reproduce it - using the steps I described above. Look at the logs for contact "397 test".

**Comment by mikeallbutt** [comment]
When adding the two people who were baptised by this contact, the 2 fields were logged.

![age-gender](https://user-images.githubusercontent.com/43966676/90995219-e348e000-e580-11ea-9fa6-9ba97fe1522c.png)

**Comment by mikeallbutt** [comment]
Steps to reproduce:
sign in as a multiplier
create a new contact
save
edit the new contact
change the status to closed
save
view the activity - and you will see that age has been recorded in the log, but if you go to it the says "not-set".

**Comment by mikeallbutt** [comment]
@raschdiaz and @zdmc23 
On this record https://dtappdemo.wpengine.com/contacts/1391/ the activity was logged (September 21, 2020, 6:24 AM) various connections were made and the Age & Gender were once again noted. Those fields were previously blank but maybe an invisible character has been inserted or removed into or from the fields.

**Comment by ericchen59** [comment]
@mikeallbutt I wasn't able to reproduce this as an admin user on the production D.T. app. Can you check once more if you can reproduce this?

**Comment by mikeallbutt** [comment]
I have also seen that the **name field** gets logged in the activity record that it has been updated but it was not touched.
