### ISSUE TITLE
FAB context (different options for Contact vs Group)

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#403]
Currently the FAB is specific to Contacts, but we should make it context-aware for Groups as well

**Comment by zdmc23** [comment]
Currently there is no FAB for `Group`, so we need to define what "fast actions" should go there

**Comment by mikeallbutt** [comment]
As per this issue https://github.com/DiscipleTools/disciple-tools-theme/issues/1007

Initial actions could be:

- Meeting scheduled
- Meeting postponed
- Meeting complete
