### ISSUE TITLE
Age field showing as "not-set"

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#406]
Observed on iOS 13.6

`Age` field is showing as "not-set"

Steps to reproduce:
1.  Login to "dtappdemo" instance
1. Select `Test of issue 397 @854pm`
1. Observe that `Age` field displays as "not-set"

![064DA8A5-E0A9-4232-8561-AC80B79DEDEC](https://user-images.githubusercontent.com/191707/90837879-43d9e200-e321-11ea-87e7-115a7ecff3b4.jpeg)

**Comment by raschdiaz** [comment]
Hi @zdmc23, see the following video showing the fix: [https://drive.google.com/file/d/1f8H_IOsp5SUwxh9EKCuLoPJ-f3AkvlX4/view?usp=sharing](https://drive.google.com/file/d/1f8H_IOsp5SUwxh9EKCuLoPJ-f3AkvlX4/view?usp=sharing)
