### ISSUE TITLE
App crashes when clicking any FAB option under Contacts->Connections

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#407]
Observed on iOS 13.6

App crashes when clicking any FAB option under Contacts->Connections

Steps to reproduce:
1. Login to "dtappdemo" instance
1. Select `Test of issue 397 @854pm`
1. Click `Connections`
1. Click `FAB` and select *any* option
1. Observe crash and empty screen

![A28BCD2A-3CD9-4072-B46B-537C079F0DBA](https://user-images.githubusercontent.com/191707/90838288-80f2a400-e322-11ea-9318-8982de539dbc.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 see the following video with the fix: [https://drive.google.com/file/d/1cQ_ShtQtwM6RmY7YYYpyNvkM3UhurUpD/view?usp=sharing](https://drive.google.com/file/d/1cQ_ShtQtwM6RmY7YYYpyNvkM3UhurUpD/view?usp=sharing)
