### ISSUE TITLE
Setting a Baptism Date results in a saved date of 1 day less than the specified date

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#408]
Observed on iOS 13.6

Setting a Baptism Date results in a saved date of 1 day less than the specified date

Steps to reproduce:
1. Login to "dtappdemo" instance
1. Select `Hans 1234` Contact
1. Click `Progress`
1. Click `Edit`
1. Select a new `Baptism Date`
1. Observe change has taken effect properly
1. Click `Save`
1. Observe upon refresh/reload that the date is now displaying as 1 day less than the specified date

For reference, please see video:
https://youtu.be/XlkWbZjlbrI

**Comment by yorkaspacher** [comment]
Guess what! This is happening in the web version. Just opened a contact in my DEMO site, tapped Baptized in Faith Journey, selected - very distinctly - September 7, 2020, and it saved it as September 6, 2020. Don't think this is a mobile app bug.

**Comment by zdmc23** [comment]
Nice catch @yorkaspacher !  I always like the `bugs` that are on @corsacca 's side :-P

**Comment by corsacca** [comment]
Anyone have a link to a contact where this happened?

**Comment by corsacca** [comment]
@zdmc23 does https://dtappdemo.wpengine.com/contacts/1775/ display march 11 or march 12 for you now?
It shows march 12 for me both on the web version and on the app.
Since the timestamp represents the start of the day in utc in wonder if there is some timezone conversion going on.

**Comment by zdmc23** [comment]
@corsacca March 11 is displayed for me

![Screenshot from 2020-09-14 09-35-25](https://user-images.githubusercontent.com/191707/93092687-c11d1c00-f66d-11ea-9e3e-3cd9147aa1be.png)

**Comment by zdmc23** [comment]
@corsacca You're probably correct that it's a date conversion issue

@raschdiaz We're going to need convert to/from UTC and Local time in Moment.js, as described here: https://stackoverflow.com/questions/32540667/moment-js-utc-to-local-time#32540840 .  We can probably start by modifying the `formatDateToBackEnd` method that you have in `shared/index.js`

**Comment by corsacca** [comment]
@zdmc23 Ok Thanks for confirming. It is an issue on both the web and mobile. I changed the time zone on my computer and the date changed for me too.
Note: The "formatted' parameter of the date field is likely correct. The timestamp is the start of the day utc, so with timezones it will be converted to the previous day in the USA.

**Comment by zdmc23** [comment]
I've resolved this in https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/b25a1413116897b150d0312465eb7486d5eb6f58 , but it's not clear to me why the `Comments and Activity` dates do not also require this change (tho it's working, so I won't think too hard about it ;-) )

**Comment by corsacca** [comment]
@zdmc23 for comments we want to convert to the current time zone so the user knowns when the comment was created in their own time zone. 
For dates we don't want to convert.

**Comment by zdmc23** [comment]
@corsacca thanks for clarifying.  No worries, I didn't change the way that the dates are saved, only viewed in the app
