### ISSUE TITLE
Display "Load More" link only when there are more items to load

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#410]
On both the list views of contacts and groups the "Load More" text link is always visible, which is confusing if there are no more items to load. The link should only display when there are actually more items that can be loaded.

**Comment by ericchen59** [comment]
Video of flow
https://drive.google.com/file/d/1JN8EnmnVQt5LVtBM-ObGy41bVPHRlSsy/view?usp=sharing

Acceptance Criteria
- [ ] in (contacts, groups) at bottom of list, there should only be the word _Load More_ if there are more contacts and groups to be loaded

**Comment by ericchen59** [comment]
There are Load More in multiple places, @ericchen59 do a double check

**Comment by raschdiaz** [comment]
Hi @ericchen59 @mikeallbutt see the following video showing the implementation:

[https://drive.google.com/file/d/1oSX-4mtW32YORuMf5BrGa6Uc8BtujAtc/view?usp=sharing](https://drive.google.com/file/d/1oSX-4mtW32YORuMf5BrGa6Uc8BtujAtc/view?usp=sharing)

For this example flow, we set the pagination to 10 and the total records to 30.
