### ISSUE TITLE
Slow to Save made duplicate activity

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#413]
When in edit mode and I pressed save after modifying a group and clicked save, it took much longer than I expected to save and return to the non edit screen, so I pressed the save button a second time, and got duplicates of the activity/modifications.

**Comment by ericchen59** [comment]
@mikeallbutt I wasn't able to replicate the issue. Can you share a screen recording of this behavior?
