### ISSUE TITLE
Search filter activated by selecting more than the text

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#415]
In list view and using the filter, by clicking "the dot" next to (on the left side) the filter type in the filters available (not just the word) should activate the filter.

**Comment by ahillbilly** [comment]
![Filter list drop down](https://user-images.githubusercontent.com/25323324/95193798-4bb7ed80-07cc-11eb-83d0-effae9ee0b8b.jpeg)

The blue dot on the dropdown indicates the current filter.  Pressing on another dot should select that filter.  Currently the selection zone for changing the filter is only the filter name and doesn't include the dot to the left of the name, but usage would indicate that the dot is often a target when attempting to make the filter change.

**Comment by raschdiaz** [comment]
Hi @ahillbilly to confirm the @mikeallbutt comment:

The user can select multiples filters options (radio) and write a text, applying all this filters in the same search.

For example: Write 'Hans' word, Select the 'active' and 'closed' options -> Show contacts that apply this 3 filters.

Its that correct?.

**Comment by ahillbilly** [comment]
Is that comment from another issue?  I don't see that comment above and that to me sounds like an advanced feature that I don't think we are pushing for.  This one is just improving the usage and making the area that feels selectable, truly selectable.

I do remember something where they were talking about multiple filters and search in the sprint meeting, but I'm not sure it was clarified and it definitely felt like a feature creep.

**Comment by mikeallbutt** [comment]
> Currently the selection zone for changing the filter is only the filter name and doesn't include the dot to the left of the name, but usage would indicate that the dot is often a target when attempting to make the filter change.

This is what the issue is about. Just making the dot to the left of the text to be selectable.

**Comment by raschdiaz** [comment]
Oh ok, understood.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ahillbilly We implemented the fix: [https://drive.google.com/file/d/1fQc2aqagAwT7kkovvqclWNs32eR7GRbP/view?usp=sharing](https://drive.google.com/file/d/1fQc2aqagAwT7kkovvqclWNs32eR7GRbP/view?usp=sharing)
