### ISSUE TITLE
FAB to create new contact can accidentally be activated when the filter list visible

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#416]
When in contact list view, open the filter and it will fill the screen. The FAB is not visible but if you touch where it normally is (bottom right side), the create new contact action will be activated - instead of activating the filter.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 , see the following video: [https://drive.google.com/file/d/1dbEebtimFF2Wll-OfGopypwI1bcunQ-d/view?usp=sharing](https://drive.google.com/file/d/1dbEebtimFF2Wll-OfGopypwI1bcunQ-d/view?usp=sharing)
