### ISSUE TITLE
Empty filter results for My Contacts

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#417]
When using the filter in the contacts list view, I select `My Contacts`, and opens/expands to list the different types. I select whichever type and the screen adjusts but shows nothing/no list of items/records.

![empty-list](https://user-images.githubusercontent.com/43966676/90912594-7c6cd080-e3a0-11ea-96b6-b1d5121d7775.png)

The following short video shows the issue.
https://drive.google.com/open?id=1Qv7XOlXiLVPsfTY76zyisHWDzuPpuY7T

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 We apply the fix. This issue was caused for some JSON restructure we have to do, related to the issue [https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/400](#400)
