### ISSUE TITLE
Contact details: Age field is confusing

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#420]
When setting the age of a contact DT uses a pre-configured age range but in the details screen of the contact it doesn't state the chosen age range but instead converts it to show a less than or greater than expression. 
Select 26-40 and it shows less than 41 - which is confusing. Maybe the person is less than 25 - which is actually another age range that could be selected.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 see the following video with the fix: 

[https://drive.google.com/file/d/1iE0Ovb6IhZdNT6xECjQmF_JLIKzX-DyJ/view?usp=sharing](https://drive.google.com/file/d/1iE0Ovb6IhZdNT6xECjQmF_JLIKzX-DyJ/view?usp=sharing)

Additionally two things:

- Several translations were added, please add the respective translations.
- We fix some error when the user try to edit the contact info.
