### ISSUE TITLE
Group leader footprint icon is staying activated

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#424]
Incorrectly, the Group member leader icon (on a group members screen in edit mode) stays black after being inactivated. 

1. access a group record
2. go to the members screen in edit mode
3. (add a member if there are none)
4. click the footprint icon to set that this contact is a leader.
5. press the icon again - but it stays black (and not grey like it should)
6. click save
7. return to edit mode and the members screen
8. press the footprint icon - and still the icon stays grey and not black.

Interestingly it seems that the leader is actually removed correctly even though the icon stays black.

**Comment by zdmc23** [comment]
changing this to a `bug` and prioritizing it in the upcoming Sprint per @mikeallbutt

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 We apply a fix to this: [https://drive.google.com/file/d/1cgJ8hr56EifcrHb24gE1DyG2DWgHaiPt/view?usp=sharing](https://drive.google.com/file/d/1cgJ8hr56EifcrHb24gE1DyG2DWgHaiPt/view?usp=sharing)
