### ISSUE TITLE
Underline group members names in view members screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#425]
Group members tab: members names should be underlined to be consistent with other areas of the app to indicate clicking the name will take the user to that contact.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 see the following video showing the implementation: [https://drive.google.com/file/d/1hqAjfb-fXnYHqqqMZv3LHgjlFc3iro28/view?usp=sharing](https://drive.google.com/file/d/1hqAjfb-fXnYHqqqMZv3LHgjlFc3iro28/view?usp=sharing)
