### ISSUE TITLE
Inconsistent return to contacts list - filtered or not filtered

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#426]
When you have finished viewing a contact record, you can click the large bottom `Contacts` icon and you will (correctly) return to the filtered list. But if you instead click the top left back arrow the list view you are taken to is now not the filtered list.

**Comment by mikeallbutt** [comment]
While this issue is being fixed, it would be good to ensure the same issue does not exist and is resolved for groups as well.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 after doing several test wit multiple devices (Android, iOS), the flow works as expected (contacts/groups):

[https://drive.google.com/file/d/1iXFNVWlkVfTmvy7G-Gb2_0SyIG2JCSBv/view?usp=sharing](https://drive.google.com/file/d/1iXFNVWlkVfTmvy7G-Gb2_0SyIG2JCSBv/view?usp=sharing)

In this test flow, we do the 'back' action using the bottom button and the top back icon.

@mikeallbutt can you confirm the flow works correctly?
