### ISSUE TITLE
Disable the Online toggle when wifi and data are turned off

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#428]
When having wifi and data turned off, it is currently still possible to toggle the `online` switch on the settings screen and then the app tries to be online - and that causes errors because it is trying to talk to the server. The yellow offline strip message is not displayed either, even though the wifi and data are turned off.

I expect that the `online` toggle should not be able to be adjusted (it should be disabled) while the wifi and data are turned off.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , see the following video demonstrating the implementation: [https://drive.google.com/file/d/1fSrEcCT44OhvGycoB-KQ8ijtQ4Qvje1e/view?usp=sharing](https://drive.google.com/file/d/1fSrEcCT44OhvGycoB-KQ8ijtQ4Qvje1e/view?usp=sharing)
