### ISSUE TITLE
Screen reload issue when using FAB actions on contact connections screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#429]
When using the FAB to mark a `meeting complete` on the **contact connections screen**, the activity is recorded but the screen doesn't fully reload after. Watch the following video to see what happens.
https://drive.google.com/open?id=1SdYqI_3fIvWXdR1HJTtwE686-Jnml8ho

The same happens when other FAB actions are used - like `meeting no show`.

**Comment by mikeallbutt** [comment]
This is the same issue as #407

**Comment by zdmc23** [comment]
Closed via https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/db6a4a9823e8f1f77675c1d576de00c406c5524c
