### ISSUE TITLE
Status not available in edit

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#43]
When in edit mode of either a contact and a group, the status is not visible or accessible.

**Comment by mikeallbutt** [comment]
![image](https://user-images.githubusercontent.com/43966676/65357487-c8c1f600-dbbc-11e9-8711-b22b296b4546.png)

**Comment by deividfdez** [comment]
@mikeallbutt This issue has been solved
