### ISSUE TITLE
login: Username field is stripping out the @ and .

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#430]
When a user has an email address as their username, if they log out using the logout action on the settings screen, they will be taken to the app login screen, but their user name has now been stripped on the @ symbol and any .'s
ie. user@gmail.com becomes usergmail-com

This will become annoying pretty quickly for any app user whose username is their email address.

![login-203344](https://user-images.githubusercontent.com/43966676/90995477-b517d000-e581-11ea-85f3-ff193a633974.png)
![login-203409](https://user-images.githubusercontent.com/43966676/90995479-b77a2a00-e581-11ea-9a84-3dce501b6ff0.png)

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , can you give me some credentials which username its an email?

**Comment by mikeallbutt** [comment]
@raschdiaz I sent you the logins via slack.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ericchen59 @corsacca we apply a modification to save the username write by the user on the login screen (previously, the mobile app save the user_nicename prop returned by the API). For some reason the API return the username this way:

![image](https://user-images.githubusercontent.com/16809967/101368765-8a722e80-3875-11eb-8da9-f9eb9f1e3f32.png)

[https://drive.google.com/file/d/1n5An9Bk3K2xVOOpeU7gniFndTCHICYyP/view?usp=sharing](https://drive.google.com/file/d/1n5An9Bk3K2xVOOpeU7gniFndTCHICYyP/view?usp=sharing)

**Comment by corsacca** [comment]
@raschdiaz Why do you wish to update the username on the server? It is not possible to do so via the API or even on the WP-admin. The user_nicename is a different field not used for login.

Can the form simply be filled with the last value the user entered?

**Comment by raschdiaz** [comment]
Hi @corsacca sorry, I updated my comment.
