### ISSUE TITLE
Sub-assigning a user should auto-share the record

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#441]
Sub-assigning a user should auto-share the record and it should not auto-remove the share when the user is removed.

**Comment by corsacca** [comment]
@mikeallbutt. This looks more like a theme issue. Sharing access is done by the theme/server.

**Comment by ericchen59** [comment]
@mikeallbutt do you have workaround in the meantime?

**Comment by corsacca** [comment]
Hey. It looks like it is working properly on the web. If you subassigned someone (and then refresh the contact) the modal will display the shared user.

@mikeallbutt can you clarify how this might not be working on mobile?

**Comment by mikeallbutt** [comment]
In the app it is working correctly. When a contact is sub-assigned to the contact, that contact that is being edited/updated does get shared with the contact that it is being sub-assigned to.
