### ISSUE TITLE
UI adjustments for Edit & Delete a comment 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#444]
My suggestions are:

- [x] use the word `Delete` and not `Remove` - to keep consistency across the DT web and app.
- [x] make the icons smaller (30% less) so they are more the same size as the text (but ensure you can still distinguish what they are).
- [x] Swap the buttons over - put `Edit` where `Remove` is and `Remove` where `Edit`. Reasoning: scrolling gets done with the touching more on the right side so it will be less chance to accidentally delete a comment.
- [x] Align the `Edit` button to the right side

Edit comment screen:

- [x] Put the comment to be edited inside a text box field (like what is used for the `initial comment` field when adding a new contact) and remove the separation line at the bottom before the buttons.
- [x] Align the text to the top of the field (like it is on the `Delete Comment` screen).
- [x] reduce the size of the modal window so that it doesn't get hidden when the keyboard is activated. (On my screen the words/title `Edit Comment` are not visible when the keyboard is active)
- [x] Not all of the comment is visible when the comment is long. The last part of the comment is shown and not the first part. There should be a scroll bar to indicate that not all the comment is visible.
- The website uses the word `Update` and not `Save`. I think both are good.

90% of the time the user will want to edit and not delete completely a comment. The function to delete a message is needed but will be used very rarely, and doesn't need such a prominent place.

Possibly remove the icon for `Delete` and just have the action as a coloured red text link that is aligned to the left side on the comment area.

Or maybe we should just have the `Edit` button (or even change the `Edit` button to be `Modify`), remove the `Delete` button and then on the Edit screen/modal, add the `Delete` button -so there would be 3 - `Close`, `Delete` and `Save` (or `Update` like the website has).

_Originally posted by @mikeallbutt in https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/304#issuecomment-684035700_

**Comment by zdmc23** [comment]
>Or maybe we should just have the Edit button (or even change the Edit button to be Modify), remove the Delete button and then on the Edit screen/modal, add the Delete button -so there would be 3 - Close, Delete and Save (or Update like the website has).

@mikeallbutt I like this idea, and I've checked each of the items above that I agree with

**Comment by zdmc23** [comment]
As of v1.10, Edit, Delete, Copy are accessible via Long Press on any comment that you wrote.  Copy is available for comments that you did not create.
