### ISSUE TITLE
Icons for parent, child and peer groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#45]
Add different icons for parent, child and peer groups to help distinguish them.

![image](https://user-images.githubusercontent.com/43966676/65357368-7ed91000-dbbc-11e9-9ed6-5dafb88dfecb.png)

**Comment by mikeallbutt** [comment]
I have made some icons for these fields but need guidance as to what types of file and image size I need to export them too.

**Comment by mikeallbutt** [comment]
These are the icons that we are using on the DT site.
![image](https://user-images.githubusercontent.com/43966676/68315133-f388e080-007c-11ea-9090-7be90bdc8f93.png)

**Comment by mikeallbutt** [comment]
@cairocoder01 Here are 5 PNG files to be used by whoever will be adding this enhancement.

![group-child](https://user-images.githubusercontent.com/43966676/68328905-d14f8c80-0095-11ea-9ef2-f7282c6def09.png)
![group-parent](https://user-images.githubusercontent.com/43966676/68328906-d14f8c80-0095-11ea-96a3-f46bf1ea18ba.png)
![group-peer](https://user-images.githubusercontent.com/43966676/68328907-d14f8c80-0095-11ea-83a8-d9c8be31eeb7.png)
![group-type](https://user-images.githubusercontent.com/43966676/68328908-d1e82300-0095-11ea-95d5-5b68c2b9e5aa.png)
![group-types](https://user-images.githubusercontent.com/43966676/68328909-d1e82300-0095-11ea-89eb-d48c2ac46d07.png)

**Comment by cairocoder01** [comment]
@mikeallbutt Those look great! Thanks.

It looks like there's a mismatch between the web screenshot you show and the icons you posted. On the web, parent shows the two children as solid circles, but the app icons indicate that parent is a thick outline on the top circle. Which one is correct for parent?

Also, I'm a little confused why there is both a thick outline and a solid fill used in different situations to indicate which node/group you're describing. To me, it's clearer to use the solid fill instead of the thick outline so that there is a sharp contrast to which node/group is being highlighted in the icon.

**Comment by mikeallbutt** [comment]
> @mikeallbutt Those look great! Thanks.
> 
> It looks like there's a mismatch between the web screenshot you show and the icons you posted. On the web, parent shows the two children as solid circles, but the app icons indicate that parent is a thick outline on the top circle. Which one is correct for parent?
> 
> Also, I'm a little confused why there is both a thick outline and a solid fill used in different situations to indicate which node/group you're describing. To me, it's clearer to use the solid fill instead of the thick outline so that there is a sharp contrast to which node/group is being highlighted in the icon.

@cairocoder01 Those icons were worked on by Corsac and myself the other day, and on his direction, we adjusted the child icon. Those icons should be visible in the next release of DT.

**Comment by mikeallbutt** [comment]
The icons on the edit group screen should also be switched to the new ones. 

Remove the 3 icons in as seen in the attached image.
![Screenshot_20191107-052940](https://user-images.githubusercontent.com/43966676/68385962-9e9ea600-0120-11ea-8c60-9d2d735f894e.png)

**Comment by mikeallbutt** [comment]
This is what the DT site will use for the icons to show variations in the types of groups:
<img width="356" alt="Screenshot 2019-11-07 05 39 20" src="https://user-images.githubusercontent.com/43966676/68386197-284e7380-0121-11ea-9fc3-0e974d5dcc2c.png">

**Comment by cairocoder01** [comment]
Great. That updated web screenshot makes more sense.

Do we need to update the Groups icon in the main tab nav at the bottom too? I am assuming yes. @mikeallbutt

**Comment by mikeallbutt** [comment]
> Great. That updated web screenshot makes more sense.
> 
> Do we need to update the Groups icon in the main tab nav at the bottom too? I am assuming yes. @mikeallbutt

@cairocoder01 I think we should leave the group icon that has people for now. In the future we can discuss all these icons, come to a consensus, then implement any adjustments.

**Comment by zdmc23** [comment]
Verified

![0598D3F6-3A1B-4F85-99EB-504CEA9F92B4](https://user-images.githubusercontent.com/191707/68727539-ad5ae200-0592-11ea-8c69-68e6782286c4.png)
![Uploading 484BF5D7-B404-4092-9EF2-9E21844B713B.png…]()

**Comment by zdmc23** [comment]
![9DAE1AFA-952F-4BB0-B8AA-9EFA27FF435A](https://user-images.githubusercontent.com/191707/68727607-e3986180-0592-11ea-8e75-3902abaaf64a.png)

**Comment by zdmc23** [comment]
![0677FDC5-0AD6-4946-9773-80DD1BB5059C](https://user-images.githubusercontent.com/191707/68727656-0f1b4c00-0593-11ea-93dd-9a0df398ca55.png)
