### ISSUE TITLE
6 digit PIN for enhanced security

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#450]
We have received a field worker request for a 6 digit PIN code (similar to what many apps and iOS enable)

**Comment by ahillbilly** [comment]
The current pin feature only allows a 4-digit pin to be set.  This issue requests the use of a 6-digit pin. @raschdiaz Do you need more information than this?

**Comment by raschdiaz** [comment]
Hi @ahillbilly , okay, understood.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ahillbilly @ericchen59 see the following video with the modification: [https://drive.google.com/file/d/1gFC2TDu41_12U7p9d8jcQZbAP0GR12_w/view?usp=sharing](https://drive.google.com/file/d/1gFC2TDu41_12U7p9d8jcQZbAP0GR12_w/view?usp=sharing)

**Comment by raschdiaz** [comment]
FYI: We recommend to the users with the PIN code active to clean the cache app ( before upgrade the app) to avoid possible problems with old PIN code saved in the app.

**Comment by zdmc23** [comment]
Good reminder!  Thx @raschdiaz
