### ISSUE TITLE
Wrong alignment for list of Members Edit when RTL

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#457]
The list of names should be aligning to the right when the app is set to use a RTL language.

![rtl-members](https://user-images.githubusercontent.com/43966676/93694335-14f58e00-fad0-11ea-86b7-a76ea1042e1b.jpg)

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 see the following video showing the fix: [https://drive.google.com/file/d/1gZmqmivQNlz3eRDPexDCVopfFg7362J7/view?usp=sharing](https://drive.google.com/file/d/1gZmqmivQNlz3eRDPexDCVopfFg7362J7/view?usp=sharing)
