### ISSUE TITLE
Sub assigned needs to offer users in the drop down list

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#458]
In edit mode of a contact, the list only shows the contacts and not the system users. It needs to include the DT users also. 

![sub-assigned](https://user-images.githubusercontent.com/43966676/93776034-bd971100-fbe8-11ea-9049-b84f4e26d442.png)
<img width="242" alt="sub-assigned-to" src="https://user-images.githubusercontent.com/43966676/93776048-c1c32e80-fbe8-11ea-9ce4-471126d5d06a.png">

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @zdmc23 @ericchen59 we added the users list to the 'sub assigned' field, see the following video: 

[https://drive.google.com/file/d/1iARUeZLwCjX5Y8cBEIHd0S_8uuVxBCVJ/view?usp=sharing](https://drive.google.com/file/d/1iARUeZLwCjX5Y8cBEIHd0S_8uuVxBCVJ/view?usp=sharing)

But, comparing the web behavior with the mobile, we notice the web app do a request when the user types a keyboard in the field (to get respective contacts/users). This can cause the web app misses some users that are not returned by the 'users/get_users?get_all=1' end-point. We suggest to create a new issue to implement this search behavior (like [#53](https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/53)).
