### ISSUE TITLE
Dropdown arrow for language setting not functional 

### ISSUE THREAD

**Issue by emmar137** [DiscipleTools/disciple-tools-mobile-app#459]
for the language setting- the downward arrow does not work, you must select the type of language instead in order to edit the language setting

**Comment by ahillbilly** [comment]
I agree with @raschdiaz - I don't understand this issue @emmar137 can you elaborate?

**Comment by mikeallbutt** [comment]
I have just tested this and the arrow does work on Android. If you select the word or the arrow, the menu opens. I think this issue can been closed.
