### ISSUE TITLE
Login screen hangs in loading state intermittently

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#46]
Depending on the internet strength, the login screen sometimes (or often) sits in a loading state after submitting login information. After some debugging, this seems to be as a result of 5 extra API requests that are being done synchronously before the user enters the app. I think these requests need to happen asynchronously in the background so that the user can go straight into the app once their login is successful.

![image](https://user-images.githubusercontent.com/44169599/65612036-f390bd80-dfb3-11e9-933f-4aa8572246ec.png)

**Comment by raschdiaz** [comment]
Hi @cairocoder01 , i have modified the login logic to reduce the amount of end-point required to consume before access to the contacts screen (3). The other end-points are consumed in background while the mobile-app do the login an access to the contacts screen, without affecting the user experience. Can you test it an confirm this fix please?.

**Comment by deividfdez** [comment]
@cairocoder01 please review, we have updated expo.

**Comment by cairocoder01** [comment]
This looks to be sufficient for now. I think we can remove waiting for all but the one login request, but I think this is sufficient for now.

In order to close the issue, can you comment on which pull request this was fixed in @deividfdez?

**Comment by deividfdez** [comment]
@cairocoder01 we will make pull request and let you know ASAP. We were thinking on generating pull requests after solving all issues. We have talked with the team and agreed to create pull request as soon as we finish an issue from our side.

**Comment by deividfdez** [comment]
@cairocoder01 this issue has been generated on pull request 38, since this issue was solved when we started Sprint#9. Please review and validate.

**Comment by cairocoder01** [comment]
@deividfdez There is no pull request with id of 38. Can you confirm which PR contains this change and link to it?

**Comment by zdmc23** [comment]
This appears to be the original commit to address this issue:

https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/67cf3294d4f39522988ce0f23cca7ea16eb33248#diff-9984464dbabb8d0e7e32a73ffe14a6ec

I'm going to close so we can proceed create a `release` branch for this Sprint/Milestone, and begin with regression testing.

We can re-open if necessary, but latest code now reflects only 3 synchronous API requests:

https://github.com/DiscipleTools/disciple-tools-mobile-app/blob/6141edfc6a0ccbe61b51a1672d085b1ffeab442e/screens/LoginScreen.js#L320
