### ISSUE TITLE
Tagging for Groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#466]
DT has a tagging feature. A group can be tagged and those tags used to filter a list. Things that would be good to be able to do are:

- [ ] Create a tag 
- [ ]  apply a tag to a group
- [ ]  remove a tag to a group
- [ ]  use the tags to filter the group list

This should be a component since both Contacts and Groups use tags. See issue #360 for Tagging for Contacts.

**Comment by ericchen59** [comment]
@mikeallbutt It seems that this issue is now a duplicate of the recently expanded scope of #360. I motion to close this issue.

**Comment by ericchen59** [comment]
confirming this is now a duplicate of #360
