### ISSUE TITLE
Can't assign date after clearing a date 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#468]
When a date is set for a field like baptism on the progress screen, if you clear the date and then try to set a new date, the calendar doesn't appear. You need to return to the view mode then re-enter into edit mode and then set the date.

**Comment by ericchen59** [comment]
User story: As a user, I want to set the date of a baptism, clear it, and be able to set it again, without needing to exit the edit mode for a contact.

Acceptance Criteria:
- [ ] In edit mode on a contact, after clearing the baptism date and in the process of selecting a new date, the calendar dials show up

**Flow Demonstration**

**Comment by raschdiaz** [comment]
Hi @ericchen59 we can't see the video, we need to you give us permissions or let the video with public access.

**Comment by ericchen59** [comment]
You should have access now
