### ISSUE TITLE
Mapping Custom Post-types

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#469]
Similarly to issue #353 , Disciple.Tools has the capacity for customization not only in lists and fields and tiles, but also in Custom Post-types (Contacts, Groups, Trainings, Etc).  We need a way to modularly handle these Post-types, both default and custom, especially within the app navigation.  We cannot keep adding items to the bottom bar navigation.

**Comment by ahillbilly** [comment]
During the mobile app meeting on Sept 30, 2020, it was mentioned that we could probably signify notifications without using one of the bottom menu slots.  It was also mentioned that we could turn settings/profile into a hamburger menu that includes settings/profile, but expands to contain additional custom post-types.

There was also discussion about the need for a home screen/dashboard to help identify / push the end user toward appropriate next steps with contacts.   This perhaps should be a new issue...?

**Comment by ericchen59** [comment]
[DTMA-24]
