### ISSUE TITLE
Copy text to paste elsewhere 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#486]
There are certain places where it would be great to be able to copy text and have it available to be pasted elsewhere.

Things like a comment and details about a contact and group would be the most important.

**Comment by ericchen59** [comment]
I'm not sure if this is something that is just a "flip switch" enablement for the entire app, or it has to be enabled "per unit"

@zdmc23 - do you happen to have an intuition about how this feature would be enabled?

**Comment by zdmc23** [comment]
Re-opening for other Text Fields (non-Comments) that will be addressed as we refactor

**Comment by mikeallbutt** [comment]
The places where this is needed is for the name and nickname and note field for contact record and name and note for a group.
