### ISSUE TITLE
While in View mode, remove/hide drop down arrow from Contact and Group status field

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#491]
This UI/style issue was introduced after #484.

User Story: as a user in view mode for a contact or group, I do not want to see a drop down arrow in the status field, so that I will not assume that I can tap the arrow to select a status.

- [ ] no arrow visible in status field while in view mode
- [ ] arrow visible in status field while in edit mode
- [ ] the above two criteria should apply to both contacts and groups

**Example**
![Screenshot_20201101-070507](https://user-images.githubusercontent.com/26180602/97806868-c9d0ae00-1c2b-11eb-97bd-2a4ed3b3faeb.png)

**Comment by raschdiaz** [comment]
Hi @ericchen59 we implemented the change for Android:

[https://drive.google.com/file/d/1kHaYyxn_sYjAloYa4MdRMlWXXfESKsvH/view](https://drive.google.com/file/d/1kHaYyxn_sYjAloYa4MdRMlWXXfESKsvH/view)

But, by default in iOS, the "arrow" symbol does not appear:
[Nativebase Picker Doc](https://docs.nativebase.io/Components.html#picker-def-headref)
