### ISSUE TITLE
When user has over 5000 contact, app crashes upon loading 

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#497]
<img width="373" alt="Screen Shot 2020-11-17 at 10 31 53 AM" src="https://user-images.githubusercontent.com/26180602/99410213-369ca700-28c0-11eb-87e7-240ae462ff67.png">

**Comment by ericchen59** [comment]
Per @corsacca on Slack:

@David Fernandez @Hans Rasch About the stopper. We started discussing this issue here: https://disciple-tools.slack.com/archives/CFA2S41DK/p1603376774163000
It looks like the mobile app currently tries to load contacts 5000 at a time.  Can we try loading 500 or 1000 at a time? This needs to be fixed for any instance.

Also @Hans Rasch you can log in with your other user and test the app as a multiplier.

**Comment by raschdiaz** [comment]
Hi @ericchen59 @corsacca @zdmc23 after set the pagination to 1000 to the contacts/groups endpoints the app load correctly:

[https://drive.google.com/file/d/1jf_20D-uEv2zU-8W5fZisFwemB0WPPga/view?usp=sharing](https://drive.google.com/file/d/1jf_20D-uEv2zU-8W5fZisFwemB0WPPga/view?usp=sharing)

**Comment by corsacca** [comment]
Brilliant!
