### ISSUE TITLE
Date format defaults...?

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-mobile-app#5]
What about date format - should it default based on your language? Location? (22/5/2019 vs 5/22/2019)

**Comment by yorkaspacher** [comment]
![Screenshot_20190605-112537_Expo](https://user-images.githubusercontent.com/47872338/58969466-c2327e80-8785-11e9-8414-66c4349151b3.jpg)

**Comment by deividfdez** [comment]
Is it ok to leave it to the system to determine how to show date?

**Comment by corsacca** [comment]
System based is good.

**Comment by zdmc23** [comment]
Hi @deividfdez , when I added Baptism Date in mobile app, the app value reflected the format: "30/7/2019" but the API update caused the website to reflect the format: "July 31, 2019".  This is a problem bc it causes the D.T Website Date Widget to be ineffective.  It won't initiate select to the date (see attached screenshots)

![Screenshot from 2019-07-13 15-54-29](https://user-images.githubusercontent.com/191707/61176012-1e5ba000-a587-11e9-86fe-55ed13a6d70b.png)

![Screenshot from 2019-07-13 15-54-44](https://user-images.githubusercontent.com/191707/61176013-1e5ba000-a587-11e9-8bfa-fa3f6e08e6a1.png)

**Comment by deividfdez** [comment]
@zdmc23 we have solved this issue, can you please check?

**Comment by zdmc23** [comment]
Hi @deividfdez , this is still an open issue.  Notice the difference in behavior of the widget, when I set a value months or years in past (anything not current month) in the App, and then open the widget on the Website, it does not show that date in the calendar, but rather shows current date.  If I change the date value on the Website and then open the widget again, it works as expected.

This is LOW priority, so we can leave this open for now, and focus on more important issues.  Thx!

![Screenshot from 2019-10-20 10-27-15](https://user-images.githubusercontent.com/191707/67161029-9ffc6000-f324-11e9-82d7-d5db26e59d6d.png)
![Screenshot from 2019-10-20 10-28-04](https://user-images.githubusercontent.com/191707/67161030-a094f680-f324-11e9-9636-9fd945a5d3f3.png)

**Comment by yorkaspacher** [comment]
@zdmc23  you asked me to review and close this, but I believe it is now YOUR open issue... :-) I'll leave it and let you mark it closed when your above issue has been resolved

**Comment by cairocoder01** [comment]
This issue has two different things described in it that I think we need to separate. The initial issue that @yorkaspacher reported was for the display/formatting of dates based on the user's location. That would be the implementation of the momentJs library to choose the date format based on locale.

The issue the @zdmc23 reported is a bug with the saving of dates. Since that is separate from the original issue and different than the current title, can you move that to a separate issue @zdmc23?

**Comment by zdmc23** [comment]
Relates to #75

**Comment by zdmc23** [comment]
Superseded by #75
