### ISSUE TITLE
Show # of search results

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#504]
User Story: as a user, I want to see the number of contacts loaded on my screen, so that I will be able to better understand the relevance of my search keywords

Acceptance Criteria:
- [ ] user is able to see visual feedback regarding how many contacts are currently showing from a search
- [ ] user is able to see how many contacts are currently loaded

**Comment by zdmc23** [comment]
Resolved by https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/4f57e671a9c99ba3265ad50d1b59d24def7b5038
