### ISSUE TITLE
Consider a different color instead of red to indicate either Closed or New Contact

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#507]
Website has red color to indicate status of Closed and New Contact - they both determine some kind of next step. However, on the mobile app, having both Closed and New Contacts indicated by a red dot make it difficult to quickly scan the list to see how much "work" you'll have to do with New Contacts.

**Comment by zdmc23** [comment]
App color for these fields is driven by website settings as of v1.10
