### ISSUE TITLE
Search is not working properly

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#509]
Search is not working properly, and it may be related to #497 implementation

Observed on iOS 14

Steps to reproduce:
1. Login
1. Search for any Contact not in initially returned list

![509-broke](https://user-images.githubusercontent.com/191707/99924628-10846600-2d09-11eb-83f6-6a9577005fb8.PNG)

Contact exists and is assigned to my user

![509-works](https://user-images.githubusercontent.com/191707/99924643-1a0dce00-2d09-11eb-83c4-106759b5809c.PNG)

**Comment by raschdiaz** [comment]
Hi @zdmc23 , the search bar works with the current list of contacts/groups for online/offline modes.

**Comment by zdmc23** [comment]
Hi @raschdiaz , that is not acceptable for a user in online mode.  Please check this video: https://youtu.be/tYOmYEVw-fU

In this case, I scroll through hundreds of contacts, click `Load More` and I still cannot search for the Contact that I want (`Yorkoffline Test`).  We cannot ask the user to scroll through hundreds and hundred of Contacts.  The mobile website enables search and it uses the same API that the mobile app has available to it.  If a Contact is not available in the persisted local data, then we should be making an API search request to return it.  (It should be the same for Groups).

**Comment by raschdiaz** [comment]
Hi @zdmc23 , then, we can implement the following approach: 

Detect the current ONLINE/OFFLINE state to do the "text search".

**ONLINE**: Do a request to get the results, add/update the results to the persisted list.

**OFFLINE**: Filter the persisted list.

**Comment by zdmc23** [comment]
Hi @raschdiaz , I would propose a slightly revised version of that approach:

1. Filter the persisted list
2A. If Contact/Group exists in persisted list, Then display
2B. Else, Detect the current ONLINE/OFFLINE state
3A. If ONLINE, then do a request to get the results, add/update the results to the persisted list
3B. If OFFLINE, then display an error message letting the user know the situation. More on error message directly below:

If OFFLINE and not present in persisted list, then notify the user with something like the following:

"Error: Unable to locate your record in local device storage.  The device is currently offline and unable to perform a online search of the database, and it's possible that all available records are not cached to the local device storage.  If you anticipate being back online soon, and you think that your record is available in the database, then you can wait and search again later.  Otherwise, you may choose to create a new record while you work offline and merge the record later."

+ @ericchen59 @ahillbilly , any thoughts on shortening that error message?  We can put it to the Slack channel for some input

**Comment by ericchen59** [comment]
@zdmc23 

shortened version:

> "Error: Unable to locate your record in local device storage. Either: 1) create a new record and merge once online, or 2) get online and try your search again"

original version:

> "Error: Unable to locate your record in local device storage. The device is currently offline and unable to perform a online search of the database, and it's possible that all available records are not cached to the local device storage. If you anticipate being back online soon, and you think that your record is available in the database, then you can wait and search again later. Otherwise, you may choose to create a new record while you work offline and merge the record later."

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 see the following video with the implementation:

[https://drive.google.com/file/d/1oN7mMhAHzWDhvQVUSpgLBhk7mgoFZ3IB/view?usp=sharing](https://drive.google.com/file/d/1oN7mMhAHzWDhvQVUSpgLBhk7mgoFZ3IB/view?usp=sharing)

**Comment by zdmc23** [comment]
Nice @raschdiaz !  Thx
