### ISSUE TITLE
Own user not available in "Assigned To" list

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#51]
Steps to Reproduce:
1. Create a New Contact in D.T Website (Contact is automatically assigned to your User)
1. View newly created Contact in Mobile App (observe that "Assigned To" is not populated IF your User is not included in the drop-down list; e.g., "zdmc23")

![Screenshot from 2019-10-20 09-48-30](https://user-images.githubusercontent.com/191707/67160497-6412cc00-f31f-11e9-82fb-26a50c89dffc.png)

**Comment by zdmc23** [comment]
![E89ED627-1554-48AF-B595-C2ECF46422B2](https://user-images.githubusercontent.com/191707/67160506-860c4e80-f31f-11e9-87c0-813d61398b42.png)
![6CFEB0E5-10E4-4E11-8800-F2857D4E3AC8](https://user-images.githubusercontent.com/191707/67160507-860c4e80-f31f-11e9-80ef-90c71f0142c5.png)
![2C6C3039-7206-4C0A-8E78-D949264ACADA](https://user-images.githubusercontent.com/191707/67160508-860c4e80-f31f-11e9-955f-74dbb9792c53.png)

**Comment by zdmc23** [comment]
I didn't have time this AM to confirm whether the API is returning the proper "assigned_to" name, or whether the API should include the current User as part of "wp-json/dt-posts/v2/contacts/compact" request.  Perhaps we simply add it in the Mobile App at LoginScreen or Groups Saga

**Comment by corsacca** [comment]
wp-json/dt-posts/v2/contacts/compact just returns a limited number of results. It is meant to work in a typeahead where you start writing and it returns the matching results (5 of them)

**Comment by corsacca** [comment]
The name of the assigned_to is included in the contacts fields

**Comment by raschdiaz** [comment]
We propose to get **all** the contacts by using the 'wp-json/dt/v1/users/get_users' end-point. This to can achieve the same flow in the OFFLINE mode. Are you agree?.

**Comment by deividfdez** [comment]
@zdmc23 @corsacca  can you please let us know your comments on our proposal so we can move on with this issue?

**Comment by corsacca** [comment]
@raschdiaz @deividfdez 
I think there are 2 pieces:
1. When displaying the assigned to name get the value form the contact fields, not from the user list.
2. When editing the assigned to, show or query against a cached list of users. Then update the contact assigned to on the contact and display the name. I'll need to modify the endpoint so you can paginate the list of users.

**Comment by raschdiaz** [comment]
Hi @corsacca . About the second 'piece', why you mention the 'pagination' feature?.

**Comment by corsacca** [comment]
> Hi @corsacca . About the second 'piece', why you mention the 'pagination' feature?.

@raschdiaz if you want to cache the users locally, you'll need a way to get the whole list of users (at least the ones they have access to)

**Comment by corsacca** [comment]
Here is documentation for the endpoint with a way to get all users: https://github.com/DiscipleTools/disciple-tools-theme/wiki/Users

**Comment by mikeallbutt** [comment]
> > Hi @corsacca . About the second 'piece', why you mention the 'pagination' feature?.
> 
> @raschdiaz if you want to cache the users locally, you'll need a way to get the whole list of users (at least the ones they have access to)

I would need to have all users in the app cache. If it will be lots of data that uses lots of space, then at least their names and maybe contact details.

**Comment by raschdiaz** [comment]
Ok @corsacca , thanks.

**Comment by raschdiaz** [comment]
Hi @corsacca , i have updated the users end-point in the mobile-app. But when i test the 'Zac' flow. The new contact does not appear in the end-point response (wp-json/dt/v1/users/get_users?get_all=1).

**Comment by corsacca** [comment]
@raschdiaz i added a new user (corsaccaflow) and the user appears in the list.
It looks like you recently added a user, but left the user role as "registered". User's will need to have a role like "Multiplier", "Dispatcher" or other that have access to contacts.
See more about roles here: https://disciple-tools.readthedocs.io/en/latest/Disciple_Tools_Theme/getting_started/roles.html

Also, if your role is multiplier, then the list will only show you the users you are allowed to see (the ones you have interacted with or given access to).
Does this resolve the issue?

**Comment by raschdiaz** [comment]
Hi @corsacca i test it the flow again with your indication and work correctly, thanks!.

**Comment by zdmc23** [comment]
![858E2506-6980-42FE-AD1A-22E4B02409B4](https://user-images.githubusercontent.com/191707/68530763-60001b80-02d9-11ea-8b20-2323abcbda8b.png)

**Comment by zdmc23** [comment]
Verified

https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/94
