### ISSUE TITLE
In Custom Tile - date of birth between View and Edit mode do not match

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#514]
per @mikeallbutt's instance

![Screenshot_20201202-131358](https://user-images.githubusercontent.com/26180602/100968757-f2d0b100-34ff-11eb-9028-9a0529bbc59f.png)
![Screenshot_20201202-131339](https://user-images.githubusercontent.com/26180602/100968760-f3694780-34ff-11eb-8bd9-e049901e92e2.png)

**Comment by raschdiaz** [comment]
Hi @ericchen59 @zdmc23 see the following video with the implementation:

[https://drive.google.com/file/d/1pQc_kxZuB52QYOYDjSEBYqL1AniCzCJs/view?usp=sharing](https://drive.google.com/file/d/1pQc_kxZuB52QYOYDjSEBYqL1AniCzCJs/view?usp=sharing)

We made several test using multiple time zones (like -5GMT, +4GMT and others).
