### ISSUE TITLE
After "mark all", in-app notification badge with count does not go away

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#515]
per @mikeallbutt's instance

Was not able to replicate issue on @ericchen59's iOS 14.2.1

<img width="702" alt="Screen Shot 2020-12-03 at 12 41 18 AM" src="https://user-images.githubusercontent.com/26180602/100969142-9b7f1080-3500-11eb-9b49-bff44a06f655.png">

**Comment by mikeallbutt** [comment]
This was seen on a Motorola g 6 using Android 9.

**Comment by zdmc23** [comment]
A known issue until we can upgrade to React Navigation 5.x and use `useIsFocused` hook: https://github.com/react-navigation/react-navigation/issues/1171
