### ISSUE TITLE
Transition conversation (Zach and TDM)

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#518]
@zdmc23 - can you shrae a little bit more how big this particular work will take? (hours, etc)

**Comment by zdmc23** [comment]
Hi @ericchen59, I anticipate at least 2 @ 1 hr meetings.  After the first 2, we can decide whether any additional meetings are necessary.  Thx!

**Comment by zdmc23** [comment]
We met for 1 hr on 12/10 and covered my open questions. Thx TDM Team!
