### ISSUE TITLE
Expo (Android 9, oikos.disciple.tools and iOS 14.2.1, dtappdemo.wpengine.com) - tapping Save button does not produce a result

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#521]
Re @mikeallbutt: 
<img width="352" alt="Screen Shot 2020-12-07 at 10 51 05 AM" src="https://user-images.githubusercontent.com/26180602/101372638-1dad6300-387a-11eb-906d-64c94668a94e.png">

Areas so far:
- [ ] assign second subuser
- [ ] changing status to Closed
- [ ] Changing group status

To do:
- [ ] reproducible in other Expos?

**Comment by ericchen59** [comment]
replicated on iPhone 12 mini, iOS 14.2.1

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @ericchen59 We test this flows the following device:

Android: 9
Expo: 2.18.4

But we cant reproduce this error, the app works as expected.

This error is presented in ONLINE or OFFLINE mode?.

**Comment by ericchen59** [comment]
Flow works on iPhone 12, iOS 14.2.1, Expo 2.18.2 before and after a reinstall of the app and expo.

Let's consider this resolved.

cc @mikeallbutt
