### ISSUE TITLE
Applying custom filter crashes app

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#523]
re: @mikeallbutt (Android 9)

Flow: https://drive.google.com/file/d/1yV0mTYcmCsJ4sQ1GWPL4a4O4GmiHGnvj/view?usp=sharing

**Comment by raschdiaz** [comment]
Hi @ericchen59 we try to replicate this issue without success.

We found another issue that causes the filter does not return results, this can be added to another issue.
