### ISSUE TITLE
Move Filter button from (Contacts, Groups) into another location

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#526]
[DTMA-33]

[DTMA-33]: https://discipletools.atlassian.net/browse/DTMA-33

**Comment by mikeallbutt** [comment]
Move it from the bottom to the top and into the kebab menu on the right side.

![Screenshot_20210128-224620.png](https://user-images.githubusercontent.com/43966676/106232910-d2993780-61ba-11eb-80c6-bf8dfe361fc5.png)
