### ISSUE TITLE
Contact>Edit>change status, cannot save

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#528]
I was looking at another bug (cannot see status), and when I tried the workflow: Contact>Edit>Change Status>Save, I was not able to save

Flow: https://drive.google.com/file/d/1mKVoSQPf1fzPuyXGvFSHI6Uqb12og6Nb/view?usp=sharing

**Comment by raschdiaz** [comment]
Hi @ericchen59 we found this issue working in the #509 issue. We already fix this.
