### ISSUE TITLE
Locations list is not complete

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#53]
If i start typing "Fra" for France nothing shows up. It needs to query the API for matching locations

**Comment by cairocoder01** [comment]
## Requirements ##

- [ ] When initially showing locations list, load locations stored in state/local storage
- [ ] When user enters search query (while online), an API request should be made and the results inserted into the locations list once the API response is received.
- [ ] When user enters search query (while offline), location list should act as it currently does to only search the locations available in the state.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 , when performing the implementation, we notice the following behavior testing the following flow:

- The user log-in (ONLINE MODE)
- The mobile app get the 'locations' list (queries in log-in) (only a few locations) and persist it in the storage.
- The user write a keyword in the 'locations' field, the mobile app does the request to the API, get the locations and persist only new ones.
- The user restart the app and log-in again (OFFLINE MODE)
- The app use the persisted list of locations and show result in the corresponding fields.

This flow works as expected, but this implementation have the following situation:

If the user log-in (ONLINE MODE), search new locations, restart the app and log-in again (ONLINE MODE), the 'locations' list will be replaced with the new data retrieved (queries in log-in).

We suggest to not replace the 'locations' list after login (if there are previously stored locations), but this can achieve more time than expected.

What's your opinion about it?
