### ISSUE TITLE
More clearly indicate a contact is closed or open

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#531]
When selecting from a list of contacts for _Assigned to_ or _Subassigned to_, the web app uses a "light gray" font color to indicate a contact record is **closed**. A similar way to indicate a contact as closed or open when looking at a list of contacts on the mobile app would be helpful.

![Screen Shot 2020-12-17 at 2 46 00 AM](https://user-images.githubusercontent.com/26180602/102458270-00af2780-4012-11eb-9137-c9587edbd3f9.png)

**Comment by squigglybob** [comment]
@zdmc23 I'm happy to have a look at this one as my first issue...

**Comment by zdmc23** [comment]
Go for it! You will get your first encounter of our kludgy bottom sheet
