### ISSUE TITLE
Adjusting a Custom Filter's behavior when contact is not in local app cache

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#537]
**From @zdmc23 ([ref Slack convo](https://disciple-tools.slack.com/archives/CFA2S41DK/p1609453978393700)):**

> when I select a Custom Filter having a Contact that I do not have in local app cache, then I search for it and it seems to download, and then I can see it in the Custom Filter (as expected), but if I refresh then it disappears and if I navigate back to the Custom Filter then it is gone.

**Flow video:**
https://drive.google.com/file/d/12R3mC6fb7pkpb3C_UKUIULuPEoOp83e0/view?usp=sharing

**Desired behavior:**
1. If the user clicks on a Custom Filter and we do not have any results in local/offline cache, and if we are ONLINE, 
2. then we should go ahead and auto-refresh and run the query for that particular filter.

**Additional Info:** 
<img width="359" alt="Screen Shot 2021-01-06 at 12 45 47 AM" src="https://user-images.githubusercontent.com/26180602/103733792-87737680-4fb8-11eb-8bdc-32be51faea1b.png">

**Comment by raschdiaz** [comment]
Hi @ericchen59 , see the following video to see this implementation:

[https://drive.google.com/file/d/10m85eDOuN825dmjRjhIjqDR0XYquGbsR/view?usp=sharing](https://drive.google.com/file/d/10m85eDOuN825dmjRjhIjqDR0XYquGbsR/view?usp=sharing)

FYI:

1. The filters are working the following way: 
       When a user execute a filter (select an option filter, write a text):
              - ONLINE: The app will gonna do a request, get the results, merge the data (add new records and update the existing records) and show the results.
              - OFFLINE: The app will gonna execute the filter and show the results persisted in the mobile.
       This way, we avoid following situation: The website create a new contact called "Hans". The user refresh the contact list in the web app, but, in this situation, the app already have several persisted contacts with a name that contains "Hans". Then the app will gonna show the persisted records filtered, but, the mobile app will not execute the request to get the new record (because the result of the filter is not empty).

2. The records are sorted according to the 'sort' props,  returned by the 'wp-json/dt/v1/users/get_filters' end-point, if the filter does not have a sort prop, the app will gonna use the 'Date Modified' sort (desc) by default. This sort will be used in OFFLINE mode by default.

3. The pagination works in active filters (Filter by text, selected option) or not.

4. Several tests were made on the dtdemo site, using multiple devices (like android and iOS).
