### ISSUE TITLE
Show app version number on login screen and settings screen

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#54]
The expo version number set in `app.json` should be displayed in a muted/subtle font/size on the login screen (bottom right) and the settings screen.

## Requirements ##
* Show app version on Login screen in light font and small size at the bottom of the screen
* Show app version on Settings screen in light font and small size at the bottom of the screen

**Comment by mikeallbutt** [comment]
It would be helpful to have on the settings page useful information about the app and the phone too. So that a user can maybe copy and paste the text like OS version and make & model of phone - so that they don't have to go and find that in the OS settings page.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt . I have done this issue. In the end of the day i will publish a new version with this change.

**Comment by cairocoder01** [comment]
I'm unable to see this change. Can you confirm it is published to https://expo.io/@hans.rasch/discipletoolsapp @raschdiaz ?

**Comment by cairocoder01** [comment]
@raschdiaz This is looking good. A small update:

* [ ] (see screenshot below) Can you align the version on the login screen to the bottom of the screen (as it is on the settings screen)?
* [ ] Comment on which pull request has the code for this issue

![Screenshot_20191104-125515](https://user-images.githubusercontent.com/44169599/68116572-d977c280-ff03-11e9-82d0-bd9ebfc2992b.png)

**Comment by deividfdez** [comment]
@cairocoder01 we are working on the changes and will update ASAP

**Comment by raschdiaz** [comment]
Hi @cairocoder01 i have implemented this update. Today i will do the respective pull-request of all Sprint 9 branches (this issue has the branch 'sprint-9-issue-54').

**Comment by zdmc23** [comment]
Verified

![CF2C4341-7427-4772-BBA7-B4506C9B9389](https://user-images.githubusercontent.com/191707/68530846-385d8300-02da-11ea-9aa8-1017e9e8ab96.png)
