### ISSUE TITLE
Improve the field sort order on records 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#545]
On different screens some of the fields should be moved for better flow.

In the attached images the assigned to is the last field but should be before the sub-assigned field - which better resembles the web version. 

![Screenshot_20210127-124103.png](https://user-images.githubusercontent.com/43966676/106038390-84dadd00-609d-11eb-8bbe-98fe2e4ca170.png)

![Screenshot_20210127-123950.png](https://user-images.githubusercontent.com/43966676/106038431-915f3580-609d-11eb-9150-d129c84b251f.png)

**Comment by zdmc23** [comment]
Note that the D.T API does not return an `order` property for Groups like it does for Contacts.  We need to open an Issue on D.T Theme to address, and then we can resolve in mobile

**Comment by zdmc23** [comment]
Reopening to fix bug that occurs when `order` list is present but some fields are missing (i.e., Leader Count, Member Count present, but missing Members List)
