### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#546]
Implement login timeout, so login does not load indefinitely.

<img width="405" alt="Screen Shot 2021-01-27 at 2 48 57 PM" src="https://user-images.githubusercontent.com/26180602/106045381-da6bb580-60ae-11eb-9f6f-93afac7721f9.png">

**Comment by mikeallbutt** [comment]
If the login automatically and login code are set but the login doesn't work (keeps trying) then there is no way to stop the app apart from force closing it.
