### ISSUE TITLE
Tag is missing on mobile app, but present on web app

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#548]
re: @mikeallbutt - see screenshots

_mobile app_
![Screenshot_20210110-162157](https://user-images.githubusercontent.com/26180602/106055550-861b0280-60bb-11eb-94e7-d617b8918200.png)

_web app_
![Screenshot_20210110-162229](https://user-images.githubusercontent.com/26180602/106053204-8665ce80-60b8-11eb-8ed9-ddabcec4d593.png)

<img width="368" alt="Screen Shot 2021-01-27 at 3 58 08 PM" src="https://user-images.githubusercontent.com/26180602/106053201-85cd3800-60b8-11eb-8dd8-e7efee075fb5.png">

**Comment by zdmc23** [comment]
@mikeallbutt , this appears to be working properly if you reset on website - that is: if you start fresh (remove any not currently working and re-add to the Contact/Group record), then the Tags display properly in the mobile app

Ex. `@case de Ram... y An...` -> `Otro` (see: `kite` and `nocongregante...`)
