### ISSUE TITLE
Add help link to settings screen

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#55]
There needs to be a way for users to submit bugs or issues that they find while using the app. That could be a general email address or could be a link to the disciple.tools website that has a form for submitting issues.

@corsacca If you have a typical process for this for the website currently, could you advise which might be preferable?

## Requirements ##
* Add item to Settings screen titled "Help / Support"
  * (option) Item should act as a `mailto` link to open user's mail client to a new email to 'tbd@disciple.tools` with subject "DT App Support: v{X.X.XX}", automatically adding the current app version in the subject of the email
  * (option) Item should act as a link to an online support form at `https://disciple.tools/tbd`

**Comment by mikeallbutt** [comment]
Another common place to access help would be via the 'menu dots' often located on the top right side of a header. Both locations would be useful to place a text help link.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt , i implemented the first option ( Item should act as a mailto link to open user's mail client to a new email to 'tbd@disciple.tools` with subject "DT App Support: v{X.X.XX}", automatically adding the current app version in the subject of the email ). Can you test it please?.

**Comment by cairocoder01** [comment]
@corsacca Can you advise if there is a support email address we could use for app support requests?

**Comment by corsacca** [comment]
@cairocoder01  We can use appsupport@disciple.tools

**Comment by cairocoder01** [comment]
@raschdiaz This is looking good. A few little updates:

* [ ] Please update the email address to `appsupport@disciple.tools`
* [ ] (see screenshot below) Can you align the version on the login screen to the bottom of the screen (as it is on the settings screen)?

![Screenshot_20191104-125515](https://user-images.githubusercontent.com/44169599/68116572-d977c280-ff03-11e9-82d0-bd9ebfc2992b.png)

**Comment by raschdiaz** [comment]
Hi @cairocoder01 i have implemented this update. The pull-request that include this change is 'sprint-9-issue-55'.

**Comment by zdmc23** [comment]
Verified on Android

![Screenshot_20191109-105551](https://user-images.githubusercontent.com/191707/68531408-e3bd0680-02df-11ea-9796-3efd9bddcdf5.png)

**Comment by zdmc23** [comment]
For iOS, I am not signed in to the Mail app, so I get an error. This is expected, but we should upgrade Expo bc there is a more descriptive error message as of Expo v34.0.0: https://github.com/expo/expo/pull/5622


![7B8BE561-9BBF-461F-AF14-5151BCB8DA3E](https://user-images.githubusercontent.com/191707/68531416-fcc5b780-02df-11ea-9970-b1043019c797.png)
