### ISSUE TITLE
Contact "Locations or Address" field name needs to be aligned "right"

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#554]
per @mikeallbutt 

![Screenshot_20210126-063833](https://user-images.githubusercontent.com/26180602/106375139-9d761c00-6357-11eb-9122-c2d71f32154d.png)

**Comment by mikeallbutt** [comment]
@zdmc23 Other fields are ones that have more than one word in their name like 

- seeker pathway
- connections to contacts
- group coach
- Church start date
- member count
