### ISSUE TITLE
Accurate screenshots of the app for the stores

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#56]
The original screenshots have development testing information and not sample data. Also, some of the UI has changed.

**Comment by cairocoder01** [comment]
This would be great! Thanks @mikeallbutt

**Comment by mikeallbutt** [comment]
The app in Google Play store.
[https://play.google.com/store/apps/details?id=tools.disciple.app](url)

**Comment by mikeallbutt** [comment]
Login screens:

![login-details](https://user-images.githubusercontent.com/43966676/67506434-a9eacf80-f652-11e9-91df-cb9d0e7b4a1d.png)
![login-espanol](https://user-images.githubusercontent.com/43966676/67506435-a9eacf80-f652-11e9-9c20-72921114ac98.png)
![login-languages](https://user-images.githubusercontent.com/43966676/67506437-a9eacf80-f652-11e9-894f-43f46ebd3323.png)
![login](https://user-images.githubusercontent.com/43966676/67506438-aa836600-f652-11e9-9781-b09e4355050e.png)

**Comment by mikeallbutt** [comment]
![contacts](https://user-images.githubusercontent.com/43966676/67506551-e1f21280-f652-11e9-8ab3-25c62468037b.png)
![groups](https://user-images.githubusercontent.com/43966676/67506552-e28aa900-f652-11e9-9951-3e10b3fba2f6.png)

**Comment by mikeallbutt** [comment]
CONTACTS:

![contact-details](https://user-images.githubusercontent.com/43966676/67506601-fc2bf080-f652-11e9-92e1-fe2694774bc7.png)

![contact-details-edit](https://user-images.githubusercontent.com/43966676/67506599-fb935a00-f652-11e9-9bc1-1354d2bb91dc.png)

![contact-progress](https://user-images.githubusercontent.com/43966676/67506603-fc2bf080-f652-11e9-8259-b1de0d2da596.png)

![contact-comments](https://user-images.githubusercontent.com/43966676/67506597-fb935a00-f652-11e9-9608-56c4754f5868.png)

![contact-activity](https://user-images.githubusercontent.com/43966676/67506596-fb935a00-f652-11e9-8757-e34757a340b3.png)

![contact-connections](https://user-images.githubusercontent.com/43966676/67506598-fb935a00-f652-11e9-94eb-67b0ab9370dd.png)

**Comment by mikeallbutt** [comment]
GROUPS:

![group-details](https://user-images.githubusercontent.com/43966676/67507189-0d293180-f654-11e9-858f-be301fbaa89e.png)

![group-progress](https://user-images.githubusercontent.com/43966676/67507193-0dc1c800-f654-11e9-8411-c3c9efe0f20b.png)

![group-comments](https://user-images.githubusercontent.com/43966676/67507187-0d293180-f654-11e9-85a7-1cf2b35cf00b.png)

![group-groups](https://user-images.githubusercontent.com/43966676/67507191-0d293180-f654-11e9-8d54-1482de5d2552.png)

![group-groups-edit](https://user-images.githubusercontent.com/43966676/67507190-0d293180-f654-11e9-901d-1e735dad36af.png)

**Comment by mikeallbutt** [comment]
SETTINGS:

![settings](https://user-images.githubusercontent.com/43966676/67507327-4b265580-f654-11e9-861c-16d506101e39.png)

![settings-languages](https://user-images.githubusercontent.com/43966676/67507326-4a8dbf00-f654-11e9-8b7f-714290b2ce81.png)

**Comment by mikeallbutt** [comment]
Who is going to make these changes to the images in the stores?

**Comment by mikeallbutt** [comment]
@zdmc23 I need access to the stores so I can make these image changes.

**Comment by corsacca** [comment]
@mikeallbutt usually the android has 4-5 screen shots. Which ones are you suggesting for the store?

**Comment by mikeallbutt** [comment]
> @mikeallbutt usually the android has 4-5 screen shots. Which ones are you suggesting for the store?

I was actually thinking of having all the different views displayed. When I consider installing an app I look through all the images to see what it does. I wouldn't have thought it was too much more work to have more images than 4 or 5 (and I am happy to do the work too).

**Comment by mikeallbutt** [comment]
What images do people want? I think we should do all these as it shows the app can do.

1. Login screen
2. Login languages
3. Contacts List
4. Contact Details
5. Contact Details Edit
6. Contact Progress
7. Contact Comments
8. Contact Connections
9. Groups List
10. Group Details
11. Group Progress
12. Groups Groups
13. Groups Groups Edit
14. Group Comments
15. Group Connections
16. Notifications
17. Settings languages

**Comment by mikeallbutt** [comment]
The current Play store images are these. They need to be replaced.

<img width="702" alt="Screenshot 2019-12-11 10 34 09" src="https://user-images.githubusercontent.com/43966676/70640899-592f3600-1c02-11ea-8460-eb063867f197.png">

**Comment by zdmc23** [comment]
Hi @mikeallbutt , let's do what you have suggested and update the screenshots that contain nonsensical data and replace with more realistic demo data.  However, as mentioned, let's not post post 17+ images bc the app is still rapidly changing with each release, and so that means lots of screenshot updates across all languages.

I would suggest no more than 7 images with the most important and exciting features, and then have English, Arabic, Spanish, and Turkish to begin with.  If you can get those to me, then I'll update the App and Play Store during the upcoming release, which we are currently targeting for this weekend or early next week.

**Comment by mikeallbutt** [comment]
@zdmc23 sounds good. So what would be the screens that you think are needed at the moment?

**Comment by mikeallbutt** [comment]
> @zdmc23 sounds good. So what would be the screens that you think are needed at the moment?

What screens and what languages and where do we need to put the images so they can be easily accessed?

**Comment by zdmc23** [comment]
@mikeallbutt let’s stick with 5, but we need them for each language in the app. I can take half and you take half

**Comment by mikeallbutt** [comment]
> @mikeallbutt let’s stick with 5, but we need them for each language in the app. I can take half and you take half 

OK. In the play store there are currently 6 images. I think the first one should be removed and replace it with the login page. (or just drop it all together?) 

- login 
- record list page 
- contact details page 
- group progress edit 
- notifications all
- settings 

@zdmc23 how about you do IOS and I will do Android. 

Let's use the same login id of someone. 

Let's only do languages for some stores for now. 

- English for USA/default 
- RTL second in the list 
- Spanish

What other stores will uses be using?

**Comment by zdmc23** [comment]
Good enough as of v1.10
