### ISSUE TITLE
in Edit mode, Contact Status drop down arrow is missing 

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#561]
Makes changing the Contact Status a bit unintuitive.

User story: As a user, I want to know when I can change contact status

![Screenshot_20210127-194330](https://user-images.githubusercontent.com/26180602/106375733-bcc37800-635c-11eb-96e2-6123e3390700.png)

**Comment by mikeallbutt** [comment]
While fixing this @zdmc23 it would be good to make it the same width as the other fields below - with a little space on the left side.

**Comment by zdmc23** [comment]
Also fixed for `Groups`
