### ISSUE TITLE
Records don't allow for no name

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#578]
The DT theme allows for records to NOT have a name. The DT app forces each record to have a name. If a record doesn’t have a name (in the app), when you try and save the record an alert message is triggered and the data/record can't be saved until a name is put in the name field.

Not sure what the solution needs to be. I think all records should have a name.

**Comment by zdmc23** [comment]
Can we think of any good reason to have a record without a name?  If not, then we prob want to open an issue for the WP Theme to prevent it

**Comment by micahmills** [comment]
Hey Zach this came up on the theme repo. https://github.com/DiscipleTools/disciple-tools-theme/issues/1144

Generally a user would have a name but there is a case where you might be interacting with a person and all you have is their social media handle or maybe an alias they have given you want to track the conversation but don't yet have their name. Leaving it blank allows you to save the data and add the name at a later time. 

This is undoubtably a rare case, but it does come up from time to time.

**Comment by zdmc23** [comment]
Thx for the use case @micahmills ! 

I assumed that post `title` (which we map name to if I am not mistaken) was a required field in WP.   If not (and I double checked the WP docs and it seems that it isn't, or at least isn't stated to be), then sure, we can permit it in the mobile app too.

For the Theme, is the requirement that at least 1 identifiable field (i.e., SM handle vs simply Location) has to be entered?  Does the Theme reject under any circumstance, or permit an empty record?  Thx!

**Comment by micahmills** [comment]
So I looked at this a bit further. In the theme we did make the name required on contact creation, but once the contact is created you can edit the name and at that point it can be left blank. I think the use case of not having a name but having other identifiable information is valid, but we need to make sure we are consistently requiring or not requiring a name across the theme and mobile app. 

@corsacca what do you think about this?

**Comment by corsacca** [comment]
All records should have a name. That is pretty much the only requirement for a record.
@todo theme API: reject setting an empty title field. @todo theme front end: Obvious UI disallowing empty name.
For the mobile app i'll let you determine if any changes are needed.
