### ISSUE TITLE
Location search in local language

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-mobile-app#587]
Hi all, 

In a slight side note, I would like to have the location field search for addresses in the local language - in our case Azerbaijani. This would be an important step in delegating contacts to multipliers. OR if possible we could have a limited number of details such as a drop down menu for City and then from there people could select their Neighbourhood the contacts could then be delegated to multipliers on the basis of pre-set location names. Is this possible?

Thanks!

Ben

_Originally posted by @benmclure in https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/586#issuecomment-801769486_

**Comment by benmclure** [comment]
Thanks ahillbilly. I should probably mention that this would be needed for the webform. Thanks!

**Comment by ahillbilly** [comment]
@benmclure, can you confirm whether the web app is operating as expected and this feature is simply missing from mobile, which I think is the case.  On the web app, do you have a mapbox key and google maps key installed?

**Comment by benmclure** [comment]
@ahillbilly, The web app seems to be working fine and I do have mapbox key and google maps key installed.

<img width="408" alt="Screenshot 2021-03-18 at 1 52 43 pm" src="https://user-images.githubusercontent.com/80407688/111607013-4803aa80-87f1-11eb-8183-02fdbe1a2579.png">

As you can see in this picture, I have placed the web form into my website and under the location entry input says "search location" in English and of course the spelling of locations is also in English, which I think would be off putting for some seekers.

<img width="414" alt="Screenshot 2021-03-18 at 1 54 59 pm" src="https://user-images.githubusercontent.com/80407688/111607323-90bb6380-87f1-11eb-8cab-5a2a383c067a.png">

**Comment by ahillbilly** [comment]
Ok, the webform issue needs to be logged as an issue on the webform plugin.  Can you copy there?

**Comment by benmclure** [comment]
@ahillbilly yes! Thanks for pointing me in the right direction.

**Comment by zdmc23** [comment]
App does support search in local language, so closing this
