### ISSUE TITLE
Use different colours for each status type 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#588]
Currently the status of a record when it is archived is set to red. The same colour is used for a new contact. The record of new needs to be followed up asap, hence the colour red to alert the user to attend to this record. But the archived record is not needing to be updated.

I suggest that the archived colour be changed to - possibly a grey.

![Screenshot_20210319-052733_DT.png](https://user-images.githubusercontent.com/43966676/111774059-91490e00-8874-11eb-91b2-ffa1a5a9e087.png)

**Comment by ericchen59** [comment]
+1 on gray, I think that’d be a great idea
