### ISSUE TITLE
Seeker Path not being adjust in offline mode

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#59]
When [Edit] ~~adjusting Faith Milestone icons or~~ using the Quick Actions buttons, the Seeker Path does not reflect any changes while in offline mode. The changes become visible only after taking the app back online.

**Comment by cairocoder01** [comment]
I can't reproduce the problem setting Faith Milestones. If I set my app in offline mode and edit the Faith Milestones, I do see it reflected in the UI. If you can give steps like below for how to reproduce the problem, that would be most helpful.

I can reproduce the Quick Actions issue though:

### Expected ###
When using quick actions while app is in offline mode, the seeker path for the contact should be updated in the Progress tab

### Actual ###
Using quick actions while in offline mode does not change the Seeker Path until the app comes back online

### Steps to Reproduce ###
1. Switch app to offline mode (or go into airplane mode)
2. Find contact whose Seeker Path is "Contact attempt needed"
3. Select Quick Action for Meeting Scheduled
4. Expected: Should see Seeker Path update immediately to "First Meeting Scheduled"

**Comment by mikeallbutt** [comment]
> I can't reproduce the problem setting Faith Milestones. If I set my app in offline mode and edit the Faith Milestones, I do see it reflected in the UI. If you can give steps like below for how to reproduce the problem, that would be most helpful.

@cairocoder01 I wrongly thought that the seeker path  would/should be moved by the Faith Milestones icons. This is not the case. No issue with that therefore, but the quick actions one still persists obviously.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt, I'm going to review this.
