### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#60]
At times I don't need to enter my logins. It remembers me and signs me in immediately. This might be a security problem for some people.

**Comment by deividfdez** [comment]
Is it ok to add checkbox "Remember password"

**Comment by zdmc23** [comment]
Hi @deividfdez , I think that the Auto-login should be enabled by default (as this is typical behavior of the majority of mobile apps), but there should be an option in the settings to enable force login each time.  When combined with PIN code (#146), this would not be so cumbersome.
