### ISSUE TITLE
Go to the web version of the record 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#605]
There are times when some things are not able to be viewed or adjusted on the app but on the web these can be done. Having a way to easily open the same record on the web will make it easy for the app user to do their work.

A menu item of `View on web` could be placed in the list where the `share` record item currently is.

**Comment by zdmc23** [comment]
@mikeallbutt would you please help us identify where specifically in app we should place these links (everywhere needed of course, but it would speed things up if we had a list)

**Comment by mikeallbutt** [comment]
As indicated in the the attached images, the menu item would be available in the kebab menu for the contact record or group record. 

![Screenshot_20210408-091528_Expo Go.png](https://user-images.githubusercontent.com/43966676/114042394-0348bd80-984b-11eb-8913-9d625fbbe60c.png)

![Screenshot_20210408-091453_Expo Go.png](https://user-images.githubusercontent.com/43966676/114042424-09d73500-984b-11eb-8a79-1ddc85f1b35e.png)
