### ISSUE TITLE
Remove back arrow when in edit mode

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#61]
The back arrow should be disabled when in edit mode. 

![screen details editing](https://user-images.githubusercontent.com/43966676/67420711-c3c5dd00-f594-11e9-947d-ea5e44054c91.png)

Pressing the back arrow should only take someone back to the previous view, and not skip directly to the contact or group page.

**Comment by cairocoder01** [comment]
This ends up being a duplicate of the issue for modifying the Edit flow #29
