### ISSUE TITLE
Crashes viewing contacts & groups with bad locations

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#62]
When a location has been assigned to a group or contact but that location is not in the location area of focus assigned in DT, then the app will crash.

**Comment by cairocoder01** [comment]
@mikeallbutt Can you give a specific step-by-step example with something from the dtappdemo site, or does this only happen on other sites?

**Comment by mikeallbutt** [comment]
> @mikeallbutt Can you give a specific step-by-step example with something from the dtappdemo site, or does this only happen on other sites?

Yes this happens on the dtappdemo site too. Using the website you can assign or find a location that is other that the default sample locations. One contact is set to Colombia. That contact will crash the app.

**Comment by raschdiaz** [comment]
To can resolve this, we need to get **all** the locations from the 'wp-json/dt/v1/mapping_module/search_location_grid_by_name?filter=all' end-point, or use another end-point. This to can achieve the same flow in the OFFLINE mode. Are you agree?.

**Comment by deividfdez** [comment]
@cairocoder01 @mikeallbutt do you agree on our approach to solve this issue?

**Comment by cairocoder01** [comment]
Why do you need to do that? From what I see in the API for getting a contact by id, the following is returned for the assigned locations:

```
    "location_grid": [
        {
            "id": 100364232,
            "label": "New York"
        },
        {
            "id": 100380051,
            "label": "Caspian Sea"
        }
    ],
```

This means we already have the name to be displayed. If an assigned location's id is not in the list of locations we have stored, we can just add that location into the list that is displayed. This is all we should need to stop the app from crashing.

Now if we want app users to be able to search and use all of the other locations that are available on the web verstion, that will be a different card and will need a different API, as I believe you're suggesting. However, this bug report should just need some null checking to make sure you're not accessing the property of a location that you couldn't find in the existing list.

In more technical detail:
In ContactDetailScreen, the locations from the API are available in `this.state.geonames`. When a contact is loaded, we should see if all of the items in `this.state.contact.location_grid` are found in `this.state.geonames`. For any contact location not found, add that location into `this.state.geonames`.
Also, when using `this.state.geonames.find(...).name`, you'll need to make sure that the result of the `find` function is not null before accessing its properties.

**Comment by mikeallbutt** [comment]
> This means we already have the name to be displayed. If an assigned location's id is not in the list of locations we have stored, we can just add that location into the list that is displayed. This is all we should need to stop the app from crashing.

That sounds like a great solution @cairocoder01 and will get the app functioning again. (at present it crashes with all DT instances because all my locations are after the first pagination.)

**Comment by raschdiaz** [comment]
Ok, @cairocoder01 i will work this issue how you suggest.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt . I do the work-around in the contacts and groups detail views. Please test it.

**Comment by mikeallbutt** [comment]
> Hi @cairocoder01 @mikeallbutt . I do the work-around in the contacts and groups detail views. Please test it.

Hi @raschdiaz, I used Expo to view the contact with the name "New York" but it crashed the app still.

**Comment by raschdiaz** [comment]
Hi @mikeallbutt , a few moments ago i test this, and worked correctly. Try deleting cache from Expo and test it again please.

**Comment by cairocoder01** [comment]
This seems to be not crashing anymore. @mikeallbutt Can you confirm with the new Expo URL: https://expo.io/@discipletools/discipletoolsapp

**Comment by mikeallbutt** [comment]
> This seems to be not crashing anymore. @mikeallbutt Can you confirm with the new Expo URL: https://expo.io/@discipletools/discipletoolsapp

Correct. I checked a contact that was set to be something other than what would be in the first pagination list, and the app didn't crash viewing the contact nor a group with the same issue previously.

**Comment by zdmc23** [comment]
@raschdiaz @cairocoder01 @mikeallbutt 

The Expo app continues to crash for me on both iOS and Android, even after clearing cache/data and uninstall/reinstall of Expo.  

To reproduce:

1. Login
1. Click "New York" Contact from Contacts List
1. App crashes

**Comment by cairocoder01** [comment]
I now see the crash returning again. Something must have been reverted in a merge or something. @raschdiaz Please make sure the change you made is still in place since it seems to be crashing again.

**Comment by deividfdez** [comment]
@cairocoder01 the update has been made, the reason this happens is that Expo is not showing this. In order to see all changes in Expo, we have suggested a solution on slack dev channel. Please let us know if this is feasible.

**Comment by zdmc23** [comment]
@deividfdez This continues to crash for me with the following steps:

 1. Login
 1. Click "New York" Contact from Contacts List
 1. App crashes

This is with the latest changes to `development` branch being published to the `default` release channel on Expo.  

If it works for the Team locally, then please have them issue a new PR with changes and we'll merge into the `development` branch. Thx!

**Comment by raschdiaz** [comment]
Hi @zdmc23 i test it this fix in the local branch an works correctly, then i try to create a new PR to the 'development' branch, but GitHub show me that all the changes are in the 'development' branch.

**Comment by zdmc23** [comment]
Hi @raschdiaz , can you paste a link to the commit hash that resolved the issue originally?  I'll investigate.  Thx!

**Comment by cairocoder01** [comment]
@zdmc23 I think it was done in https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/97/commits/eea377fac819adfdc55608d10f1a630e278e44ed, which was in #97. 

The app seems to be working and not crashing for me now.

**Comment by zdmc23** [comment]
Reintroduced `screens/Contact/ContactDetailScreen.js` change from https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/eea377fac819adfdc55608d10f1a630e278e44ed with https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/6141edfc6a0ccbe61b51a1672d085b1ffeab442e

**Comment by mikeallbutt** [comment]
When I login to a non demo data install, the app crashes on nearly all my contacts and groups. The only ones that don't crash are ones that don't have the location assigned or the location is set to world.

**Comment by mikeallbutt** [comment]
The other thing I see when using real data, is that my locations list (which has some custom locations and is set to a country level not world) is not mine but the whole DT list.

**Comment by zdmc23** [comment]
NOTE: All of the issues in the comments that follow below were observed using iOS 13.1.3 and D.T v1.1.0 (Expo `release` channel: https://expo.io/@discipletools/discipletoolsapp?release-channel=release) or v1.2.0 (Expo default)

Crash 1 - Steps to reproduce:

1. Select `Saira Tabbal` Contact
2. App crashes (whitescreen)

![F8AE7ACB-D820-46FF-A708-2C765AD5DA6D](https://user-images.githubusercontent.com/191707/69480738-28fd3000-0dd8-11ea-8240-3c47f44d84e1.png)
