### ISSUE TITLE
Suggestion: Remember Login details by default

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#632]
I knew to look for the settings, but most users would not?
It felt a bit frustrating to have to put in everything each time till i changed the setting.

**Comment by zdmc23** [comment]
Hi @corsacca , we did not enable it by default for security reasons.  But I agree that it is inconvenient, esp. if folks do not realize it is an option.  Should we default it or consider the security situation and do a better job of highlighting it (in a demo, or maybe a first launch highlight flow?)
