### ISSUE TITLE
Search Capability - Groups

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#64]
As shown in design prototype: https://xd.adobe.com/view/7080ce9f-27ae-4018-449e-33b6bcc61293-06b1/screen/3ab63fac-11f5-446b-a03a-ba28935434a5/Groups

![image](https://user-images.githubusercontent.com/44169599/67468821-7789a400-f64b-11e9-9584-2596ad1c43a4.png)

## Requirements ##
There should be a search box at the top of the groups list screen that provides the ability to search groups. It should search the following fields:
* Group name

## API Integration ##
Current group list uses the endpoint [/wp-json/dt-posts/v2/groups](https://github.com/DiscipleTools/disciple-tools-theme/wiki/List-posts) which allows search through the `text` parameter (see [documentation](https://github.com/DiscipleTools/disciple-tools-theme/wiki/List-posts#search-parameters)).

## Notes/Exceptions ##
* This issue does **NOT** include the filtering feature which shows in the right side of the design above. The filter icon displayed in the design should not be added as part of this issue.
* This issue is for the Groups screen only - not for Contacts. (separate issue: #28)

**Comment by corsacca** [comment]
@cairocoder01 the `/wp-json/dt-posts/v2/groups` supports both search and filtering. See https://github.com/DiscipleTools/disciple-tools-theme/wiki/List-posts

**Comment by cairocoder01** [comment]
Great! I've updated the requirements above

**Comment by jl0325** [comment]
Group search by name now is working!

![groups_search](https://user-images.githubusercontent.com/10079527/69094807-0c02de80-0a1f-11ea-9ece-6da431d45843.gif)

**Comment by zdmc23** [comment]
Nice work @jl0325 !  :+1:  Would you kindly issue a Pull Request so that I can pull it into the `development` branch and we can test it in Expo?  Thx

**Comment by jl0325** [comment]
Yeah! I'm working to do a PR whit #64 and #28

**Comment by zdmc23** [comment]
Verified

![D6295173-BAEA-4C1B-83CA-BA5C07F3BA37](https://user-images.githubusercontent.com/191707/69166548-6785a880-0ac1-11ea-94b9-da342f0d6c7f.png)
