### ISSUE TITLE
App Offline message is missing on the comment and activity screen 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#641]
The message advising a user that the app is offline is not shown on the 'comments and activity' screen.

![IMG_20220619_062237.jpg](https://user-images.githubusercontent.com/43966676/174478524-34a4d6da-6264-4f2e-bfd6-172992af60d2.jpg)

![IMG_20220619_062250.jpg](https://user-images.githubusercontent.com/43966676/174478527-b6e62d78-72d8-4387-8d32-af4709d3ead3.jpg)

**Comment by zdmc23** [comment]
Resolved by 1d62d6a8f7d0e5a878b0363224fa02d7b81db9b3
