### ISSUE TITLE
Chip stays empty after changing 'assigned to' field 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#659]
When you change who a record is assigned to, the chip that should display the new info is now blank. If you do a pull down on the screen to invoke a refresh of the screen, then the chip will reload correctly.
It should reload without a manual refresh.

![IMG_20220619_103023.jpg](https://user-images.githubusercontent.com/43966676/174489048-94de3e0f-4758-48f3-b480-07fb21bae805.jpg)

**Comment by mikeallbutt** [comment]
The same issue happens when adding a contact record with the 'people groups' field.

**Comment by zdmc23** [comment]
Unable to reproduce now. Fixed since?
