### ISSUE TITLE
Remove empty space character at the end of the search term

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#674]
When using the search box it is common for the keyboard system to add an empty space onto the end of a recognised term. The issue is that the app uses the the empty space character and won't offer the results unless that space character is not there. 

eg. `trent ` (with the ending space) is not the same as `trent` (without the ending space) and if a record does not have the extra space then the record will not be offered as a result (but it should in both cases).

**Comment by jhenterprise** [comment]
Done through trim() will it work @zdmc23
![WhatsApp Image 2022-07-01 at 3 41 44 PM](https://user-images.githubusercontent.com/9843021/176879857-46e98439-82eb-4a7b-ba22-bdf27e9d8a5d.jpeg)
  working fine on my side.

**Comment by mikeallbutt** [comment]
OK so if you have implemented trim and it works then submit a PR please.

**Comment by squigglybob** [comment]
@zdmc23 is this one closed?

**Comment by zdmc23** [comment]
It appears so, must have missed it in the commit msg
