### ISSUE TITLE
Dates in logs are not user friendly 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#686]
The date in the logs are like `Baptism Date: {1654111560} ` and need to be shown in the same way the app user wants depending on their device settings ie. dd-mm-yyyy or mm-dd-yyyy

![IMG_20220621_220820.jpg](https://user-images.githubusercontent.com/43966676/174935375-055985d5-e5fd-4aa3-8f57-ff2da994d554.jpg)

**Comment by jhenterprise** [comment]
@mikeallbutt like this ?
![disciple_tools_activity_log](https://user-images.githubusercontent.com/9843021/175564253-082582b5-3dff-4c2b-9380-65a98746127d.jpeg)

**Comment by zdmc23** [comment]
That looks good @jhenterprise , but @mikeallbutt are we sure this shouldn't be fixed in the API prior to recv'ing it in the app?

@jhenterprise, we use momentjs to translate dates per locale. Are you reusing that? I can point you to an example if you didn't already see it. Thx!

**Comment by jhenterprise** [comment]
Yes, ideally it should be handled through an API endpoint, but don't know the overall architecture as in the web version I saw it is forcefully converted to locale DateTime(as in database this is saved object_note).
First I tried react-native-intl but it is not working in android(Intl.DateTimeFormat not working in android), don't sure momentjs supports locale(but saw in post item hook)?  I used javascript Date function to convert. Should I share the code?

**Comment by mikeallbutt** [comment]
This is how dates are displayed on the theme. (always good to see how it is done there and do similar.

![IMG_20220624_185908.jpg](https://user-images.githubusercontent.com/43966676/175749810-afd915df-23f8-4155-a33b-2fc520ec8776.jpg)

**Comment by jhenterprise** [comment]
thanks, @zdmc23 . Done through momentjs nice and easy :) @mikeallbutt please check the 
![disciple_tools_activity_log2](https://user-images.githubusercontent.com/9843021/175774004-1ec641df-3fb2-452e-aa71-9e1867e4990d.jpeg)
attachment.

**Comment by mikeallbutt** [comment]
Thanks. Looks good.

The same thing needs to be done to the comments and activity screen too.

**Comment by zdmc23** [comment]
@jhenterprise please go ahead and issue a PR. Aa you may already know, if you have a commit message like: "Resolves #686 - (whatever text you want)" then GitHub will auto-close the Issue and reference the commit when the PR is merged. Thx!
