### ISSUE TITLE
Comment Activity - Mention Regex Issue

### ISSUE THREAD

**Issue by jhenterprise** [DiscipleTools/disciple-tools-mobile-app#699]
The regular expression replaces whole content when trying to mention multiple people. Please check the attachment.
In web
<img width="1193" alt="Screenshot 2022-07-01 at 12 25 31 PM" src="https://user-images.githubusercontent.com/9843021/176846036-9a4863ef-6846-4398-ac6d-de26a13960e4.png">
In app
![WhatsApp Image 2022-07-01 at 12 25 53 PM](https://user-images.githubusercontent.com/9843021/176846102-dbd5f294-30d8-403d-91ca-c1a3073425a3.jpeg)

**Comment by zdmc23** [comment]
Resolved by #701
