### ISSUE TITLE
RTL (right-to-left) enabled components

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#71]
*As a* User,
*I want to* view the app in my RTL language
*in order to* ensure expected user experience for those languages

- [ ] Components support RTL
- [x] Form labels are aligned right
- [x] Form field content and placeholders are aligned right
- [ ] Horizontal lists are listed right to left
- [ ] Navigation is shown right to left

**Comment by zdmc23** [comment]
As of 10/20: 

![ss1](https://user-images.githubusercontent.com/191707/67645976-1e976580-f902-11e9-833d-52584566cc23.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23. We have fixed some visual defects in the details views like the FAB icon position in the comments/activities TAB and some icons spacing. 

After some tests we discover a problem with the text alignment: If the texts is not 'RTL' type, this texts are not aligned as expected (see screenshot below). This behavior varies according to the OS. That seem that only way to align this texts its add conditions to set the alignment 'manually', this could take us a little more time than expected. What do you think about this?.

![Captura de Pantalla 2019-11-08 a la(s) 3 17 20 p  m](https://user-images.githubusercontent.com/16809967/68508139-a141ee00-023b-11ea-8872-29fb2b9e9890.png)

**Comment by raschdiaz** [comment]
Hi @zdmc23 i have resolved the conflict presented in the PR. Can you check it out?.

**Comment by jl0325** [comment]
RTL support in contact detail: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/70663097-a37dda80-1c35-11ea-991a-188346e9baf3.gif)

**Comment by zdmc23** [comment]
Crashing on iOS (iPhone XR and iOS 13.1.3)

**Comment by jl0325** [comment]
> Crashing on iOS (iPhone XR and iOS 13.1.3)

This error occurs when you start the application when it is first loaded and has the user language in 'ar'. I did the test in the master branch and the same thing happens. Then there are the changes implemented for this issue, I am conducting a thorough test to detect which of the consumptions is incomplete in the Arabic language and causes the app to close. I'm testing to find what is the problem.

**Comment by jl0325** [comment]
Error in IOS found and solved, it happened due to the change from LTR to RTL, the library restarted the application and did not allow the local storage of the variables.
