### ISSUE TITLE
In-App Notifications (not Push)

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#72]
*As a* PO,
*I want to* have an in-app notifications
*in order to* be aware of updates that relate to me or my team

https://xd.adobe.com/spec/2a03c95d-f952-4825-777e-584c67adbc1b-5c32/screen/55a36009-2711-499c-ad39-cb89387d6aa0/Contacts/

- [x] Notifications Tab Button
- [x] Behavior is similar to Comments/Activities

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/70151420-e4ad4200-16ab-11ea-8559-95cced576aa6.png)

**Comment by jl0325** [comment]
I do a new PR whit the first stable notifications menu.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/70364926-d5212b00-185c-11ea-8689-b13de992148f.gif)

To do, 
- Mark All function
- Button read/unRead fucntions

**Comment by zdmc23** [comment]
Perhaps this is already known bc this is the initial commit for this, but the notifications do not show for me on Android or iOS, even after clicking `All` and `Unread` and `Load More`

![400AAB0E-B9DB-423F-9800-19DED2DA307A](https://user-images.githubusercontent.com/191707/70368242-212c9980-1876-11ea-8117-848c5be03385.png)

**Comment by jl0325** [comment]
> e notifications do not show for me on Android or iOS, even after clicking `All` and `Unread` and `Load More`

Can I use your user to do a test?

**Comment by zdmc23** [comment]
@jl0325 The `Mark All` button doesn't do anything (both iOS and Android).

Steps to reproduce:

1. At least 1 Notification is `Unread`
1. Click `Mark All`

**Comment by zdmc23** [comment]
Verified
