### ISSUE TITLE
Group comments and activity messages by date/time

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#73]
*As a* PO,
*I want to* group comments and activity messages by date/time
*in order to* mimic web app grouping

- [ ] Behavior is similar to web app grouping

**Comment by zdmc23** [comment]
![7E8A27B7-F9FB-45C6-A0AF-66376662906A](https://user-images.githubusercontent.com/191707/74213526-a9109480-4c67-11ea-82af-9c75d5c13bb7.png)
![BDF79EAE-B5A4-4524-A640-47B9A772EA39](https://user-images.githubusercontent.com/191707/74213529-aada5800-4c67-11ea-8e23-9bb517589c9a.png)

**Comment by zdmc23** [comment]
Grouping should by by Date (not DateTime) and by User:

zdmc23                             Nov 22, 2019
  Added to group...
  Removed from group..

hansrasch                         Nov 22, 2019
  Updated status...
  Updated email address...

**Comment by raschdiaz** [comment]
Hi @zdmc23 , working in this issue, we get a problem, when we group the comments/activites by **date** and user, we dont get the list like the web app show us. But, when we sort the comments/activites by **datetime** and user, the list its similar to the web app

Web app comments/activities example (Contact Ramírez):
![image](https://user-images.githubusercontent.com/16809967/95381796-46cb6a80-08ae-11eb-81ed-f8e8333fc4e5.png)

Comments/Activites JSON grouped by **date** and user:
![image](https://user-images.githubusercontent.com/16809967/95381547-eb997800-08ad-11eb-93f5-57bca9eec5e2.png)

Comments/Activites JSON grouped by **datetime** and user:
![image](https://user-images.githubusercontent.com/16809967/95382280-06b8b780-08af-11eb-937d-0f73d986021a.png)
![image](https://user-images.githubusercontent.com/16809967/95382314-13d5a680-08af-11eb-9222-934f609cdcba.png)
![image](https://user-images.githubusercontent.com/16809967/95382344-1e903b80-08af-11eb-9bf1-d46522adb62c.png)
![image](https://user-images.githubusercontent.com/16809967/95382419-3c5da080-08af-11eb-895c-ad5011ac39be.png)

As you can see, when we group the comments and activities by  **datetime** and user, the collection its similar to the seen in the web app.

The problem we found its try to replicate this behavior:
![image](https://user-images.githubusercontent.com/16809967/95382825-dc1b2e80-08af-11eb-92fd-9c09244c38f3.png)

When the user add several comments between a range of time (1 hour we guess), the comments are grouped and it only show the last date of the saved comment.

How the web app group this data?

**Comment by corsacca** [comment]
@raschdiaz 
This is the gist of what the web app does:

//build an array of the comments and activity
let displayed = array of comments and activity

order displayed array by date

//create groupings
- take a first comment/activity
- keep adding comments/activity as long as the user is the same and time is < 1h from the first comment/activity

If you come to a new user or the time is more than 1 hour from the first element, then start a new group.
The date/time displayed for the group is the date of the first element.

The theme code for the grouping can be found here: https://github.com/DiscipleTools/disciple-tools-theme/blob/47948f7dff6b34d1416bf538e64e1a35a9623429/dt-assets/js/comments.js#L317

**Comment by ericchen59** [comment]
@corsacca When the theme code keeps adding comments/activity as long as the user is the same and time is < 1hr from the first comment/activity, what time stamp does the code display? (i.e. the time of the first comment/activity, time of the latest comment/activity, etc?)

**Comment by corsacca** [comment]
@ericchen59 The date/time displayed for the grouped activity/comments is the earliest date in that group.

**Comment by ericchen59** [comment]
@raschdiaz does this give you enough info?

**Comment by raschdiaz** [comment]
Hi @ericchen59 , for the moment, yes.

**Comment by raschdiaz** [comment]
Hi @zdmc23 @ericchen59 @corsacca see the following video with the implementation: [https://drive.google.com/file/d/1fYdcitfZCKQM3K-TTm-HrYsSCPd6gq6a/view?usp=sharing](https://drive.google.com/file/d/1fYdcitfZCKQM3K-TTm-HrYsSCPd6gq6a/view?usp=sharing)

**Comment by raschdiaz** [comment]
Hi @zdmc23 @corsacca @ericchen59 see the following video with the implementation: [https://drive.google.com/file/d/1frCCo5Z3_OTcWw9WAvVC722ni1QUG2Kh/view?usp=sharing](https://drive.google.com/file/d/1frCCo5Z3_OTcWw9WAvVC722ni1QUG2Kh/view?usp=sharing)
