### ISSUE TITLE
Display visual indicators on Contact/Group List page

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#74]
@cairocoder01 said:

I've been thinking about some sort of visual for the contact list screen to make it more easily scannable at a glance after doing some ux reading this week. So I was thinking of what the key status indicator is for each contact in order to maybe use in place of a profile photo beside each contact. It seems to me like the seeker path would be that kind of information. What are the thoughts on using something like these beside each contact in the list? I tried to pull any existing icons from other parts of the app, so only 2-3 would need to be created.

![ss2](https://user-images.githubusercontent.com/191707/67646469-a67e6f00-f904-11e9-91a1-31d6645c8e8b.jpg)

**Comment by zdmc23** [comment]
mikeallbutt said:

This mock-up is useful.
https://xd.adobe.com/view/7080ce9f-27ae-4018-449e-33b6bcc61293-06b1/screen/3cf7701e-dec1-46b4-9753-43c5533516e1/Contact-Details-quick-actions

**Comment by mikeallbutt** [comment]
> mikeallbutt said:
> 
> This mock-up is useful.
> https://xd.adobe.com/view/7080ce9f-27ae-4018-449e-33b6bcc61293-06b1/screen/3cf7701e-dec1-46b4-9753-43c5533516e1/Contact-Details-quick-actions

I think that @cairocoder01 was actually referring to the Contact List screen and not the quick actions buttons.

I agree that having icons will make it faster to scan and sort the lists.

**Comment by zdmc23** [comment]
Per @mikeallbutt

"Set the colours of the Status for each contact to more quickly indicate what status they are. eg. red = new, dispatch needs, closed; orange = not ready, waiting for acceptance, paused; green = active;"

We briefly discussed this in Slack a few weeks back, and a common practice in Messaging apps is to use the dots to denote status (i.e., green dot = active)

See also: #220
