### ISSUE TITLE
Activity log link screen link to online version 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#740]
The activity log screen (accessed from the tile on the home screen) needs a kebab item that gives the user aceess to easily view the data and other metrics on the same instance they are currently using in the app.

The link should be going to:
https://[their dt instance]/metrics/personal/activity-log

The kebab should also have the other standard item that takes them to the documentation.

**Comment by zdmc23** [comment]
Resolved by #752
