### ISSUE TITLE
Upgrade Expo to version 33.0.0

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#8]
SDK 33 provides support for the Android 64-bit requirement (required for all new apps after Aug 1, 2019) and updates from React Native 0.57.1 to 0.59.8. The expo dependency should be upgraded and tested for any breaking changes.

https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c

**Comment by cairocoder01** [comment]
@deividfdez Are you able to include this in an upcoming sprint? After August 1, we won't be able to upload to the Play Store without this, I think.

**Comment by zdmc23** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/bf5b62287d999ae4bb4f9dbe2bd1e546a86bea25
