### ISSUE TITLE
Automatic multiplication of social link

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#85]
When editing a contact and adding a Social Media field, the Facebook field keeps creating new fields, without any user interaction.

View the video of the issue here:
https://drive.google.com/file/d/1vVUNg1sngDafFf60sZGlmLsf7oXThzqu/view?usp=sharing

**Comment by mikeallbutt** [comment]
@zdmc23 I am still getting this in the current version of the development app.

**Comment by mikeallbutt** [comment]
This happens on Android Version 9 on a Motorola g6

**Comment by ahillbilly** [comment]
I am not able to reproduce this on iPhone 10 (Expo)

**Comment by zdmc23** [comment]
@mikeallbutt can you reproduce this issue still?  if yes, then we can decide whether to add to Sprint 14, otherwise let's close it. Thx

**Comment by mikeallbutt** [comment]
This issue seems to be fixed.
