### ISSUE TITLE
FAB Quick action button covers details

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#86]
As can be seen in the attached images, the Fast Action Button covers words. It would be good to have a sufficient space after the last list item so that the final text item can be read.

**Source is covered**
![Screenshot_20191104-092901](https://user-images.githubusercontent.com/43966676/68140705-decc1180-fef1-11e9-8000-f2acd0174cd1.png)

**Baptism is covered**
![Screenshot_20191104-093024](https://user-images.githubusercontent.com/43966676/68140706-decc1180-fef1-11e9-908a-d8948e1bd306.png)

**Ample space after last item**
![Screenshot_20191104-093052](https://user-images.githubusercontent.com/43966676/68140707-decc1180-fef1-11e9-92bf-81f202a7db7c.png)

**Comment by cairocoder01** [comment]
This is good. We should add a sufficient amount of padding to the bottom of any page that has a FAB so that all data can be viewed.

**Comment by zdmc23** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/108

**Comment by cairocoder01** [comment]
Verified in development
