### ISSUE TITLE
Feedback message to look more standard

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#87]
Currently the message "data saved successfully" is green and in the middle of the screen.
I suggest it be made more standardised (see the bottom of the second image) by having it placed at the bottom and in the standard colours and style used by the operating system messages per mobile platform. 

![Screenshot_20190822-061304](https://user-images.githubusercontent.com/43966676/68141034-6c0f6600-fef2-11e9-8630-ec0d0b483446.png)
"

![Screenshot_20191104-093105](https://user-images.githubusercontent.com/43966676/68141197-b0026b00-fef2-11e9-9176-7f087325e8c5.png)

**Comment by raschdiaz** [comment]
Hi @mikeallbutt @cairocoder01 @zdmc23 , What happens if the toast show an error?. This toast have to be at the bottom of the screen?.

**Comment by cairocoder01** [comment]
Yes, all toast messages should be at the bottom.

Here is some further styling:

Normal toast message:
* Background: #E5E5E5, 85% opacity
* Text Color: Normal (black, 100% opacity)

Error toast message:
* Background: #e48481, 85% opacity
* Text Color: #691917, 100% opacity

![image](https://user-images.githubusercontent.com/44169599/68849229-595b1500-06da-11ea-9763-143135e78c13.png)

**Comment by jl0325** [comment]
The change of style of the toast messages was made, and it looks like this.

![feedback-error](https://user-images.githubusercontent.com/10079527/68945543-a0024b00-077e-11ea-843b-77c1c7ce6fc1.png)
![feedback-success](https://user-images.githubusercontent.com/10079527/68945544-a0024b00-077e-11ea-99c7-d6135769f759.png)

**Comment by zdmc23** [comment]
https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/108

**Comment by zdmc23** [comment]
@jl0325 the Toast is too low and is being covered in iOS 

![090C8A2A-F4B7-4C65-8F20-7D85E8126124](https://user-images.githubusercontent.com/191707/68986110-361f8b00-07ea-11ea-9dfb-0f8d042e76ce.jpeg)

**Comment by jl0325** [comment]
High resolution like Iphone 11 Pro now is supported!

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-16 at 09 18 05](https://user-images.githubusercontent.com/10079527/68994716-3c4a5180-0854-11ea-9f80-89e29f569e68.png)

**Comment by jl0325** [comment]
High resolution like Iphone 11 Pro now is supported!

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-16 at 09 34 56](https://user-images.githubusercontent.com/10079527/68994733-5c7a1080-0854-11ea-936c-39683ba38f24.png)

**Comment by zdmc23** [comment]
Verified 

![EEF4E225-97F6-4991-B320-E41A705C4703](https://user-images.githubusercontent.com/191707/68995790-9a306680-085f-11ea-811d-fd1ad38075bf.png)
