### ISSUE TITLE
Remove space from end of URL on login screen

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#88]
When a user types in the URL to login to the app, ensure that there are no spaces after the URL (or in any part of the URL).

The attached image shows what error message is displayed when a space is at the end of the URL.

![Screenshot_20191106-132605](https://user-images.githubusercontent.com/43966676/68330828-89326900-0099-11ea-8a27-49d3af65e90a.png)

**Comment by zdmc23** [comment]
Reopening bc we also need to remove leading whitespace (not only trailing)

![4838AF6B-54CC-40E0-B03D-85C664E7E8DC](https://user-images.githubusercontent.com/191707/72683039-df605700-3aa1-11ea-8acb-923b42f99ed2.jpeg)
