### ISSUE TITLE
Cancel login option

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#90]
Have an option to cancel login when something isn't working and the app login doesn't time out.

**Comment by mikeallbutt** [comment]
@zdmc23 This issue of the app not timing out the login also happens when trying to sign in when the app is offline or the phone is in aeroplane mode. Currently the only way to stop the process is to force quit the app.

**Comment by mikeallbutt** [comment]
@zdmc23 IMO people need an easy as possible login process. If they click login and some details aren't correct, there is no way to stop the process. It needs a 10-15 sec timeout - and/or a cancel login button.
(good issue for an upcoming sprint IMO)

**Comment by zdmc23** [comment]
See also: #196
